//! Regenerate `rust/cli/src/compiled_cli.rs` from the self-hosted CLI-core
//! Ball program (`dart/self_host/cli.ball.json`) — the Rust cli-core adoption
//! route (issue #365), mirroring `ball-engine-regen`
//! (`rust/engine/tool/src/main.rs`, issue #39) almost exactly. The only
//! structural difference: `cli_core` is a plain library of top-level
//! `Program -> String` report functions (no classes, no interpreter loop), so
//! the compiled output is directly callable — no runtime-driving wrapper like
//! `ball-engine`'s `run_self_hosted` is needed; `rust/cli/src/commands/*.rs`
//! calls the generated functions straight.
//!
//! Pipeline:
//!   1. Read `dart/self_host/cli.ball.json` — a self-describing
//!      `google.protobuf.Any` envelope (`{"@type":".../ball.v1.Program", …}`).
//!   2. **Strip the `@type` envelope** (it is not part of the `ball.v1.Program`
//!      schema) before deserializing.
//!   3. proto3-JSON -> `DynamicMessage` -> binary -> typed `Program`
//!      (the same load path `ball-shared`/`ball-compiler` tests use).
//!   4. Compile via `ball_compiler::Compiler` -> Rust source (library mode —
//!      `cli_core` has no runnable entry point).
//!   5. Write `rust/cli/src/compiled_cli.rs` with a NEVER-edit header.
//!
//! `compiled_cli.rs` is a **generated, NEVER-edit** file — fix `cli_core`
//! (`dart/shared/lib/cli_core.dart`) or the compiler and rerun this, never
//! hand-patch the output.
//!
//! Usage (from anywhere): `cargo run -p ball-cli-regen`.
//!
//! Prerequisite: `dart/self_host/cli.ball.json` must already exist — generate
//! it with `cd dart && dart run compiler/tool/gen_cli_json.dart` first (see
//! `dart/compiler/tool/gen_cli_json.dart` and CLAUDE.md's "Build & Test").

use std::path::{Path, PathBuf};

use ball_compiler::Compiler;
use ball_shared::DESCRIPTOR_POOL;
use ball_shared::proto::ball::v1::Program;
use prost::Message;
use prost_reflect::DynamicMessage;

/// The auto-generated banner prepended to `compiled_cli.rs`. The `@generated`
/// marker keeps the file out of manual review churn, and
/// `rustfmt::skip`/broad `allow`s keep the machine-emitted source from
/// tripping lint/format gates it was never hand-authored to satisfy — mirrors
/// `rust/engine/tool/src/main.rs`'s `HEADER`.
const HEADER: &str = "\
// @generated by `cargo run -p ball-cli-regen` from dart/self_host/cli.ball.json.
//
// DO NOT EDIT BY HAND. This is the self-hosted Ball CLI core (info/validate/
// tree/version report functions), compiled from `dart/shared/lib/cli_core.dart`'s
// own Ball encoding through `ball-compiler`. To change it, fix
// `dart/shared/lib/cli_core.dart` (then rerun `dart run
// compiler/tool/gen_cli_json.dart`) or `rust/compiler/`, and rerun the
// regenerator — never hand-patch this file. See rust/cli/AGENTS.md.
#![cfg_attr(rustfmt, rustfmt::skip)]
#![allow(warnings, clippy::all)]

";

fn repo_root() -> PathBuf {
    // CARGO_MANIFEST_DIR = .../rust/cli/tool ; the repo root is four levels
    // up (tool -> cli -> rust -> <repo root>).
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(3)
        .expect("rust/cli/tool must have a repo-root ancestor")
        .to_path_buf()
}

/// Load a `.ball.json` file — stripping the cosmetic `@type` Any envelope —
/// into a typed [`Program`] via prost-reflect (proto3 JSON -> `DynamicMessage`
/// -> binary -> typed `Program`), the same path `ball-engine-regen` uses.
fn load_ball_program(path: &Path) -> Program {
    let json = std::fs::read_to_string(path).unwrap_or_else(|err| {
        panic!(
            "failed to read {}: {err}\nHint: generate it with `cd dart && dart run \
             compiler/tool/gen_cli_json.dart` first.",
            path.display()
        )
    });
    let mut json_value: serde_json::Value =
        serde_json::from_str(&json).expect("cli.ball.json must be valid JSON");
    if let serde_json::Value::Object(map) = &mut json_value {
        map.remove("@type");
    }
    let program_descriptor = DESCRIPTOR_POOL
        .get_message_by_name("ball.v1.Program")
        .expect("ball.v1.Program must be resolvable from the embedded descriptor pool");
    let dynamic =
        DynamicMessage::deserialize(program_descriptor, json_value).unwrap_or_else(|err| {
            panic!(
                "{} must deserialize as a ball.v1.Program: {err}",
                path.display()
            )
        });
    Program::decode(dynamic.encode_to_vec().as_slice())
        .expect("binary re-encoded from the DynamicMessage must decode as a typed ball.v1.Program")
}

/// Function names dropped from `cli_core`'s `main` module before compiling
/// (issue #365; `#362` residual). `auditReport` calls
/// `capability_analyzer`/`termination_analyzer` — separate Dart files pulled
/// in via `import` (not `part`), which `gen_cli_json.dart`'s
/// `resolveDartLibrary` does not merge, and which the Dart encoder therefore
/// leaves as **empty import-stub modules** (0 functions) in `cli.ball.json`.
/// The Dart-engine self-host parity test tolerates this silently (`audit` is
/// simply never invoked — see the doc comment on `_goldenFixtures` in
/// `dart/cli/test/cli_core_parity_test.dart`), but Rust performs whole-file
/// AOT compilation: an unresolved call to `analyzeCapabilities`/
/// `formatCapabilityReport`/`analyzeTermination`/`formatTerminationReport`/
/// `writeln` is a hard `rustc` error, not a latent runtime gap. Dropping the
/// function here (a Rust-target-only, well-documented filter — `cli_core.dart`
/// and `ball-compiler` itself are untouched) keeps the generated file
/// compiling while `ball audit` stays out of the Rust CLI, exactly as issue
/// #365 specifies. Remove this filter once #362 makes `auditReport` fully
/// self-hostable (its Dart source needs no change either way).
const SKIPPED_FUNCTIONS: &[&str] = &["auditReport"];

fn main() {
    let root = repo_root();
    let cli_json = root.join("dart/self_host/cli.ball.json");
    let out_path = root.join("rust/cli/src/compiled_cli.rs");

    eprintln!("[regen-cli] loading {}", cli_json.display());
    let mut program = load_ball_program(&cli_json);
    for module in &mut program.modules {
        let before = module.functions.len();
        module
            .functions
            .retain(|f| !SKIPPED_FUNCTIONS.contains(&f.name.as_str()));
        let dropped = before - module.functions.len();
        if dropped > 0 {
            eprintln!(
                "[regen-cli] dropped {dropped} unsupported function(s) from module {:?}: {:?}",
                module.name, SKIPPED_FUNCTIONS
            );
        }
    }
    eprintln!(
        "[regen-cli] compiling program {:?} v{} ({} modules)",
        program.name,
        program.version,
        program.modules.len()
    );

    // cli_core is a *library* (it has no runnable top-level entry point — its
    // public surface is the info/validate/tree/version report functions),
    // exactly like the self-hosted engine — compile in library mode.
    let compiler = Compiler::new(&program);
    let rust_src = compiler.compile_library();

    let mut out = String::with_capacity(HEADER.len() + rust_src.len());
    out.push_str(HEADER);
    out.push_str(&rust_src);
    std::fs::write(&out_path, &out)
        .unwrap_or_else(|err| panic!("failed to write {}: {err}", out_path.display()));
    eprintln!(
        "[regen-cli] wrote {} ({} bytes)",
        out_path.display(),
        out.len()
    );
}
