// Generated by ball compiler
// Source: wordcount v1.0.0
// Target: Dart

class Counts {
  Counts() : lines = 0, words = 0, chars = 0, blankLines = 0, longestLine = 0;

  int lines;

  int words;

  int chars;

  int blankLines;

  int longestLine;

  void observe(String input) {
    String line = input;
    lines = (lines + 1);
    chars = (chars + line.length);
    final trimmed = trim(line);
    if ((trimmed.length == 0)) {
      blankLines = (blankLines + 1);
    }
    if ((line.length > longestLine)) {
      longestLine = line.length;
    }
    words = (words + countWords(line));
  }
}

const sampleText =
    (((('The quick brown fox jumps over the lazy dog.\n' +
                'Pack my box with five dozen liquor jugs.\n') +
            'How vexingly quick daft zebras jump!\n') +
        'Sphinx of black quartz, judge my vow.\n') +
    'The five boxing wizards jump quickly.\n');
String trim(String input) {
  String s = input;
  var start = 0;
  var end = s.length;
  while (((start < end) && isSpace(s[start]))) {
    start = (start + 1);
  }
  while (((end > start) && isSpace(s[(end - 1)]))) {
    end = (end - 1);
  }
  return s.substring(start, end);
}

bool isSpace(String input) {
  String ch = input;
  return (((ch == ' ') || (ch == '\t')) || (ch == '\r'));
}

int countWords(String input) {
  String line = input;
  var count = 0;
  var inWord = false;
  var i = 0;
  while ((i < line.length)) {
    final ch = line[i];
    final space = isSpace(ch);
    if ((!space && !inWord)) {
      count = (count + 1);
      inWord = true;
    } else if (space) {
      inWord = false;
    }
    i = (i + 1);
  }
  return count;
}

List<String> splitLines(String input) {
  String text = input;
  final List<String> result = [];
  var start = 0;
  var i = 0;
  while ((i < text.length)) {
    if ((text[i] == '\n')) {
      result.add(text.substring(start, i));
      start = (i + 1);
    }
    i = (i + 1);
  }
  if ((start < text.length)) {
    result.add(text.substring(start, text.length));
  }
  return result;
}

void main() {
  final counts = Counts();
  final lines = splitLines(sampleText);
  for (final line in lines) {
    counts.observe(line);
  }
  final Map<String, int> report = {};
  report['lines'] = counts.lines;
  report['words'] = counts.words;
  report['chars'] = counts.chars;
  report['blank'] = counts.blankLines;
  report['longest'] = counts.longestLine;
  print('wordcount report');
  print('----------------');
  print(('lines:   ' + report['lines'].toString()));
  print(('words:   ' + report['words'].toString()));
  print(('chars:   ' + report['chars'].toString()));
  print(('blank:   ' + report['blank'].toString()));
  print(('longest: ' + report['longest'].toString()));
}
