/// Generates hand-authored conformance fixtures for std base functions that
/// are genuinely unreachable from ANY source-language encoder (issue #64
/// std-coverage gap report on issue #134):
///
///   - `int_to_string` / `double_to_string` — type-specific variants of
///     `to_string`; the syntactic encoders (Dart/TS) have no static type
///     resolution (`parseString`/`ts.SyntaxKind`-only), so `.toString()`
///     always routes to the generic `to_string` and can never disambiguate
///     by receiver type.
///   - `label` (paired with `goto`, already correctly marked
///     not-encoder-emittable) — no mainstream source language the encoders
///     target has a `goto`/label-point statement (see the Dart engine's own
///     `engine: goto/label (#125)` test, which covers this the same way:
///     a hand-built `Program`, not a conformance fixture, until this tool).
///
/// Both ARE fully implemented by the Dart reference engine (and — this is
/// what makes a fixture safe to add — already compiled into the self-hosted
/// TS/C++ engines, since those are generated by encoding
/// `dart/engine/lib/engine.dart` itself, which contains this dispatch code).
/// So unlike a true engine gap, no engine work is required here — only the
/// conformance fixture was missing.
///
/// `length` is DELIBERATELY NOT generated here, unlike the other two: a
/// direct `std.length(...)` call exposed a genuine TS self-host bug — the
/// compiled engine installs a `.length` GETTER on `Object.prototype` (to
/// emulate Dart `Map.length` on every plain-object "map", including the
/// `StdModuleHandler._composedDispatch` dispatch table itself), so indexing
/// that dispatch table with the STRING KEY `"length"` returns the getter's
/// numeric result (the table's own key count) instead of `undefined`, and
/// `StdModuleHandler.call` then tries to invoke that number as a handler
/// ("composed is not a function"). This is a pre-existing, latent
/// self-hosted-engine defect (nothing to do with the encoder), never
/// exercised before because no conformance fixture called `length` until
/// this tool briefly added one. Fixing it means changing the TS engine's
/// Dart-Map-as-plain-object representation strategy — real engine work,
/// out of scope for this (encoder/conformance-surface) lane. DEFERRED:
/// re-add a `388_length_call` fixture once that representation is fixed.
///
/// Regenerate whenever these functions' semantics change:
///   cd dart/encoder && dart run tool/gen_std_gap_fixtures.dart
/// then re-run the Dart engine test suite to refresh expected_output.txt (the
/// tool computes it directly from BallEngine, matching the technique used by
/// `188_std_time_now` / the goto/label engine test).
library;

import 'dart:convert';
import 'dart:io';

import 'package:ball_base/ball_base.dart' show encodeBallFileJson;
import 'package:ball_base/gen/ball/v1/ball.pb.dart';
import 'package:ball_engine/engine.dart';

// ── JSON-shape helpers (mirrors dart/engine/test/engine_test.dart) ──

Map<String, dynamic> literal(Object value) {
  if (value is int) {
    return {
      'literal': {'intValue': '$value'},
    };
  }
  if (value is double) {
    return {
      'literal': {'doubleValue': value},
    };
  }
  if (value is String) {
    return {
      'literal': {'stringValue': value},
    };
  }
  throw ArgumentError('Unsupported literal type: ${value.runtimeType}');
}

Map<String, dynamic> listLit(List<Map<String, dynamic>> elements) => {
  'literal': {
    'listValue': {'elements': elements},
  },
};

Map<String, dynamic> ref(String name) => {
  'reference': {'name': name},
};

Map<String, dynamic> call(
  String function, {
  String module = '',
  Map<String, dynamic>? input,
}) {
  final c = <String, dynamic>{'function': function};
  if (module.isNotEmpty) c['module'] = module;
  if (input != null) c['input'] = input;
  return {'call': c};
}

Map<String, dynamic> stdCall(String function, Map<String, dynamic> input) =>
    call(function, module: 'std', input: input);

Map<String, dynamic> msg(
  List<Map<String, dynamic>> fields, {
  String typeName = '',
}) {
  return {
    'messageCreation': {'typeName': typeName, 'fields': fields},
  };
}

Map<String, dynamic> field(String name, Map<String, dynamic> value) => {
  'name': name,
  'value': value,
};

Map<String, dynamic> printExpr(Map<String, dynamic> value) {
  return stdCall(
    'print',
    msg([field('message', value)], typeName: 'PrintInput'),
  );
}

Map<String, dynamic> stmt(Map<String, dynamic> expr) => {'expression': expr};

Map<String, dynamic> letStmt(
  String name,
  Map<String, dynamic> value, {
  String keyword = 'var',
}) {
  return {
    'let': {
      'name': name,
      'value': value,
      'metadata': {'keyword': keyword},
    },
  };
}

Map<String, dynamic> mainFn(List<Map<String, dynamic>> statements) {
  return {
    'name': 'main',
    'outputType': 'void',
    'body': {
      'block': {'statements': statements},
    },
    'metadata': {'kind': 'function'},
  };
}

const _printInputTypeDef = {
  'name': 'PrintInput',
  'descriptor': {
    'name': 'PrintInput',
    'field': [
      {
        'name': 'message',
        'number': 1,
        'label': 'LABEL_OPTIONAL',
        'type': 'TYPE_STRING',
      },
    ],
  },
};

const _unaryInputTypeDef = {
  'name': 'UnaryInput',
  'descriptor': {
    'name': 'UnaryInput',
    'field': [
      {
        'name': 'value',
        'number': 1,
        'label': 'LABEL_OPTIONAL',
        'type': 'TYPE_STRING',
      },
    ],
  },
};

const _labelInputTypeDef = {
  'name': 'LabelInput',
  'descriptor': {
    'name': 'LabelInput',
    'field': [
      {
        'name': 'name',
        'number': 1,
        'label': 'LABEL_OPTIONAL',
        'type': 'TYPE_STRING',
      },
      {
        'name': 'body',
        'number': 2,
        'label': 'LABEL_OPTIONAL',
        'type': 'TYPE_MESSAGE',
      },
    ],
  },
};

const _gotoInputTypeDef = {
  'name': 'GotoInput',
  'descriptor': {
    'name': 'GotoInput',
    'field': [
      {
        'name': 'label',
        'number': 1,
        'label': 'LABEL_OPTIONAL',
        'type': 'TYPE_STRING',
      },
    ],
  },
};

/// Builds a minimal single-module Program: a `std` module carrying exactly
/// the base functions used (mirrors the minimal footprint the encoder itself
/// would produce, and the hand-authored `188_std_time_now` fixture).
Map<String, dynamic> buildProgramJson({
  required String name,
  required List<Map<String, Object?>> stdFunctions,
  required List<Map<String, Object?>> stdTypeDefs,
  required Map<String, dynamic> mainFunction,
}) {
  return {
    'name': name,
    'version': '1.0.0',
    'modules': [
      {'name': 'std', 'functions': stdFunctions, 'typeDefs': stdTypeDefs},
      {
        'name': 'main',
        'functions': [mainFunction],
      },
    ],
    'entryModule': 'main',
    'entryFunction': 'main',
  };
}

Future<void> writeFixture(
  String id,
  Map<String, dynamic> programJson, {
  bool expectOutput = true,
}) async {
  final program = Program()..mergeFromProto3Json(programJson);
  final jsonMap = encodeBallFileJson(program);
  final jsonStr = const JsonEncoder.withIndent('  ').convert(jsonMap);
  final outDir = '../../tests/conformance';
  File('$outDir/$id.ball.json').writeAsStringSync('$jsonStr\n');

  if (expectOutput) {
    final lines = <String>[];
    await BallEngine(program, stdout: lines.add).run();
    File(
      '$outDir/$id.expected_output.txt',
    ).writeAsStringSync('${lines.join('\n')}\n');
  }
  stderr.writeln(
    'Wrote $id.ball.json${expectOutput ? ' + expected_output.txt' : ''}',
  );
}

Future<void> main() async {
  // `388_length_call` is intentionally NOT generated — see the `length`
  // section of the library doc comment above (a real TS self-host bug, out
  // of scope for this lane; deferred).

  // ── 389_typed_to_string: int_to_string / double_to_string ──
  await writeFixture(
    '389_typed_to_string',
    buildProgramJson(
      name: 'typed_to_string',
      stdFunctions: [
        {'name': 'print', 'isBase': true},
        {'name': 'int_to_string', 'isBase': true},
        {'name': 'double_to_string', 'isBase': true},
      ],
      stdTypeDefs: [_printInputTypeDef, _unaryInputTypeDef],
      mainFunction: mainFn([
        stmt(
          printExpr(
            stdCall('int_to_string', msg([field('value', literal(42))])),
          ),
        ),
        stmt(
          printExpr(
            stdCall('int_to_string', msg([field('value', literal(-7))])),
          ),
        ),
        stmt(
          printExpr(
            stdCall('double_to_string', msg([field('value', literal(3.14))])),
          ),
        ),
        stmt(
          printExpr(
            stdCall('double_to_string', msg([field('value', literal(2.0))])),
          ),
        ),
      ]),
    ),
  );

  // ── 390_goto_label: backward goto re-executing a label body (mirrors
  // dart/engine/test/engine_test.dart's `engine: goto/label (#125)` group,
  // now proven on the TS/C++ self-hosted engines too via the conformance
  // matrix, not just the Dart reference engine). ──
  await writeFixture(
    '390_goto_label',
    buildProgramJson(
      name: 'goto_label',
      stdFunctions: [
        {'name': 'print', 'isBase': true},
        {'name': 'to_string', 'isBase': true},
        {'name': 'assign', 'isBase': true},
        {'name': 'add', 'isBase': true},
        {'name': 'less_than', 'isBase': true},
        {'name': 'if', 'isBase': true},
        {'name': 'label', 'isBase': true},
        {'name': 'goto', 'isBase': true},
      ],
      stdTypeDefs: [
        _printInputTypeDef,
        _unaryInputTypeDef,
        _labelInputTypeDef,
        _gotoInputTypeDef,
      ],
      mainFunction: mainFn([
        letStmt('i', literal(0)),
        stmt(
          stdCall(
            'label',
            msg([
              field('name', literal('loop')),
              field('body', {
                'block': {
                  'statements': [
                    stmt(
                      printExpr(
                        stdCall('to_string', msg([field('value', ref('i'))])),
                      ),
                    ),
                    stmt(
                      stdCall(
                        'assign',
                        msg([
                          field('target', ref('i')),
                          field(
                            'value',
                            stdCall(
                              'add',
                              msg([
                                field('left', ref('i')),
                                field('right', literal(1)),
                              ]),
                            ),
                          ),
                        ]),
                      ),
                    ),
                    stmt(
                      stdCall(
                        'if',
                        msg([
                          field(
                            'condition',
                            stdCall(
                              'less_than',
                              msg([
                                field('left', ref('i')),
                                field('right', literal(3)),
                              ]),
                            ),
                          ),
                          field('then', {
                            'block': {
                              'statements': [
                                stmt(
                                  stdCall(
                                    'goto',
                                    msg([field('label', literal('loop'))]),
                                  ),
                                ),
                              ],
                            },
                          }),
                        ]),
                      ),
                    ),
                  ],
                },
              }),
            ]),
          ),
        ),
      ]),
    ),
  );

  stderr.writeln('Done.');
}
