/// Generates hand-authored conformance fixtures for std base functions that
/// are genuinely unreachable from ANY source-language encoder (issue #64
/// std-coverage gap report on issue #134):
///
///   - `int_to_string` / `double_to_string` — type-specific variants of
///     `to_string`; the syntactic encoders (Dart/TS) have no static type
///     resolution (`parseString`/`ts.SyntaxKind`-only), so `.toString()`
///     always routes to the generic `to_string` and can never disambiguate
///     by receiver type.
///   - `label` (paired with `goto`, already correctly marked
///     not-encoder-emittable) — no mainstream source language the encoders
///     target has a `goto`/label-point statement (see the Dart engine's own
///     `engine: goto/label (#125)` test, which covers this the same way:
///     a hand-built `Program`, not a conformance fixture, until this tool).
///
/// Both ARE fully implemented by the Dart reference engine (and — this is
/// what makes a fixture safe to add — already compiled into the self-hosted
/// TS/C++ engines, since those are generated by encoding
/// `dart/engine/lib/engine.dart` itself, which contains this dispatch code).
/// So unlike a true engine gap, no engine work is required here — only the
/// conformance fixture was missing.
///
/// `length` is DELIBERATELY NOT generated here, unlike the other two: a
/// direct `std.length(...)` call exposed a genuine TS self-host bug — the
/// compiled engine installs a `.length` GETTER on `Object.prototype` (to
/// emulate Dart `Map.length` on every plain-object "map", including the
/// `StdModuleHandler._composedDispatch` dispatch table itself), so indexing
/// that dispatch table with the STRING KEY `"length"` returns the getter's
/// numeric result (the table's own key count) instead of `undefined`, and
/// `StdModuleHandler.call` then tries to invoke that number as a handler
/// ("composed is not a function"). This is a pre-existing, latent
/// self-hosted-engine defect (nothing to do with the encoder), never
/// exercised before because no conformance fixture called `length` until
/// this tool briefly added one. Fixing it means changing the TS engine's
/// Dart-Map-as-plain-object representation strategy — real engine work,
/// out of scope for this (encoder/conformance-surface) lane. DEFERRED:
/// re-add a `388_length_call` fixture once that representation is fixed.
///
/// Regenerate whenever these functions' semantics change:
///   cd dart/encoder && dart run tool/gen_std_gap_fixtures.dart
/// then re-run the Dart engine test suite to refresh expected_output.txt (the
/// tool computes it directly from BallEngine, matching the technique used by
/// `188_std_time_now` / the goto/label engine test).
library;

import 'dart:convert';
import 'dart:io';

import 'package:ball_base/ball_base.dart' show encodeBallFileJson;
import 'package:ball_base/gen/ball/v1/ball.pb.dart';
import 'package:ball_engine/engine.dart';

// ── JSON-shape helpers (mirrors dart/engine/test/engine_test.dart) ──

Map<String, dynamic> literal(Object value) {
  if (value is bool) {
    return {
      'literal': {'boolValue': value},
    };
  }
  if (value is int) {
    return {
      'literal': {'intValue': '$value'},
    };
  }
  if (value is double) {
    return {
      'literal': {'doubleValue': value},
    };
  }
  if (value is String) {
    return {
      'literal': {'stringValue': value},
    };
  }
  throw ArgumentError('Unsupported literal type: ${value.runtimeType}');
}

Map<String, dynamic> listLit(List<Map<String, dynamic>> elements) => {
  'literal': {
    'listValue': {'elements': elements},
  },
};

Map<String, dynamic> ref(String name) => {
  'reference': {'name': name},
};

Map<String, dynamic> call(
  String function, {
  String module = '',
  Map<String, dynamic>? input,
}) {
  final c = <String, dynamic>{'function': function};
  if (module.isNotEmpty) c['module'] = module;
  if (input != null) c['input'] = input;
  return {'call': c};
}

Map<String, dynamic> stdCall(String function, Map<String, dynamic> input) =>
    call(function, module: 'std', input: input);

Map<String, dynamic> msg(
  List<Map<String, dynamic>> fields, {
  String typeName = '',
}) {
  return {
    'messageCreation': {'typeName': typeName, 'fields': fields},
  };
}

Map<String, dynamic> field(String name, Map<String, dynamic> value) => {
  'name': name,
  'value': value,
};

Map<String, dynamic> printExpr(Map<String, dynamic> value) {
  return stdCall(
    'print',
    msg([field('message', value)], typeName: 'PrintInput'),
  );
}

Map<String, dynamic> stmt(Map<String, dynamic> expr) => {'expression': expr};

Map<String, dynamic> toStr(Map<String, dynamic> value) =>
    stdCall('to_string', msg([field('value', value)]));

Map<String, dynamic> setCall(
  String function,
  String setVar,
  Map<String, dynamic> value,
) => collectionsCall(
  function,
  msg([field('set', ref(setVar)), field('value', value)]),
);

Map<String, dynamic> setLen(String setVar) =>
    collectionsCall('set_length', msg([field('set', ref(setVar))]));

/// A fresh `{1, 2}` — every case in `459_set_add_remove_bool` builds its own,
/// so the fixture never depends on a mutation surviving to the next call.
Map<String, dynamic> _setOf12() => stdCall(
  'set_create',
  msg([
    field('elements', listLit([literal(1), literal(2)])),
  ]),
);

Map<String, dynamic> letStmt(
  String name,
  Map<String, dynamic> value, {
  String keyword = 'var',
}) {
  return {
    'let': {
      'name': name,
      'value': value,
      'metadata': {'keyword': keyword},
    },
  };
}

Map<String, dynamic> mainFn(List<Map<String, dynamic>> statements) {
  return {
    'name': 'main',
    'outputType': 'void',
    'body': {
      'block': {'statements': statements},
    },
    'metadata': {'kind': 'function'},
  };
}

const _printInputTypeDef = {
  'name': 'PrintInput',
  'descriptor': {
    'name': 'PrintInput',
    'field': [
      {
        'name': 'message',
        'number': 1,
        'label': 'LABEL_OPTIONAL',
        'type': 'TYPE_STRING',
      },
    ],
  },
};

const _unaryInputTypeDef = {
  'name': 'UnaryInput',
  'descriptor': {
    'name': 'UnaryInput',
    'field': [
      {
        'name': 'value',
        'number': 1,
        'label': 'LABEL_OPTIONAL',
        'type': 'TYPE_STRING',
      },
    ],
  },
};

const _labelInputTypeDef = {
  'name': 'LabelInput',
  'descriptor': {
    'name': 'LabelInput',
    'field': [
      {
        'name': 'name',
        'number': 1,
        'label': 'LABEL_OPTIONAL',
        'type': 'TYPE_STRING',
      },
      {
        'name': 'body',
        'number': 2,
        'label': 'LABEL_OPTIONAL',
        'type': 'TYPE_MESSAGE',
      },
    ],
  },
};

const _gotoInputTypeDef = {
  'name': 'GotoInput',
  'descriptor': {
    'name': 'GotoInput',
    'field': [
      {
        'name': 'label',
        'number': 1,
        'label': 'LABEL_OPTIONAL',
        'type': 'TYPE_STRING',
      },
    ],
  },
};

Map<String, dynamic> collectionsCall(
  String function,
  Map<String, dynamic> input,
) => call(function, module: 'std_collections', input: input);

const _listInputTypeDef = {
  'name': 'ListInput',
  'descriptor': {
    'name': 'ListInput',
    'field': [
      {
        'name': 'list',
        'number': 1,
        'label': 'LABEL_OPTIONAL',
        'type': 'TYPE_MESSAGE',
      },
      {
        'name': 'index',
        'number': 2,
        'label': 'LABEL_OPTIONAL',
        'type': 'TYPE_MESSAGE',
      },
      {
        'name': 'value',
        'number': 3,
        'label': 'LABEL_OPTIONAL',
        'type': 'TYPE_MESSAGE',
      },
    ],
  },
};

const _setInputTypeDef = {
  'name': 'SetInput',
  'descriptor': {
    'name': 'SetInput',
    'field': [
      {
        'name': 'set',
        'number': 1,
        'label': 'LABEL_OPTIONAL',
        'type': 'TYPE_MESSAGE',
      },
      {
        'name': 'value',
        'number': 2,
        'label': 'LABEL_OPTIONAL',
        'type': 'TYPE_MESSAGE',
      },
    ],
  },
};

const _binaryInputTypeDef = {
  'name': 'BinaryInput',
  'descriptor': {
    'name': 'BinaryInput',
    'field': [
      {
        'name': 'left',
        'number': 1,
        'label': 'LABEL_OPTIONAL',
        'type': 'TYPE_INT64',
      },
      {
        'name': 'right',
        'number': 2,
        'label': 'LABEL_OPTIONAL',
        'type': 'TYPE_INT64',
      },
    ],
  },
};

const _listCallbackInputTypeDef = {
  'name': 'ListCallbackInput',
  'descriptor': {
    'name': 'ListCallbackInput',
    'field': [
      {
        'name': 'list',
        'number': 1,
        'label': 'LABEL_OPTIONAL',
        'type': 'TYPE_MESSAGE',
      },
      {
        'name': 'callback',
        'number': 2,
        'label': 'LABEL_OPTIONAL',
        'type': 'TYPE_MESSAGE',
      },
    ],
  },
};

/// A single-parameter lambda `(x) => body` in the shape every encoder emits
/// (`metadata.params` + `expression_body`), so each target compiles it to its
/// own native closure rather than dropping it.
Map<String, dynamic> lambda1(String param, Map<String, dynamic> body) => {
  'lambda': {
    'name': '',
    'body': body,
    'metadata': {
      'kind': 'lambda',
      'expression_body': true,
      'has_return': true,
      'params': [
        {'name': param},
      ],
    },
  },
};

/// `std_collections.list_find(list, callback)` — the callback goes under the
/// name `ListCallbackInput` actually declares (`callback`); every target
/// aliases `callback`/`function`/`value`, so this is the canonical spelling.
Map<String, dynamic> listFind(
  Map<String, dynamic> list,
  Map<String, dynamic> callback,
) => collectionsCall(
  'list_find',
  msg([field('list', list), field('callback', callback)]),
);

/// `std.try(body, catches)` where each catch entry is `(type, variable, body)`.
/// A `type` of `''` means an untyped `catch (e)`.
Map<String, dynamic> tryCatch(
  List<Map<String, dynamic>> bodyStatements,
  List<({String type, String variable, Map<String, dynamic> body})> catches,
) => stdCall(
  'try',
  msg([
    field('body', {
      'block': {'statements': bodyStatements},
    }),
    field(
      'catches',
      listLit([
        for (final c in catches)
          msg([
            if (c.type.isNotEmpty) field('type', literal(c.type)),
            field('variable', literal(c.variable)),
            field('body', {
              'block': {
                'statements': [stmt(c.body)],
              },
            }),
          ]),
      ]),
    ),
  ]),
);

/// Builds a minimal single-module Program: a `std` module carrying exactly
/// the base functions used (mirrors the minimal footprint the encoder itself
/// would produce, and the hand-authored `188_std_time_now` fixture).
Map<String, dynamic> buildProgramJson({
  required String name,
  required List<Map<String, Object?>> stdFunctions,
  required List<Map<String, Object?>> stdTypeDefs,
  required Map<String, dynamic> mainFunction,
  List<Map<String, Object?>> extraModules = const [],
}) {
  return {
    'name': name,
    'version': '1.0.0',
    'modules': [
      {'name': 'std', 'functions': stdFunctions, 'typeDefs': stdTypeDefs},
      ...extraModules,
      {
        'name': 'main',
        'functions': [mainFunction],
      },
    ],
    'entryModule': 'main',
    'entryFunction': 'main',
  };
}

Future<void> writeFixture(
  String id,
  Map<String, dynamic> programJson, {
  bool expectOutput = true,
}) async {
  final program = Program()..mergeFromProto3Json(programJson);
  final jsonMap = encodeBallFileJson(program);
  final jsonStr = const JsonEncoder.withIndent('  ').convert(jsonMap);
  final outDir = '../../tests/conformance';
  File('$outDir/$id.ball.json').writeAsStringSync('$jsonStr\n');

  if (expectOutput) {
    final lines = <String>[];
    await BallEngine(program, stdout: lines.add).run();
    File(
      '$outDir/$id.expected_output.txt',
    ).writeAsStringSync('${lines.join('\n')}\n');
  }
  stderr.writeln(
    'Wrote $id.ball.json${expectOutput ? ' + expected_output.txt' : ''}',
  );
}

Future<void> main() async {
  // `388_length_call` is intentionally NOT generated — see the `length`
  // section of the library doc comment above (a real TS self-host bug, out
  // of scope for this lane; deferred).

  // ── 389_typed_to_string: int_to_string / double_to_string ──
  await writeFixture(
    '389_typed_to_string',
    buildProgramJson(
      name: 'typed_to_string',
      stdFunctions: [
        {'name': 'print', 'isBase': true},
        {'name': 'int_to_string', 'isBase': true},
        {'name': 'double_to_string', 'isBase': true},
      ],
      stdTypeDefs: [_printInputTypeDef, _unaryInputTypeDef],
      mainFunction: mainFn([
        stmt(
          printExpr(
            stdCall('int_to_string', msg([field('value', literal(42))])),
          ),
        ),
        stmt(
          printExpr(
            stdCall('int_to_string', msg([field('value', literal(-7))])),
          ),
        ),
        stmt(
          printExpr(
            stdCall('double_to_string', msg([field('value', literal(3.14))])),
          ),
        ),
        stmt(
          printExpr(
            stdCall('double_to_string', msg([field('value', literal(2.0))])),
          ),
        ),
      ]),
    ),
  );

  // ── 390_goto_label: backward goto re-executing a label body (mirrors
  // dart/engine/test/engine_test.dart's `engine: goto/label (#125)` group,
  // now proven on the TS/C++ self-hosted engines too via the conformance
  // matrix, not just the Dart reference engine). ──
  await writeFixture(
    '390_goto_label',
    buildProgramJson(
      name: 'goto_label',
      stdFunctions: [
        {'name': 'print', 'isBase': true},
        {'name': 'to_string', 'isBase': true},
        {'name': 'assign', 'isBase': true},
        {'name': 'add', 'isBase': true},
        {'name': 'less_than', 'isBase': true},
        {'name': 'if', 'isBase': true},
        {'name': 'label', 'isBase': true},
        {'name': 'goto', 'isBase': true},
      ],
      stdTypeDefs: [
        _printInputTypeDef,
        _unaryInputTypeDef,
        _labelInputTypeDef,
        _gotoInputTypeDef,
      ],
      mainFunction: mainFn([
        letStmt('i', literal(0)),
        stmt(
          stdCall(
            'label',
            msg([
              field('name', literal('loop')),
              field('body', {
                'block': {
                  'statements': [
                    stmt(
                      printExpr(
                        stdCall('to_string', msg([field('value', ref('i'))])),
                      ),
                    ),
                    stmt(
                      stdCall(
                        'assign',
                        msg([
                          field('target', ref('i')),
                          field(
                            'value',
                            stdCall(
                              'add',
                              msg([
                                field('left', ref('i')),
                                field('right', literal(1)),
                              ]),
                            ),
                          ),
                        ]),
                      ),
                    ),
                    stmt(
                      stdCall(
                        'if',
                        msg([
                          field(
                            'condition',
                            stdCall(
                              'less_than',
                              msg([
                                field('left', ref('i')),
                                field('right', literal(3)),
                              ]),
                            ),
                          ),
                          field('then', {
                            'block': {
                              'statements': [
                                stmt(
                                  stdCall(
                                    'goto',
                                    msg([field('label', literal('loop'))]),
                                  ),
                                ),
                              ],
                            },
                          }),
                        ]),
                      ),
                    ),
                  ],
                },
              }),
            ]),
          ),
        ),
      ]),
    ),
  );

  // ── 459_set_add_remove_bool: the ONE bool contract for
  // `std_collections.set_add` / `set_remove` (issue #545). Both mutate the
  // receiver set IN PLACE and return `bool` — `true` only when the element was
  // newly inserted / was actually present — exactly like Dart's own
  // `Set.add`/`Set.remove`. Before #545 the Dart engine returned the NEW SET
  // from both (and never mutated the receiver at all), the Dart and C++
  // compilers returned the set, and the TS engine returned an UNCONDITIONAL
  // `true` from `set_add` — several different answers for the same call, and
  // the Dart engine and Dart compiler disagreed with each OTHER on `set_remove`
  // alone. Every print here puts the RESULT in a value position; that is the
  // whole point, since nothing in the corpus ever did.
  //
  // Not generatable from Dart source: the Dart encoder deliberately declines to
  // route a `Set` receiver's `.add()`/`.remove()` to these base functions (see
  // the receiver-TYPE gate in `dart/encoder/lib/encoder.dart`, issue #488), so
  // no portable Dart program encodes to a `set_add` call. Hand-built here, and
  // listed in tests/conformance/CARVEOUTS.md.
  //
  // EACH CASE USES A FRESH SET, deliberately — it does not chain calls against
  // one `let`-bound set and then observe the mutation. That stronger fixture
  // was written first and it FAILED on the C# and Rust self-hosted engines for
  // a reason that has nothing to do with #545: their `_ballSetItems` hands back
  // a COPY of a set's backing list, so every in-place set mutation the engine
  // performs is silently lost (`list_clear` on a set and the `Set.add`/`remove`
  // method dispatch are already affected on `main`). That is issue #557; when
  // it is fixed, chain these calls against one set and assert the interleaved
  // `set_length`/`set_contains`, which is exactly its regression test. Until
  // then the four return-value branches below are pinned on every target, and
  // the in-place mutation is pinned per runtime instead (the C#/Rust/Go/Python
  // runtime unit tests) and on the Dart reference engine.
  await writeFixture(
    '459_set_add_remove_bool',
    buildProgramJson(
      name: 'set_add_remove_bool',
      // `set_create` is declared and CALLED on `std`, not `std_collections`:
      // that is what every encoder emits today (see `118_set_operations`), and
      // the Dart compiler's `set_create` case lives on its std switch, so a
      // `std_collections.set_create` call compiles to an `/* unsupported */`
      // comment. Mirror the real encoder shape rather than inventing one.
      stdFunctions: [
        {'name': 'print', 'isBase': true},
        {'name': 'to_string', 'isBase': true},
        {'name': 'set_create', 'isBase': true},
      ],
      stdTypeDefs: [_printInputTypeDef, _unaryInputTypeDef, _listInputTypeDef],
      extraModules: [
        {
          'name': 'std_collections',
          'functions': [
            // Declared name+isBase only, exactly like every other fixture's
            // base-function list — the `outputType: 'bool'` DECLARATION lives
            // in dart/shared/lib/std_collections.dart (and so in std.json), and
            // is gated by dart/engine/test/std_output_type_contract_test.dart.
            {'name': 'set_add', 'isBase': true},
            {'name': 'set_remove', 'isBase': true},
            {'name': 'set_contains', 'isBase': true},
            {'name': 'set_length', 'isBase': true},
          ],
          'typeDefs': [_setInputTypeDef],
        },
      ],
      mainFunction: mainFn([
        // set_add — true ONLY on a fresh insert.
        letStmt('a', _setOf12()),
        stmt(printExpr(toStr(setCall('set_add', 'a', literal(3))))),
        letStmt('b', _setOf12()),
        stmt(printExpr(toStr(setCall('set_add', 'b', literal(2))))),
        // set_remove — true ONLY when the element was actually present.
        letStmt('c', _setOf12()),
        stmt(printExpr(toStr(setCall('set_remove', 'c', literal(2))))),
        letStmt('d', _setOf12()),
        stmt(printExpr(toStr(setCall('set_remove', 'd', literal(9))))),
        // Read-only siblings, so the fixture also covers the two set functions
        // it needs in order to be readable as a set test at all.
        letStmt('e', _setOf12()),
        stmt(printExpr(toStr(setLen('e')))),
        stmt(printExpr(toStr(setCall('set_contains', 'e', literal(2))))),
      ]),
    ),
  );

  // ── 462_set_mutation_in_place: `std_collections.set_add`/`set_remove`
  // MUTATE the receiver, and the mutation is observable through the SAME
  // `let`-bound set afterwards (issue #557). This is the chained form
  // `459_set_add_remove_bool` deliberately could NOT use: there every case
  // builds a FRESH `{1, 2}`, so the fixture pins only the returned bool and
  // never observes the in-place write. Here one set `a` is created once, added
  // to, removed from, and then READ BACK — printed whole, measured, and probed
  // with `set_contains` for both the added and the removed element.
  //
  // Before #557's fix the C# and Rust self-hosted engines printed `{1, 2}` for
  // the whole set while every bool AND `set_length` still looked right: their
  // compiled `_ballSetItems` handed back a COPY of the backing list (its
  // `v is Map` guard is false for a tagged set on those targets, so the
  // native-`Set` `.toList()` branch ran instead), so each mutation applied to a
  // throwaway list. Only reading the SAME set back after a mutation can see
  // that — which is exactly why the fresh-set-per-case form could not.
  //
  // Hand-built for the same reason 459 is: the Dart encoder's receiver-TYPE
  // gate (issue #488) declines to route a `Set` receiver's `.add()`/`.remove()`
  // to these base functions, so no portable Dart source encodes to a `set_add`
  // call. Listed in tests/conformance/CARVEOUTS.md.
  await writeFixture(
    '462_set_mutation_in_place',
    buildProgramJson(
      name: 'set_mutation_in_place',
      // Same module shape as 459: `set_create` is declared and CALLED on `std`
      // (what every encoder emits today), the set ops on `std_collections`.
      stdFunctions: [
        {'name': 'print', 'isBase': true},
        {'name': 'to_string', 'isBase': true},
        {'name': 'set_create', 'isBase': true},
      ],
      stdTypeDefs: [_printInputTypeDef, _unaryInputTypeDef, _listInputTypeDef],
      extraModules: [
        {
          'name': 'std_collections',
          'functions': [
            {'name': 'set_add', 'isBase': true},
            {'name': 'set_remove', 'isBase': true},
            {'name': 'set_contains', 'isBase': true},
            {'name': 'set_length', 'isBase': true},
          ],
          'typeDefs': [_setInputTypeDef],
        },
      ],
      mainFunction: mainFn([
        // ONE set, mutated in place and then read back.
        letStmt('a', _setOf12()),
        stmt(printExpr(toStr(setCall('set_add', 'a', literal(3))))),
        stmt(printExpr(toStr(setCall('set_remove', 'a', literal(2))))),
        // The set itself — the assertion the copy-instead-of-alias bug fails.
        stmt(printExpr(toStr(ref('a')))),
        stmt(printExpr(toStr(setLen('a')))),
        // Probe both mutations independently of ordering and of length.
        stmt(printExpr(toStr(setCall('set_contains', 'a', literal(3))))),
        stmt(printExpr(toStr(setCall('set_contains', 'a', literal(2))))),
      ]),
    ),
  );

  // -- 463_list_find_no_match: the ONE no-match contract for
  // `std_collections.list_find` (issue #597). When no element satisfies the
  // predicate the call THROWS a catchable `StateError` -- it never yields a
  // null/undefined/empty placeholder. That is what the declaration itself
  // promises (`dart/shared/lib/std_collections.dart`: "Find first:
  // list.firstWhere(callback)", and Dart's `firstWhere` without `orElse`
  // throws by definition) and what the Dart reference engine
  // (`dart/engine/lib/engine_std.dart`) has always done.
  //
  // Before #597's fix four targets disagreed with Dart while the corpus stayed
  // green, because NOTHING exercised the no-match branch: the TS engine's
  // hand-written `engine_setup.ts` override shadowed the compiled engine's own
  // (correct) handler and returned `null`; the TS compiler emitted a bare
  // `Array.prototype.find`, which yields `undefined`; the C++ compiler emitted
  // `return BallDyn();`; and the C# compiler had no `list_find` case at all, so
  // it emitted an `UnsupportedBaseCall` that threw a native
  // `BallRuntimeException` at RUN time -- not even caught by the program's own
  // `try`. The #545 declared-outputType gate could not see any of it: it checks
  // the return TYPE on a HIT, never the no-match path.
  //
  // Three cases, deliberately:
  //   1. a HIT still returns the element (the fix must not turn every call into
  //      a throw);
  //   2. a MISS on a non-empty list is caught by `on StateError`;
  //   3. a MISS on an EMPTY list throws the same way (the empty case reaches a
  //      different branch in several targets than "scanned everything, found
  //      nothing").
  //
  // Every `try` here has exactly ONE catch clause, deliberately. That the throw
  // is a genuinely TYPED exception -- reachable by `on StateError` and not only
  // by an untyped catch-all, which is what Rust's bare `panic!` gave before
  // #597 -- is pinned per runtime instead (rust/shared's
  // `list_find_no_match_throws_a_typed_state_error` asserts the
  // `{'__type__': 'StateError', 'message': …}` payload directly; the C# and TS
  // compiler tests assert the typed catch). A multi-clause `try` whose FIRST
  // arm names a non-matching type cannot go in a portable fixture: the Go, C#
  // and Rust COMPILERS all dispatch only the first catch clause with no
  // type matching (a pre-existing, separately documented gap -- see
  // `csharp/compiler/src/BaseCall.cs`'s `CompileTryStatement` doc comment), so
  // such a fixture would fail those compile legs for a reason that has nothing
  // to do with `list_find`.
  //
  // Not generatable from Dart source: the Dart encoder routes NO Dart syntax to
  // `list_find` (zero hits in `dart/encoder/lib/`), so `generate_conformance`
  // cannot reach it from any `tests/conformance/src/*.dart` -- which is also why
  // `check_encoder_completeness.dart` never flagged the gap. Hand-built here
  // and listed in tests/conformance/CARVEOUTS.md.
  await writeFixture(
    '463_list_find_no_match',
    buildProgramJson(
      name: 'list_find_no_match',
      stdFunctions: [
        {'name': 'print', 'isBase': true},
        {'name': 'to_string', 'isBase': true},
        {'name': 'greater_than', 'isBase': true},
        {'name': 'try', 'isBase': true},
      ],
      stdTypeDefs: [
        _printInputTypeDef,
        _unaryInputTypeDef,
        _binaryInputTypeDef,
      ],
      extraModules: [
        {
          'name': 'std_collections',
          'functions': [
            {'name': 'list_find', 'isBase': true},
          ],
          'typeDefs': [_listCallbackInputTypeDef],
        },
      ],
      mainFunction: mainFn([
        letStmt(
          'nums',
          listLit([literal(1), literal(2), literal(3)]),
          keyword: 'final',
        ),
        // 1. A HIT returns the matching element.
        stmt(
          tryCatch(
            [
              stmt(
                printExpr(
                  toStr(
                    listFind(
                      ref('nums'),
                      lambda1(
                        'x',
                        stdCall(
                          'greater_than',
                          msg([
                            field('left', ref('x')),
                            field('right', literal(2)),
                          ]),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ],
            [
              (
                type: 'StateError',
                variable: 'e',
                body: printExpr(literal('wrong: StateError on a hit')),
              ),
            ],
          ),
        ),
        // 2. A MISS on a non-empty list throws a catchable StateError.
        stmt(
          tryCatch(
            [
              stmt(
                printExpr(
                  toStr(
                    listFind(
                      ref('nums'),
                      lambda1(
                        'x',
                        stdCall(
                          'greater_than',
                          msg([
                            field('left', ref('x')),
                            field('right', literal(100)),
                          ]),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ],
            [
              (
                type: 'StateError',
                variable: 'e',
                body: printExpr(literal('caught StateError: no match')),
              ),
            ],
          ),
        ),
        // 3. A MISS on an EMPTY list throws the same typed StateError.
        stmt(
          tryCatch(
            [
              stmt(
                printExpr(
                  toStr(listFind(listLit([]), lambda1('x', literal(true)))),
                ),
              ),
            ],
            [
              (
                type: 'StateError',
                variable: 'e',
                body: printExpr(literal('caught StateError: empty list')),
              ),
            ],
          ),
        ),
        stmt(printExpr(literal('done'))),
      ]),
    ),
  );

  // -- 464_state_error_message: the ONE observable form of a CAUGHT StateError
  // (issue #616). `463_list_find_no_match` proved the throw is typed, but both
  // of its catch bodies print a HARDCODED literal, so nothing anywhere pinned
  // what the caught value itself reads as -- and every target answered
  // differently. Measured on `origin/main` before the fix, same program:
  //
  //   Dart reference engine   Bad state: No element   <- canonical
  //   TS self-hosted engine   {message: No element}
  //   Go self-hosted engine   main:StateError
  //
  // The canonical answer is the Dart reference engine's, and it is also real
  // Dart's: `StateError('No element').toString()` is `Bad state: No element`
  // (verified against the SDK, not asserted in prose). `_evalLazyTry` binds
  // `e is BallException ? e.value : e.toString()`, and the reference engine
  // raised a HOST `StateError`, so the catch variable collapsed to that string.
  // Every self-hosted engine compiles the same source line into a BALL-level
  // construction of an unknown `StateError` class, so its catch variable bound
  // a target-shaped object instead and each target's `to_string` rendered it
  // its own way. The fix makes the engine throw a `BallException` whose value
  // IS the canonical string, so the SAME portable value travels every target.
  //
  // Two sites, deliberately: `list_find` (the #604/#616 site, typed everywhere
  // already) and `list_first` on an EMPTY list (which reached the runtimes'
  // untyped `panic!`/`Thrown{string}`/`BallRuntimeException` paths, so a typed
  // `on StateError catch` could not even see it on Rust/Go/C#/Python).
  //
  // One catch clause per `try`, for the same reason `463` has one: the Go, C#
  // and Rust COMPILERS dispatch only the first clause with no type matching.
  //
  // Not generatable from Dart source: the Dart encoder routes no Dart syntax to
  // `list_find` at all (see `463`'s note), so `generate_conformance` cannot
  // reach it from a `tests/conformance/src/*.dart`. Hand-built here and listed
  // in tests/conformance/CARVEOUTS.md.
  await writeFixture(
    '464_state_error_message',
    buildProgramJson(
      name: 'state_error_message',
      stdFunctions: [
        {'name': 'print', 'isBase': true},
        {'name': 'to_string', 'isBase': true},
        {'name': 'greater_than', 'isBase': true},
        {'name': 'try', 'isBase': true},
      ],
      stdTypeDefs: [
        _printInputTypeDef,
        _unaryInputTypeDef,
        _binaryInputTypeDef,
      ],
      extraModules: [
        {
          'name': 'std_collections',
          'functions': [
            {'name': 'list_find', 'isBase': true},
            {'name': 'list_first', 'isBase': true},
          ],
          'typeDefs': [_listCallbackInputTypeDef, _listInputTypeDef],
        },
      ],
      mainFunction: mainFn([
        // 1. A MISS on a non-empty list: print the CAUGHT VALUE, never a
        //    hardcoded string. This is the whole point of the fixture.
        stmt(
          tryCatch(
            [
              stmt(
                printExpr(
                  toStr(
                    listFind(
                      listLit([literal(1), literal(2), literal(3)]),
                      lambda1(
                        'x',
                        stdCall(
                          'greater_than',
                          msg([
                            field('left', ref('x')),
                            field('right', literal(100)),
                          ]),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ],
            [
              (
                type: 'StateError',
                variable: 'e',
                body: printExpr(toStr(ref('e'))),
              ),
            ],
          ),
        ),
        // 2. `list_first` on an EMPTY list throws the same typed StateError
        //    with the same observable form.
        stmt(
          tryCatch(
            [
              stmt(
                printExpr(
                  toStr(
                    collectionsCall(
                      'list_first',
                      msg([field('list', listLit([]))]),
                    ),
                  ),
                ),
              ),
            ],
            [
              (
                type: 'StateError',
                variable: 'e',
                body: printExpr(toStr(ref('e'))),
              ),
            ],
          ),
        ),
        stmt(printExpr(literal('done'))),
      ]),
    ),
  );

  stderr.writeln('Done.');
}
