/// Idempotent rewrap tool: wraps `.ball.json` files into the self-describing
/// `google.protobuf.Any` JSON envelope so readers never guess Program vs Module.
///
/// For each file:
///   - If a top-level `@type` is already present, the file is left untouched
///     (idempotent).
///   - Otherwise the top-level message is classified as a Program (it has a
///     top-level `modules` key) or a Module (no `modules`; carries
///     `functions` / `typeDefs` / `moduleImports` / `name`), the matching
///     `@type` is prepended, and the file is rewritten with 2-space indent and
///     a trailing newline.
///
/// Usage:
///   dart run tool/wrap_ball_files.dart <file-or-dir> [<file-or-dir> ...]
///
/// Directories are scanned recursively for `*.ball.json`. With no arguments the
/// tool wraps the canonical set: tests/conformance, tests/fixtures/dart, the
/// examples tree, and the committed std/ball_proto/ball_protobuf artifacts.
///
/// `.bin` files are intentionally left alone — they are regenerated by the
/// writer tools (gen_std, gen_ball_proto, gen_ball_protobuf, roundtrip_engine).
library;

import 'dart:convert';
import 'dart:io';

import 'package:ball_base/ball_base.dart' show programTypeUrl, moduleTypeUrl;

void main(List<String> args) {
  final repoRoot = _findRepoRoot();

  final targets = <String>[];
  if (args.isEmpty) {
    targets.addAll([
      '$repoRoot/tests/conformance',
      '$repoRoot/tests/fixtures/dart',
      '$repoRoot/examples',
      '$repoRoot/dart/shared/std.json',
      '$repoRoot/dart/shared/ball_proto.json',
      '$repoRoot/dart/shared/ball_protobuf.json',
    ]);
  } else {
    targets.addAll(args);
  }

  final files = <File>[];
  for (final target in targets) {
    final entity = FileSystemEntity.typeSync(target);
    if (entity == FileSystemEntityType.directory) {
      files.addAll(_findBallJsonFiles(Directory(target)));
    } else if (entity == FileSystemEntityType.file) {
      files.add(File(target));
    } else {
      stderr.writeln('Skipping (not found): $target');
    }
  }
  files.sort((a, b) => a.path.compareTo(b.path));

  var wrapped = 0;
  var skipped = 0;
  var programs = 0;
  var modules = 0;
  final failures = <String>[];

  for (final file in files) {
    try {
      final decoded = jsonDecode(file.readAsStringSync());
      if (decoded is! Map<String, dynamic>) {
        failures.add('${file.path}: top-level JSON is not an object');
        continue;
      }
      if (decoded.containsKey('@type')) {
        skipped++;
        continue;
      }
      final isProgram = decoded.containsKey('modules');
      final typeUrl = isProgram ? programTypeUrl : moduleTypeUrl;
      if (isProgram) {
        programs++;
      } else {
        modules++;
      }
      final wrappedMap = <String, dynamic>{'@type': typeUrl, ...decoded};
      final out = const JsonEncoder.withIndent('  ').convert(wrappedMap);
      file.writeAsStringSync('$out\n');
      wrapped++;
    } catch (e) {
      failures.add('${file.path}: $e');
    }
  }

  stdout.writeln('wrap_ball_files: ${files.length} candidate(s)');
  stdout.writeln(
    '  wrapped: $wrapped (programs: $programs, modules: $modules)',
  );
  stdout.writeln('  skipped (already wrapped): $skipped');
  if (failures.isNotEmpty) {
    stderr.writeln('  failures: ${failures.length}');
    for (final f in failures) {
      stderr.writeln('    - $f');
    }
    exit(1);
  }
}

List<File> _findBallJsonFiles(Directory dir) {
  if (!dir.existsSync()) return const [];
  return dir
      .listSync(recursive: true)
      .whereType<File>()
      .where((f) => f.path.endsWith('.ball.json'))
      .toList();
}

String _findRepoRoot() {
  var dir = Directory.current;
  while (true) {
    if (File('${dir.path}/proto/ball/v1/ball.proto').existsSync()) {
      return dir.path.replaceAll('\\', '/');
    }
    final parent = dir.parent;
    if (parent.path == dir.path) {
      throw StateError(
        'Could not locate repo root (no proto/ball/v1/ball.proto found '
        'walking up from ${Directory.current.path})',
      );
    }
    dir = parent;
  }
}
