using System.Text.Json;
using Ball.Compiler;
using Ball.V1;
using Google.Protobuf;
using Google.Protobuf.WellKnownTypes;

namespace Ball.Engine.Regen;

/// <summary>
/// Regenerates <c>csharp/engine/src/CompiledEngine.cs</c> from the self-hosted
/// Ball engine (<c>dart/self_host/engine.ball.pb</c>) — the self-host route
/// (issue #383, playbook Phase 4 Option B), mirroring
/// <c>rust/engine/tool/src/main.rs</c> and the TypeScript regeneration command.
///
/// <para>Pipeline:</para>
/// <list type="number">
/// <item>Read <c>dart/self_host/engine.ball.pb</c> — a self-describing
/// <c>google.protobuf.Any</c> envelope carrying the <c>ball.v1.Program</c>
/// (binary, since the 21&#160;MB JSON exceeds protobuf's 100-level nesting
/// default). Falls back to <c>engine.ball.json</c> (stripping the <c>@type</c>
/// envelope) when the <c>.pb</c> is absent.</item>
/// <item>Unpack the <c>Any</c> to a typed <see cref="Program"/>.</item>
/// <item>Compile via <see cref="CSharpCompiler.Compile(Program)"/> (library
/// shape — the engine has no runnable top-level <c>main</c>, so no
/// <c>Main</c> is emitted).</item>
/// <item>Write <c>CompiledEngine.cs</c> with a NEVER-edit header.</item>
/// </list>
///
/// <para><c>CompiledEngine.cs</c> is a <b>generated, NEVER-edit</b> file — fix
/// the compiler (<c>csharp/compiler/</c>) or the wrapper and rerun this, never
/// hand-patch the output. Usage: <c>dotnet run --project
/// csharp/engine/tool/Ball.Engine.Regen.csproj</c>.</para>
/// </summary>
internal static class RegenTool
{
    private const string Header =
        "// <auto-generated> by `dotnet run --project csharp/engine/tool` from dart/self_host/engine.ball.pb.\n" +
        "//\n" +
        "// DO NOT EDIT BY HAND. This is the self-hosted Ball engine, compiled from\n" +
        "// the reference engine's own Ball encoding through the Ball -> C# compiler.\n" +
        "// To change it, fix csharp/compiler/ (or the dart/self_host/ source) and\n" +
        "// rerun the regenerator — never hand-patch this file. See csharp/AGENTS.md.\n" +
        "#nullable disable\n" +
        "#pragma warning disable\n\n";

    private static int Main()
    {
        var root = FindRepoRoot();
        var pbPath = Path.Combine(root, "dart", "self_host", "engine.ball.pb");
        var jsonPath = Path.Combine(root, "dart", "self_host", "engine.ball.json");
        var outPath = Path.Combine(root, "csharp", "engine", "src", "CompiledEngine.cs");

        Program program;
        if (File.Exists(pbPath))
        {
            Console.Error.WriteLine($"[regen] loading {pbPath}");
            program = LoadBinary(pbPath);
        }
        else if (File.Exists(jsonPath))
        {
            Console.Error.WriteLine($"[regen] loading {jsonPath}");
            program = LoadJson(jsonPath);
        }
        else
        {
            Console.Error.WriteLine(
                $"[regen] neither {pbPath} nor {jsonPath} exists.\n" +
                "        Regenerate the self-host source first:\n" +
                "          dart run dart/compiler/tool/gen_engine_json.dart");
            return 1;
        }

        Console.Error.WriteLine(
            $"[regen] compiling program \"{program.Name}\" v{program.Version} " +
            $"({program.Modules.Count} modules)");

        var csharp = CSharpCompiler.Compile(program);

        Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);
        File.WriteAllText(outPath, Header + csharp);
        Console.Error.WriteLine($"[regen] wrote {outPath} ({Header.Length + csharp.Length} bytes)");
        return 0;
    }

    /// <summary>
    /// Load an <c>engine.ball.pb</c> — a binary <c>google.protobuf.Any</c>
    /// envelope wrapping the <c>ball.v1.Program</c> — into a typed
    /// <see cref="Program"/>.
    /// </summary>
    private static Program LoadBinary(string path)
    {
        var bytes = File.ReadAllBytes(path);
        var any = Any.Parser.ParseFrom(bytes);
        return any.Unpack<Program>();
    }

    /// <summary>
    /// Load an <c>engine.ball.json</c> — a proto3-JSON <c>google.protobuf.Any</c>
    /// envelope with an explicit <c>@type</c> key — into a typed
    /// <see cref="Program"/>. The <c>@type</c> key is stripped before parsing
    /// (mirrors the Rust/TS loaders).
    /// </summary>
    private static Program LoadJson(string path)
    {
        var json = File.ReadAllText(path);
        using var doc = JsonDocument.Parse(json);
        // Re-serialize without the cosmetic @type Any-envelope key.
        using var stream = new MemoryStream();
        using (var writer = new Utf8JsonWriter(stream))
        {
            writer.WriteStartObject();
            foreach (var property in doc.RootElement.EnumerateObject())
            {
                if (property.NameEquals("@type"))
                {
                    continue;
                }

                property.WriteTo(writer);
            }

            writer.WriteEndObject();
        }

        var body = System.Text.Encoding.UTF8.GetString(stream.ToArray());
        var parser = new JsonParser(JsonParser.Settings.Default.WithIgnoreUnknownFields(true));
        return parser.Parse<Program>(body);
    }

    private static string FindRepoRoot()
    {
        var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
        while (dir is not null)
        {
            if (File.Exists(Path.Combine(dir.FullName, "proto", "ball", "v1", "ball.proto")))
            {
                return dir.FullName;
            }

            dir = dir.Parent;
        }

        throw new InvalidOperationException("not inside the ball repo (no proto/ball/v1/ball.proto found)");
    }
}
