#!/usr/bin/env bash
# Static consistency guard for the pub.dev (Dart) release lane (#551).
#
# WHY THIS EXISTS: the pub.dev lane was the one release channel in this repo
# built around a *human* checkpoint. `release-prepare.yml` ran Melos on every
# push to main and refreshed a single rolling `chore/release` PR; a maintainer
# squash-merged it; only then did `release-tag.yml` tag and dispatch
# `release-publish.yml`. Every automated part of that chain was wired correctly
# and stayed green — and the lane still shipped nothing for two months, because
# the rolling PR (#272, opened 2026-07-07) was never merged. pub.dev sat at
# `ball_base 0.3.0+3` (published 2026-07-03) while main shipped v1.61.1 →
# v1.67.1 through the *other* pipeline. No gate noticed: the repo's release
# guards all assert REACHABILITY (`check_release_dispatch_wiring.sh`), and this
# trigger chain was perfectly reachable. What was missing is a gate on the
# lane's SHAPE — that publishing a Dart package requires no human action at all.
#
# So this guard pins the post-#551 contract:
#   1. every publishable Dart package has exactly one semantic-release config,
#      and every Dart config names a package that still exists (bidirectional);
#   2. each config is internally consistent (tagFormat / path filter /
#      version-stamp target / publish dispatch all name the SAME package);
#   3. exactly one workflow drives those configs, and it is reachable
#      automatically from a release — no human merge in the path;
#   4. the retired Melos versioning lane cannot come back;
#   5. `ball_cli`'s generated `version.g.dart` is regenerated by the same
#      prepare step that bumps its pubspec (ci.yml's `--check` guard fails
#      otherwise on the next push);
#   6. `release-publish.yml` verifies its own publish against the live index;
#   7. the loop keeps re-pinned siblings in LOCKSTEP (#566) — it snapshots
#      pub.dev, asks the planner per package, and every config records what
#      semantic-release decided so the next package can see it.
#
# Deliberately textual/grep-based against the DOCUMENTED pattern, in the same
# style as `check_release_dispatch_wiring.sh` and
# `tools/check_conformance_doc_counts.sh`: it asserts the handful of things
# that make the lane fire without a human, not the incidental shape of the YAML
# and JSON around them, so a legitimate refactor does not false-red.
#
# Usage: bash tools/release/check_pubdev_release_wiring.sh

set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
WORKFLOWS="$ROOT/.github/workflows"
CONFIGS="$ROOT/.github/release"
RELEASE="$WORKFLOWS/release.yml"
DRIVER="$WORKFLOWS/pubdev-release.yml"
PUBLISH="$WORKFLOWS/release-publish.yml"
CI="$WORKFLOWS/ci.yml"

pass=0
fail=0

ok() {
  pass=$((pass + 1))
  echo "PASS  $1"
}

no() {
  fail=$((fail + 1))
  echo "FAIL  $1"
  shift
  local line
  for line in "$@"; do printf '  %s\n' "$line"; done
}

[ -f "$RELEASE" ] || {
  echo "::error::missing $RELEASE"
  exit 1
}

# ── Discover the publishable Dart packages from the repo, never a hardcoded
#    list: a 10th package added under dart/ must be picked up automatically,
#    which is the whole point of the completeness leg below. `publish_to: none`
#    marks a package private (ball_self_host_tests).
PKG_NAMES=""
declare -A PKG_DIR=()
for pubspec in "$ROOT"/dart/*/pubspec.yaml; do
  [ -f "$pubspec" ] || continue
  name="$(grep -m1 -E '^name:[[:space:]]*[A-Za-z0-9_]+' "$pubspec" | awk '{print $2}')"
  [ -n "$name" ] || continue
  if grep -qE '^publish_to:[[:space:]]*none' "$pubspec"; then continue; fi
  dir="dart/$(basename "$(dirname "$pubspec")")"
  PKG_NAMES="$PKG_NAMES $name"
  PKG_DIR["$name"]="$dir"
done

# The discovery itself must have found something — an empty sweep would make
# every per-package leg below vacuously green.
pkg_count="$(echo $PKG_NAMES | wc -w | tr -d ' ')"
if [ "$pkg_count" -ge 1 ]; then
  ok "discovered $pkg_count publishable Dart packages under dart/*/pubspec.yaml"
else
  no "discovered at least one publishable Dart package under dart/*/pubspec.yaml" \
    "the discovery sweep found nothing — every check below would be vacuous"
  echo "Results: $pass passed, $fail failed, $((pass + fail)) total"
  exit 1
fi

# ── 1. Config completeness, package → config. ─────────────────────────────
for name in $PKG_NAMES; do
  cfg="$CONFIGS/$name.releaserc.json"
  if [ -f "$cfg" ]; then
    ok "$name has .github/release/$name.releaserc.json"
  else
    no "$name has .github/release/$name.releaserc.json" \
      "a publishable Dart package with no semantic-release config never publishes," \
      "and nothing else in the repo would say so — exactly how the pub.dev lane went quiet (#551)"
  fi
done

# ── 2. Config completeness, config → package (the other direction). ───────
for cfg in "$CONFIGS"/*.releaserc.json; do
  [ -f "$cfg" ] || continue
  grep -qF 'release-publish.yml' "$cfg" || continue # not a pub.dev config
  cfg_name="$(basename "$cfg" .releaserc.json)"
  if [ -n "${PKG_DIR[$cfg_name]:-}" ]; then
    ok "$cfg_name.releaserc.json names a package that still exists and is publishable"
  else
    no "$cfg_name.releaserc.json names a package that still exists and is publishable" \
      "the config dispatches release-publish.yml for '$cfg_name', but no dart/*/pubspec.yaml declares" \
      "that name as publishable — a renamed or privatised package leaves a config that can only fail"
  fi
done

# ── 3. Per-config internal consistency. ───────────────────────────────────
# Every field that names the package must name the SAME package: a copy-pasted
# config whose tagFormat says ball_engine while its prepareCmd stamps
# dart/compiler/pubspec.yaml publishes the wrong tree under the right tag, and
# both halves look plausible in review.
for name in $PKG_NAMES; do
  cfg="$CONFIGS/$name.releaserc.json"
  [ -f "$cfg" ] || continue
  dir="${PKG_DIR[$name]}"
  probs=()
  grep -qF "\"tagFormat\": \"$name-v\${version}\"" "$cfg" ||
    probs+=("expected \"tagFormat\": \"$name-v\${version}\" (pub.dev's configured tag pattern is <pkg>-v{{version}})")
  grep -qF "\"paths\": [\"$dir\"]" "$cfg" ||
    probs+=("expected the only-package-commits path filter to be \"paths\": [\"$dir\"]")
  grep -qF "--file=$dir/pubspec.yaml" "$cfg" ||
    probs+=("expected prepareCmd to stamp --file=$dir/pubspec.yaml")
  grep -qF "gh workflow run release-publish.yml --ref $name-v\${nextRelease.version}" "$cfg" ||
    probs+=("expected publishCmd: gh workflow run release-publish.yml --ref $name-v\${nextRelease.version}")
  grep -qF "\"$dir/pubspec.yaml\"" "$cfg" ||
    probs+=("expected $dir/pubspec.yaml in the @semantic-release/git assets")
  # #566: the loop can only keep the NEXT package in step if this one records
  # what semantic-release actually decided. verifyRelease is one of the four
  # steps semantic-release also runs under --dry-run, which is what makes the
  # dry-run rehearsal a faithful plan rather than a guess.
  grep -qF "lockstep_plan.mjs --record --package=$name" "$cfg" ||
    probs+=("expected a verifyReleaseCmd running: node tools/release/lockstep_plan.mjs --record --package=$name ..."       "so the next package in the loop can see what semantic-release decided for this one (#566)")
  if [ "${#probs[@]}" -eq 0 ]; then
    ok "$name.releaserc.json is internally consistent (tag, paths, stamp, dispatch, assets)"
  else
    no "$name.releaserc.json is internally consistent (tag, paths, stamp, dispatch, assets)" "${probs[@]}"
  fi
done

# ── 4. A driver workflow exists, and it is reachable without a human. ─────
# This is the leg #551 is actually about. The old lane was reachable too — via
# a maintainer merging a PR. "Reachable" here means: cut a release and the Dart
# packages publish, with nobody pressing anything.
if [ -f "$DRIVER" ]; then
  ok "pubdev-release.yml exists"

  if grep -qE '^[[:space:]]*workflow_dispatch:' "$DRIVER"; then
    ok "pubdev-release.yml declares a workflow_dispatch trigger"
  else
    no "pubdev-release.yml declares a workflow_dispatch trigger" \
      "release.yml invokes it with 'gh workflow run', which 422s without workflow_dispatch"
  fi

  # It must drive EVERY publishable package. A driver that quietly lists 8 of 9
  # is the same invisible failure one level down.
  missing=()
  for name in $PKG_NAMES; do
    grep -qF "$name" "$DRIVER" || missing+=("$name")
  done
  if [ "${#missing[@]}" -eq 0 ]; then
    ok "pubdev-release.yml drives every publishable Dart package"
  else
    no "pubdev-release.yml drives every publishable Dart package" \
      "not named in the release loop: ${missing[*]}"
  fi

  # ball_cli's version.g.dart regeneration needs a Dart SDK in this job; without
  # it the prepareCmd fails mid-release, after other packages have published.
  if grep -qF 'dart-lang/setup-dart' "$DRIVER"; then
    ok "pubdev-release.yml sets up a Dart SDK (ball_cli's version.g.dart regen needs it)"
  else
    no "pubdev-release.yml sets up a Dart SDK (ball_cli's version.g.dart regen needs it)" \
      "ball_cli.releaserc.json's prepareCmd runs 'dart run tool/gen_version.dart'"
  fi
else
  no "pubdev-release.yml exists" \
    "the nine Dart packages have semantic-release configs but no workflow that runs them," \
    "so a merge to main publishes nothing to pub.dev (#551)"
fi

# release.yml must dispatch it, guarded on a release actually having been cut.
# The --ref is `main`, NOT the vX.Y.Z tag the sibling channels use: this driver
# does not build the released tree, it RUNS semantic-release, whose
# @semantic-release/git step pushes commits and tags to the main branch. A
# detached tag ref has no branch for semantic-release to release from.
if grep -qF 'gh workflow run pubdev-release.yml --ref main' "$RELEASE"; then
  ok "release.yml dispatches pubdev-release.yml (--ref main, the branch semantic-release releases from)"
else
  no "release.yml dispatches pubdev-release.yml (--ref main, the branch semantic-release releases from)" \
    "expected a step running: gh workflow run pubdev-release.yml --ref main" \
    "a push-triggered driver cannot substitute: release.yml's own semantic-release commit carries" \
    "[skip ci], and racing it would push two release commits at main concurrently"
fi

line="$(grep -nF 'gh workflow run pubdev-release.yml --ref' "$RELEASE" | head -1 | cut -d: -f1)"
if [ -n "$line" ]; then
  start=$((line - 8))
  [ "$start" -lt 1 ] && start=1
  if sed -n "${start},${line}p" "$RELEASE" |
    grep -qF "if: steps.semrel.outputs.released_version != ''"; then
    ok "the pubdev-release.yml dispatch is guarded on released_version != ''"
  else
    no "the pubdev-release.yml dispatch is guarded on released_version != ''" \
      "an unguarded dispatch fires on every push to main, releasing or not"
  fi
else
  no "the pubdev-release.yml dispatch is guarded on released_version != ''" \
    "no dispatch line for pubdev-release.yml to guard"
fi

# ── 5. Single owner. Two workflows releasing the same package race each other
#      into duplicate tags and double version bumps.
for other in "$WORKFLOWS"/*.yml; do
  [ -f "$other" ] || continue
  case "$(basename "$other")" in
  pubdev-release.yml | release-publish.yml) continue ;;
  esac
  dupes=()
  for name in $PKG_NAMES; do
    # `<pkg>` alone appears in unrelated prose; the release-loop shape is the
    # bare package name on its own line inside a config list.
    grep -qE "^[[:space:]]*$name[[:space:]]*$" "$other" && dupes+=("$name")
  done
  if [ "${#dupes[@]}" -eq 0 ]; then
    ok "$(basename "$other") does not also drive the Dart release configs"
  else
    no "$(basename "$other") does not also drive the Dart release configs" \
      "also lists: ${dupes[*]}" \
      "two drivers for one package cut duplicate tags and double-bump the pubspec"
  fi
done

# ── 6. The retired Melos versioning lane must not come back. ──────────────
# `melos version` (run-versioning) and `melos tag` were the rolling-PR lane. A
# workflow reintroducing either re-creates the human checkpoint #551 is about,
# and would fight semantic-release for the same pubspec versions.
for dead in release-prepare.yml release-tag.yml; do
  if [ -f "$WORKFLOWS/$dead" ]; then
    no "$dead is retired" \
      "the Melos rolling-release-PR lane is replaced by pubdev-release.yml; leaving $dead in place" \
      "means Melos and semantic-release both bump the same nine pubspecs"
  else
    ok "$dead is retired"
  fi
done

melos_versioning=()
for wf in "$WORKFLOWS"/*.yml; do
  [ -f "$wf" ] || continue
  if grep -qE '^[[:space:]]*(run-versioning|tag):[[:space:]]*true' "$wf"; then
    melos_versioning+=("$(basename "$wf")")
  fi
done
if [ "${#melos_versioning[@]}" -eq 0 ]; then
  ok "no workflow runs Melos versioning or tagging"
else
  no "no workflow runs Melos versioning or tagging" \
    "melos-action run-versioning/tag found in: ${melos_versioning[*]}" \
    "semantic-release owns the Dart version line now (docs/RELEASE.md)"
fi

if grep -qE '^[[:space:]]{2}command:' "$ROOT/pubspec.yaml" &&
  sed -n '/^  command:/,/^[a-z]/p' "$ROOT/pubspec.yaml" | grep -qE '^[[:space:]]{4}version:'; then
  no "the root pubspec.yaml no longer configures 'melos version'" \
    "the melos: command: version: block only ever served the retired rolling-PR lane;" \
    "leaving it invites a local 'melos version' run that conflicts with semantic-release's bumps"
else
  ok "the root pubspec.yaml no longer configures 'melos version'"
fi

# ── 7. ball_cli regenerates its single-sourced version constant. ──────────
# dart/cli/lib/src/version.g.dart is generated from dart/cli/pubspec.yaml
# (#363) and ci.yml runs `gen_version.dart --check`. A release that bumps the
# pubspec without regenerating it leaves main red for the next contributor.
CLI_CFG="$CONFIGS/ball_cli.releaserc.json"
if [ -f "$CLI_CFG" ]; then
  if grep -qF 'gen_version.dart' "$CLI_CFG"; then
    ok "ball_cli.releaserc.json regenerates version.g.dart in prepareCmd"
  else
    no "ball_cli.releaserc.json regenerates version.g.dart in prepareCmd" \
      "expected 'dart run tool/gen_version.dart' after the set_manifest_version.mjs call;" \
      "ci.yml's 'CLI version drift check (#363)' fails on the next push otherwise"
  fi
  if grep -qF '"dart/cli/lib/src/version.g.dart"' "$CLI_CFG"; then
    ok "ball_cli.releaserc.json commits version.g.dart with the release"
  else
    no "ball_cli.releaserc.json commits version.g.dart with the release" \
      "expected dart/cli/lib/src/version.g.dart in the @semantic-release/git assets;" \
      "regenerating it without committing it leaves the drift guard red all the same"
  fi
else
  no "ball_cli.releaserc.json exists" "the ball_cli release config is missing entirely"
fi

# ── 8. The publish backend verifies its own publish. ──────────────────────
# publish-pypi.yml proves the published artifact is installable from the real
# index. The pub.dev backend had no post-publish assertion of any kind: a
# publish that silently no-ops looks exactly like one that worked.
if [ -f "$PUBLISH" ]; then
  if grep -qE '^[[:space:]]{2}verify-published:' "$PUBLISH"; then
    ok "release-publish.yml has a verify-published job"
  else
    no "release-publish.yml has a verify-published job" \
      "mirrors publish-pypi.yml: after publishing, read the package back from the real index" \
      "and run it — uploading is not the same as being installable"
  fi
  if grep -qF 'pub.dev/api/packages/' "$PUBLISH"; then
    ok "release-publish.yml reads the published version back from the pub.dev API"
  else
    no "release-publish.yml reads the published version back from the pub.dev API" \
      "expected a poll of https://pub.dev/api/packages/<pkg> asserting latest.version == the tag's version"
  fi
  # Resolving is NOT sufficient: `ball_compiler 0.4.0` requiring `ball_encoder
  # ^0.3.2` resolves for an outside consumer because 0.3.2 is still published.
  # The tag's own tree is the reference the resolution must be measured against.
  if grep -qF 'check_published_siblings.py' "$PUBLISH"; then
    ok "release-publish.yml checks the published resolution against the tag's own tree"
  else
    no "release-publish.yml checks the published resolution against the tag's own tree" \
      "expected tools/release/check_published_siblings.py after the consumer resolution;" \
      "a stale sibling constraint resolves cleanly and is invisible to every other guard"
  fi
else
  no "release-publish.yml exists" "the pub.dev publish backend is missing"
fi

# ── 9. Both pub.dev guards are wired into CI. ─────────────────────────────
if grep -qF 'tools/release/check_pubdev_release_wiring.sh' "$CI"; then
  ok "ci.yml runs this guard"
else
  no "ci.yml runs this guard" "a guard nothing invokes is not a guard"
fi

if grep -qF 'tools/release/check_pubdev_freshness.sh' "$CI"; then
  ok "ci.yml runs the pub.dev freshness guard's self-test"
else
  no "ci.yml runs the pub.dev freshness guard's self-test" \
    "the freshness guard's network leg belongs on a schedule, but its comparison logic" \
    "must still be exercised on every PR — see tools/release/check_pubdev_freshness.sh --self-test"
fi

# ── 10. The workspace invariants `melos version` used to hold for free. ───
# All ten packages under dart/ are ONE pub resolution unit; a release that
# re-pins only the releasing package's pubspec leaves the rest asking for a
# version the workspace no longer contains, and `dart pub get` fails for the
# whole repo. The order the driver walks the packages matters for the same
# reason, one level out: a package released before its dependency publishes a
# tarball pinned to that dependency's OLD version.
if grep -qF 'tools/release/check_pubspec_workspace_consistency.mjs' "$CI"; then
  ok "ci.yml runs the Dart workspace consistency + release-order guard"
else
  no "ci.yml runs the Dart workspace consistency + release-order guard" \
    "expected tools/release/check_pubspec_workspace_consistency.mjs in the Proto Checks job;" \
    "without it a release can leave main unresolvable and nothing says so until someone runs pub get"
fi

if grep -qF 'tools/release/check_published_siblings.py' "$CI"; then
  ok "ci.yml exercises the published-sibling classifier on every PR"
else
  no "ci.yml exercises the published-sibling classifier on every PR" \
    "that check only runs during a real publish, so without a --self-test here its first" \
    "exercise would be the day it had to catch something"
fi

# The workspace-wide sweep must be what the release configs actually invoke; a
# --file= sweep is the per-package shape that leaves the other members behind.
sweep_bad=()
for cfg in "$CONFIGS"/*.releaserc.json; do
  [ -f "$cfg" ] || continue
  grep -qF 'release-publish.yml' "$cfg" || continue
  grep -qF 'sync_pubspec_deps.mjs --workspace-root=.' "$cfg" ||
    sweep_bad+=("$(basename "$cfg") does not run the workspace-wide sibling sweep")
  grep -qF '"dart/*/pubspec.yaml"' "$cfg" ||
    sweep_bad+=("$(basename "$cfg") does not commit dart/*/pubspec.yaml")
done
if [ "${#sweep_bad[@]}" -eq 0 ]; then
  ok "every pub.dev release config sweeps AND commits the whole workspace's pubspecs"
else
  no "every pub.dev release config sweeps AND commits the whole workspace's pubspecs" \
    "${sweep_bad[@]}"
fi

# ── 11. The lockstep rule (#566). ─────────────────────────────────────────
# The sweep re-pins every workspace member on every release; a member with no
# releasable commits is re-pinned in the REPO and never published, so pub.dev
# keeps serving its old pubspec and the published graph splits. Ordering and
# workspace consistency cannot see that — both are satisfied by the broken
# state. These legs pin the three moving parts that make the loop repair it.
LOCKSTEP="$ROOT/tools/release/lockstep_plan.mjs"
FILTER="$ROOT/tools/release/only-package-commits.mjs"

if [ -f "$LOCKSTEP" ]; then
  ok "tools/release/lockstep_plan.mjs exists (the pub.dev-state planner)"
else
  no "tools/release/lockstep_plan.mjs exists (the pub.dev-state planner)" \
    "without it nothing models what pub.dev serves after the run, and a sibling the sweep" \
    "left behind publishes an unsolvable graph (#566)"
fi

if [ -f "$DRIVER" ]; then
  lockstep_probs=()
  grep -qF 'lockstep_plan.mjs --fetch-published' "$DRIVER" ||
    lockstep_probs+=(
      "expected a step running: node tools/release/lockstep_plan.mjs --fetch-published"
      "the baseline must be the LIVE pub.dev graph; the repo tree is kept consistent by the"
      "sweep whether or not its packages were ever published, so it cannot detect this"
    )
  grep -qF 'lockstep_plan.mjs --decide --package=' "$DRIVER" ||
    lockstep_probs+=("expected the loop to ask: node tools/release/lockstep_plan.mjs --decide --package=<pkg>")
  grep -qF 'SR_FORCE_RELEASE=' "$DRIVER" ||
    lockstep_probs+=("expected the planner's verdict to reach semantic-release as SR_FORCE_RELEASE")
  grep -qF 'SR_LOCKSTEP_STATE' "$DRIVER" ||
    lockstep_probs+=(
      "expected SR_LOCKSTEP_STATE in the release step's env; each config's verifyReleaseCmd"
      "records this run's decisions there for the packages that follow"
    )
  if [ "${#lockstep_probs[@]}" -eq 0 ]; then
    ok "pubdev-release.yml plans the run against live pub.dev state and forces lockstep releases"
  else
    no "pubdev-release.yml plans the run against live pub.dev state and forces lockstep releases" \
      "${lockstep_probs[@]}"
  fi
fi

# A REAL release must still run from the tip of main — that is what makes
# @semantic-release/git's push a fast-forward. A DRY RUN must be able to run the
# dispatched ref, or a change to this lane can only ever be exercised by merging
# it, which is how #566 shipped unrehearsed. Both halves are pinned here so
# neither can be dropped in favour of the other.
if [ -f "$DRIVER" ]; then
  ref_probs=()
  grep -qF "inputs.dry_run && github.ref || 'main'" "$DRIVER" ||
    ref_probs+=(
      "expected the checkout ref: \${{ inputs.dry_run && github.ref || 'main' }}"
      "a real run must check out main; a dry run must check out the ref it was dispatched for"
    )
  grep -qF -- '--branches ${GITHUB_REF_NAME}' "$DRIVER" ||
    ref_probs+=(
      "expected the dry-run flag to carry --branches \${GITHUB_REF_NAME}"
      "every config declares branches: [\"main\"], and semantic-release reads the current branch"
      "from GITHUB_REF, so a rehearsal on any other branch computes nothing at all"
    )
  if [ "${#ref_probs[@]}" -eq 0 ]; then
    ok "pubdev-release.yml releases from main but rehearses the dispatched ref under dry_run"
  else
    no "pubdev-release.yml releases from main but rehearses the dispatched ref under dry_run" \
      "${ref_probs[@]}"
  fi
fi

if [ -f "$FILTER" ] && grep -qF 'SR_FORCE_RELEASE' "$FILTER"; then
  ok "only-package-commits.mjs promotes a no-release verdict when SR_FORCE_RELEASE is set"
else
  no "only-package-commits.mjs promotes a no-release verdict when SR_FORCE_RELEASE is set" \
    "the driver computes the lockstep plan, but nothing turns it into a release: the path" \
    "filter is the only place that can override 'There are no relevant changes' (#566)"
fi

if grep -qF 'tools/release/lockstep_plan.mjs --self-test' "$CI"; then
  ok "ci.yml exercises the lockstep planner on every PR"
else
  no "ci.yml exercises the lockstep planner on every PR" \
    "the planner only otherwise runs during a real release, so without a --self-test here its" \
    "first exercise would be the day it had to prevent an unsolvable published graph"
fi

total=$((pass + fail))
# Positive floor (#439/#444): an exit code plus a zero failure count cannot tell
# "all passed" from "nothing ran". With nine publishable packages this sweep
# runs well over 60 cases; 30 is a deliberately loose floor that still catches a
# discovery loop that silently found nothing.
MIN=30
case "$pass$fail$total" in
*[!0-9]*)
  echo "::error::pub.dev release wiring guard produced a non-numeric tally"
  exit 1
  ;;
esac
if [ "$total" -lt "$MIN" ]; then
  echo "::error::pub.dev release wiring guard ran $total cases, expected at least $MIN — the sweep itself is broken"
  exit 1
fi
echo "Results: $pass passed, $fail failed, $total total"
[ "$fail" -eq 0 ] || exit 1
