#!/usr/bin/env python3
"""Post-publish sibling-freshness guard for the pub.dev lane (#551).

WHY THIS EXISTS: resolving a freshly published package is necessary and NOT
sufficient. `ball_compiler 0.4.0` published still requiring `ball_encoder
^0.3.2` resolves perfectly for an outside consumer, because 0.3.2 is still on
pub.dev — `release-publish.yml`'s "resolve as an external consumer" step goes
green while the registry serves a package built against APIs its pinned
dependency predates. That is the exact failure
`tools/release/sync_pubspec_deps.mjs` exists to prevent, and none of the lane's
other guards can see it: the static ones run before the release, and
`check_pubdev_freshness.sh` compares versions and publish dates, which match.

So this compares the CONSUMER'S RESOLUTION against the repo tree at the release
tag, which carries every sibling's version as of this release: each Ball sibling
the consumer resolved must be at least the version that tree declares. A stale
constraint resolves an older sibling and fails here, in the same run that
published it.

It is deliberately one-directional. Resolving a sibling NEWER than the tag's
tree is fine and expected: publishes are dispatched asynchronously, so a
dependency released later in the same loop may already be on pub.dev by the
time this runs.

Usage:
  python3 tools/release/check_published_siblings.py <repo-root> <pubspec.lock> <pkg> <version>
  python3 tools/release/check_published_siblings.py --self-test
"""

from __future__ import annotations

import os
import re
import sys
import tempfile

_VERSION = re.compile(r"(\d+)\.(\d+)\.(\d+)(?:\+(\d+))?")


def parse_version(value: str):
    """`X.Y.Z(+build)` -> a comparable tuple, or None for anything else."""
    m = _VERSION.fullmatch(value.strip())
    if not m:
        return None
    return (int(m[1]), int(m[2]), int(m[3]), -1 if m[4] is None else int(m[4]))


def declared_versions(root: str) -> dict[str, str]:
    """Every publishable Dart package's version as declared in the tree."""
    declared: dict[str, str] = {}
    dart_dir = os.path.join(root, "dart")
    if not os.path.isdir(dart_dir):
        return declared
    for entry in sorted(os.listdir(dart_dir)):
        path = os.path.join(dart_dir, entry, "pubspec.yaml")
        if not os.path.isfile(path):
            continue
        with open(path, encoding="utf-8") as fh:
            text = fh.read()
        if re.search(r"^publish_to:\s*none", text, re.M):
            continue
        name = re.search(r"^name:\s*(\S+)", text, re.M)
        version = re.search(r"^version:\s*(\S+)", text, re.M)
        if name and version:
            declared[name[1]] = version[1]
    return declared


def resolved_versions(lock_path: str) -> dict[str, str]:
    """name -> version from a pubspec.lock.

    pub writes each package as `  <name>:` followed by an indented block whose
    `    version: "x.y.z"` is the resolved one. The nested `      name:` inside
    `description:` is at six spaces and must not be mistaken for a package.
    """
    resolved: dict[str, str] = {}
    current: str | None = None
    with open(lock_path, encoding="utf-8") as fh:
        for raw in fh:
            line = raw.rstrip("\n").rstrip("\r")
            m = re.fullmatch(r" {2}([A-Za-z_][A-Za-z0-9_]*):", line)
            if m:
                current = m[1]
                continue
            m = re.fullmatch(r' {4}version: "?([^"]+)"?', line)
            if m and current:
                resolved[current] = m[1]
                current = None
    return resolved


def stale_siblings(root: str, lock_path: str, pkg: str, version: str):
    """(checked_count, [problem strings])."""
    declared = declared_versions(root)
    resolved = resolved_versions(lock_path)
    checked = 0
    problems = []
    for name, got in sorted(resolved.items()):
        if name == pkg or name not in declared:
            continue
        want = parse_version(declared[name])
        have = parse_version(got)
        if want is None or have is None:
            continue
        checked += 1
        if have < want:
            problems.append(
                f"{pkg} {version} resolved {name} {got}, but the tree at this tag declares "
                f"{name} {declared[name]} — {pkg} was published with a stale sibling constraint"
            )
    return checked, problems


_LOCK_FIXTURE = """\
# Generated by pub
packages:
  ball_base:
    dependency: transitive
    description:
      name: ball_base
      sha256: "aaaa"
      url: "https://pub.dev"
    source: hosted
    version: "0.3.0+3"
  ball_encoder:
    dependency: transitive
    description:
      name: ball_encoder
      sha256: "bbbb"
      url: "https://pub.dev"
    source: hosted
    version: "0.5.0"
  ball_compiler:
    dependency: "direct main"
    description:
      name: ball_compiler
      sha256: "cccc"
      url: "https://pub.dev"
    source: hosted
    version: "0.4.0"
  protobuf:
    dependency: transitive
    description:
      name: protobuf
      sha256: "dddd"
      url: "https://pub.dev"
    source: hosted
    version: "6.0.0"
sdks:
  dart: ">=3.9.0 <4.0.0"
"""


def _write_tree(root: str, packages: dict[str, tuple[str, bool]]) -> None:
    for directory, (spec, private) in packages.items():
        d = os.path.join(root, "dart", directory)
        os.makedirs(d, exist_ok=True)
        name, version = spec.split("@")
        body = f"name: {name}\n"
        if private:
            body += "publish_to: none\n"
        body += f"version: {version}\n"
        with open(os.path.join(d, "pubspec.yaml"), "w", encoding="utf-8") as fh:
            fh.write(body)


def self_test() -> int:
    results = []

    def check(label: str, condition: bool, detail: str = "") -> None:
        results.append((label, condition, detail))

    tmp = tempfile.mkdtemp(prefix="ball-sibcheck-")
    lock = os.path.join(tmp, "pubspec.lock")
    with open(lock, "w", encoding="utf-8") as fh:
        fh.write(_LOCK_FIXTURE)

    resolved = resolved_versions(lock)
    check(
        "reads every package version out of a real pubspec.lock",
        resolved
        == {
            "ball_base": "0.3.0+3",
            "ball_encoder": "0.5.0",
            "ball_compiler": "0.4.0",
            "protobuf": "6.0.0",
        },
        repr(resolved),
    )
    check(
        "does not mistake description.name for a package entry",
        "sha256" not in resolved and "url" not in resolved,
        repr(sorted(resolved)),
    )

    # A CRLF checkout must classify identically.
    crlf_lock = os.path.join(tmp, "pubspec.crlf.lock")
    with open(crlf_lock, "wb") as fh:
        fh.write(_LOCK_FIXTURE.replace("\n", "\r\n").encode("utf-8"))
    check(
        "parses a CRLF pubspec.lock identically",
        resolved_versions(crlf_lock) == resolved,
        repr(resolved_versions(crlf_lock)),
    )

    # The tree the tag carries: ball_base has moved to 0.4.0, so ball_compiler
    # 0.4.0 resolving ball_base 0.3.0+3 is the stale-constraint failure.
    stale_root = os.path.join(tmp, "stale")
    _write_tree(
        stale_root,
        {
            "shared": ("ball_base@0.4.0", False),
            "encoder": ("ball_encoder@0.5.0", False),
            "compiler": ("ball_compiler@0.4.0", False),
            "self_host": ("ball_self_host_tests@0.0.0", True),
        },
    )
    checked, problems = stale_siblings(stale_root, lock, "ball_compiler", "0.4.0")
    check(
        "flags a published package whose resolved sibling is behind the tag's tree",
        len(problems) == 1 and "ball_base" in problems[0],
        repr(problems),
    )
    check(
        "checks every Ball sibling in the resolution, not just the first",
        checked == 2,
        f"checked={checked}",
    )
    check(
        "ignores third-party packages in the lock",
        all("protobuf" not in p for p in problems),
        repr(problems),
    )

    # Same lock, a tree whose ball_base matches: clean.
    fresh_root = os.path.join(tmp, "fresh")
    _write_tree(
        fresh_root,
        {
            "shared": ("ball_base@0.3.0+3", False),
            "encoder": ("ball_encoder@0.5.0", False),
            "compiler": ("ball_compiler@0.4.0", False),
        },
    )
    checked_ok, problems_ok = stale_siblings(fresh_root, lock, "ball_compiler", "0.4.0")
    check(
        "passes when every resolved sibling matches the tag's tree",
        problems_ok == [] and checked_ok == 2,
        repr((checked_ok, problems_ok)),
    )

    # A sibling AHEAD of the tree is fine: publishes are dispatched async, so a
    # dependency released later in the same loop may already be live.
    ahead_root = os.path.join(tmp, "ahead")
    _write_tree(
        ahead_root,
        {
            "shared": ("ball_base@0.3.0+3", False),
            "encoder": ("ball_encoder@0.4.0", False),
            "compiler": ("ball_compiler@0.4.0", False),
        },
    )
    _, problems_ahead = stale_siblings(ahead_root, lock, "ball_compiler", "0.4.0")
    check(
        "accepts a sibling resolved NEWER than the tag's tree",
        problems_ahead == [],
        repr(problems_ahead),
    )

    # Private members never participate: they are not on pub.dev at all.
    check(
        "excludes publish_to: none packages from the declared set",
        "ball_self_host_tests" not in declared_versions(stale_root),
        repr(sorted(declared_versions(stale_root))),
    )

    # Build metadata ordering: 0.3.0+6 is NEWER than 0.3.0+3, and 0.3.0 is the
    # oldest of the three. A naive string compare gets the last one wrong.
    check(
        "orders Dart build metadata correctly",
        parse_version("0.3.0+6") > parse_version("0.3.0+3") > parse_version("0.3.0"),
        "0.3.0+6 > 0.3.0+3 > 0.3.0",
    )

    passed = sum(1 for _, condition, _ in results if condition)
    failed = len(results) - passed
    for label, condition, detail in results:
        print(f"{'PASS' if condition else 'FAIL'}  {label}")
        if not condition and detail:
            print(f"  {detail}")
    total = len(results)
    minimum = 10
    if total < minimum:
        print(
            f"::error::published-sibling guard self-test ran {total} cases, "
            f"expected at least {minimum} — the sweep itself is broken"
        )
        return 1
    print(f"Results: {passed} passed, {failed} failed, {total} total")
    return 0 if failed == 0 else 1


def main(argv: list[str]) -> int:
    if "--self-test" in argv:
        return self_test()
    if len(argv) != 4:
        print(
            "usage: check_published_siblings.py <repo-root> <pubspec.lock> <package> <version>",
            file=sys.stderr,
        )
        return 2
    root, lock_path, pkg, version = argv
    checked, problems = stale_siblings(root, lock_path, pkg, version)
    print(f"checked {checked} Ball sibling(s) in the published resolution of {pkg} {version}")
    for problem in problems:
        print(f"::error::{problem}")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
