using Ball.Shared;
using Ball.V1;

namespace Ball.Engine;

/// <summary>
/// A loaded Ball program, ready to run — the self-hosted engine wrapper's facade
/// (issue #383), the C# sibling of <c>rust/engine/src/lib.rs</c>'s
/// <c>BallEngine</c>.
///
/// <para><b>Design: self-host, mirroring the Rust/TS/C++ targets.</b> Rather than
/// hand-writing a tree-walking interpreter, the engine is the reference engine
/// itself — a Ball program (<c>dart/self_host/engine.ball.pb</c>) — compiled
/// through the Ball → C# compiler into <c>src/CompiledEngine.cs</c> (a
/// gitignored, never-edit generated file regenerated by <c>csharp/engine/tool</c>).
/// This thin wrapper supplies what compiled Ball cannot express natively: loading
/// a target program and viewing it as the canonical proto3-JSON
/// <see cref="BallValue"/> the compiled engine reads (<see cref="Loader"/>), and
/// the <c>ball_proto</c> access-pattern functions it calls to inspect that
/// program (<see cref="BallProto"/>).</para>
///
/// <para><b>Self-host status (#383).</b> The wrapper foundation (loader +
/// <c>ball_proto</c>) is complete and tested, but the generated
/// <c>CompiledEngine.cs</c> does not yet compile through the current Ball → C#
/// compiler (a bounded category grind — see the issue). It is feature-gated off
/// by default (<c>-p:SelfHost=true</c> includes it, for error measurement), so
/// <see cref="Run"/> reports <see cref="SelfHostPendingException"/> until the
/// grind lands. The loader and <c>ball_proto</c> access patterns this wrapper
/// provides are exercised independently by the engine test suite.</para>
/// </summary>
public sealed class BallEngine
{
    private BallEngine(Program program, BallValue programValue)
    {
        Program = program;
        ProgramValue = programValue;
    }

    /// <summary>The typed program (entry point, modules, functions).</summary>
    public Program Program { get; }

    /// <summary>
    /// The canonical proto3-JSON <see cref="BallValue"/> view of the program —
    /// the shape the <see cref="BallProto"/> access-pattern helpers read.
    /// </summary>
    public BallValue ProgramValue { get; }

    /// <summary>Load a program from proto3-JSON <c>.ball.json</c> source (the <c>@type</c> envelope is stripped).</summary>
    public static BallEngine FromJson(string json)
    {
        var (program, view) = Loader.ParseJson(json);
        return new BallEngine(program, view);
    }

    /// <summary>Load a program from binary-protobuf <c>.ball.pb</c> bytes (a <c>google.protobuf.Any</c> envelope).</summary>
    public static BallEngine FromBinary(byte[] bytes)
    {
        var (program, view) = Loader.ParseBinary(bytes);
        return new BallEngine(program, view);
    }

    /// <summary>
    /// Run the program, returning its captured stdout lines.
    ///
    /// <para>The compiled self-hosted engine driver is not yet wired in — the
    /// generated <c>CompiledEngine.cs</c> does not compile through the current
    /// Ball → C# compiler (issue #383; a bounded category grind). This method
    /// therefore throws <see cref="SelfHostPendingException"/>; the loader, the
    /// program view, and the <c>ball_proto</c> access patterns this wrapper
    /// provides are still exercised (see the engine test suite).</para>
    /// </summary>
    public IReadOnlyList<string> Run() =>
        throw new SelfHostPendingException(
            "the compiled self-hosted engine (CompiledEngine.cs) does not yet compile through " +
            "the Ball -> C# compiler (issue #383); the loader + ball_proto foundation is in place.");
}

/// <summary>A failure loading a Ball program (bad JSON, wrong shape, or undecodable binary).</summary>
public sealed class EngineException : Exception
{
    /// <summary>Create a load/parse error.</summary>
    public EngineException(string message)
        : base(message)
    {
    }
}

/// <summary>
/// The self-hosted engine driver is not yet available — the generated
/// <c>CompiledEngine.cs</c> does not compile through the current Ball → C#
/// compiler (issue #383). The C# analog of Rust's
/// <c>EngineError::SelfHostPending</c>.
/// </summary>
public sealed class SelfHostPendingException : Exception
{
    /// <summary>Create a self-host-pending signal describing the blocking gap.</summary>
    public SelfHostPendingException(string message)
        : base(message)
    {
    }
}
