using Ball.Shared;
using Ball.V1;

namespace Ball.Engine;

/// <summary>
/// A loaded Ball program, ready to run — the self-hosted engine wrapper's facade
/// (issue #383), the C# sibling of <c>rust/engine/src/lib.rs</c>'s
/// <c>BallEngine</c>.
///
/// <para><b>Design: self-host, mirroring the Rust/TS/C++ targets.</b> Rather than
/// hand-writing a tree-walking interpreter, the engine is the reference engine
/// itself — a Ball program (<c>dart/self_host/engine.ball.pb</c>) — compiled
/// through the Ball → C# compiler into <c>src/CompiledEngine.cs</c> (a
/// gitignored, never-edit generated file regenerated by <c>csharp/engine/tool</c>).
/// This thin wrapper supplies what compiled Ball cannot express natively: loading
/// a target program and viewing it as the canonical proto3-JSON
/// <see cref="BallValue"/> the compiled engine reads (<see cref="Loader"/>), and
/// the <c>ball_proto</c> access-pattern functions it calls to inspect that
/// program (<see cref="BallProto"/>).</para>
///
/// <para><b>Self-host status (#383).</b> The wrapper foundation (loader +
/// <c>ball_proto</c>) is complete and tested, but the generated
/// <c>CompiledEngine.cs</c> does not yet compile through the current Ball → C#
/// compiler (a bounded category grind — see the issue). It is feature-gated off
/// by default (<c>-p:SelfHost=true</c> includes it, for error measurement), so
/// <see cref="Run"/> reports <see cref="SelfHostPendingException"/> until the
/// grind lands. The loader and <c>ball_proto</c> access patterns this wrapper
/// provides are exercised independently by the engine test suite.</para>
/// </summary>
public sealed class BallEngine
{
    private BallEngine(Program program, BallValue programValue)
    {
        Program = program;
        ProgramValue = programValue;
    }

    /// <summary>The typed program (entry point, modules, functions).</summary>
    public Program Program { get; }

    /// <summary>
    /// The canonical proto3-JSON <see cref="BallValue"/> view of the program —
    /// the shape the <see cref="BallProto"/> access-pattern helpers read.
    /// </summary>
    public BallValue ProgramValue { get; }

    /// <summary>Load a program from proto3-JSON <c>.ball.json</c> source (the <c>@type</c> envelope is stripped).</summary>
    public static BallEngine FromJson(string json)
    {
        var (program, view) = Loader.ParseJson(json);
        return new BallEngine(program, view);
    }

    /// <summary>Load a program from binary-protobuf <c>.ball.pb</c> bytes (a <c>google.protobuf.Any</c> envelope).</summary>
    public static BallEngine FromBinary(byte[] bytes)
    {
        var (program, view) = Loader.ParseBinary(bytes);
        return new BallEngine(program, view);
    }

    /// <summary>
    /// Run the program, returning its captured stdout lines.
    ///
    /// <para>The compiled self-hosted engine driver is not yet wired in — the
    /// generated <c>CompiledEngine.cs</c> does not compile through the current
    /// Ball → C# compiler (issue #383; a bounded category grind). This method
    /// therefore throws <see cref="SelfHostPendingException"/>; the loader, the
    /// program view, and the <c>ball_proto</c> access patterns this wrapper
    /// provides are still exercised (see the engine test suite).</para>
    /// </summary>
    public IReadOnlyList<string> Run()
    {
#if SELF_HOST
        return RunSelfHosted();
#else
        throw new SelfHostPendingException(
            "the compiled self-hosted engine driver is off in the default build (issue #383); " +
            "build with -p:SelfHost=true to include the generated CompiledEngine.cs and driver.");
#endif
    }

#if SELF_HOST
    /// <summary>
    /// Drive the compiled self-hosted engine (issue #383): build its 16-field
    /// constructor input (the program view, an stdout callback capturing into a
    /// shared buffer, permissive limits, and a StdModuleHandler), construct the
    /// <c>BallEngine</c> instance via its compiled constructor, then call the
    /// compiled <c>run</c>. Mirrors <c>rust/engine/src/lib.rs</c>'s
    /// <c>run_self_hosted</c>. Runs on a large-stack thread — the self-hosted
    /// engine is a deep tree-walker whose compiled methods each carry a very large
    /// frame (hundreds of field-alias locals), so even a modestly recursive target
    /// (<c>fibonacci(10)</c>) overflows the default stack.
    /// </summary>
    private IReadOnlyList<string> RunSelfHosted()
    {
        var output = new List<string>();
        Exception? failure = null;

        var worker = new System.Threading.Thread(
            () =>
            {
                try
                {
                    var stdout = new BallFunction("stdout", message =>
                    {
                        output.Add(message.ToString() ?? string.Empty);
                        return BallValue.Null;
                    });

                    // The compiled StdModuleHandler — the module handler the engine
                    // consults for every std/std_collections/… base call. Built here
                    // with its field-level defaults (the constructor's
                    // `moduleHandlers ?? [StdModuleHandler()]` default is a cosmetic
                    // initializer the compiler does not evaluate).
                    var stdFields = new BallMap();
                    stdFields.Set("_dispatch", new BallMap());
                    stdFields.Set("_composedDispatch", new BallMap());
                    stdFields.Set("_tombstones", new BallList());
                    stdFields.Set("_allowlist", BallValue.Null);
                    var stdHandler = (BallValue)new BallMessage("main:StdModuleHandler", stdFields);

                    var ctorInput = new BallMap();
                    ctorInput.Set("program", ProgramValue);
                    ctorInput.Set("stdout", stdout);
                    ctorInput.Set("stderr", BallValue.Null);
                    ctorInput.Set("stdinReader", BallValue.Null);
                    ctorInput.Set("envGet", BallValue.Null);
                    ctorInput.Set("args", new BallList());
                    ctorInput.Set("enableProfiling", BallValue.Bool(false));
                    ctorInput.Set("maxRecursionDepth", BallValue.Int(100_000));
                    ctorInput.Set("timeoutMs", BallValue.Null);
                    ctorInput.Set("maxMemoryBytes", BallValue.Null);
                    ctorInput.Set("maxModules", BallValue.Int(1_000_000));
                    ctorInput.Set("maxExpressionDepth", BallValue.Int(1_000_000));
                    ctorInput.Set("maxProgramSizeBytes", BallValue.Null);
                    ctorInput.Set("sandbox", BallValue.Bool(false));
                    ctorInput.Set("moduleHandlers", new BallList(new[] { stdHandler }));
                    ctorInput.Set("resolver", BallValue.Null);

                    var engine = BallProgram.BallEngine__new((BallValue)ctorInput);
                    var runInput = new BallMap();
                    runInput.Set("self", engine);
                    BallProgram.run((BallValue)runInput);
                }
                catch (Exception e)
                {
                    failure = e;
                }
            },
            256 * 1024 * 1024);

        worker.Start();
        worker.Join();

        if (failure is not null)
        {
            var frames = failure.StackTrace?.Split('\n').Take(6);
            throw new EngineException(
                $"self-hosted engine did not complete: {failure.Message}\n{string.Join("\n", frames ?? Array.Empty<string>())}");
        }

        return output;
    }
#endif
}

/// <summary>A failure loading a Ball program (bad JSON, wrong shape, or undecodable binary).</summary>
public sealed class EngineException : Exception
{
    /// <summary>Create a load/parse error.</summary>
    public EngineException(string message)
        : base(message)
    {
    }
}

/// <summary>
/// The self-hosted engine driver is not yet available — the generated
/// <c>CompiledEngine.cs</c> does not compile through the current Ball → C#
/// compiler (issue #383). The C# analog of Rust's
/// <c>EngineError::SelfHostPending</c>.
/// </summary>
public sealed class SelfHostPendingException : Exception
{
    /// <summary>Create a self-host-pending signal describing the blocking gap.</summary>
    public SelfHostPendingException(string message)
        : base(message)
    {
    }
}
