#!/usr/bin/env python3
"""Derive the CI overlay port from the real ball-lang vcpkg port.

`ports/ball-lang/portfile.cmake` is the file that will be submitted upstream to
microsoft/vcpkg: it downloads a tagged release tarball with `vcpkg_from_github`
and checks it against a real SHA512. CI cannot use that as-is — the point of the
smoke is to prove the recipe builds *this commit's* cpp/ tree, before a tag (and
its hash) exists.

So the overlay is GENERATED, never hand-maintained: this script copies the port
verbatim and replaces exactly one thing — the `vcpkg_from_github(...)` call —
with `set(SOURCE_PATH "<local path>")`. Everything else (vcpkg_cmake_configure,
vcpkg_cmake_install, vcpkg_copy_tools, vcpkg_install_copyright, the CMake
options) stays byte-identical to the submission file, so the smoke exercises the
real recipe and a future edit to the real port cannot silently desync from what
CI tests.

Usage:

    python3 tools/vcpkg-port/make_ci_overlay.py <overlay-dir> <source-path>
"""

from __future__ import annotations

import argparse
import pathlib
import shutil
import sys

PORT_NAME = "ball-lang"
CALL_OPEN = "vcpkg_from_github("


def rewrite_portfile(text: str, source_path: str) -> str:
    """Replace the single `vcpkg_from_github(...)` call with a local SOURCE_PATH.

    The call is matched structurally, not by regex over the whole file: its
    closing paren is the first subsequent line that is exactly ")". Brace/paren
    counting would be wrong here — the port's SHA512 comment block itself
    contains parentheses.
    """
    lines = text.splitlines(keepends=True)
    opens = [i for i, line in enumerate(lines) if line.strip() == CALL_OPEN]
    if len(opens) != 1:
        raise SystemExit(
            f"expected exactly one line `{CALL_OPEN}` in portfile.cmake, found {len(opens)}"
        )
    start = opens[0]
    close = None
    for i in range(start + 1, len(lines)):
        if lines[i].rstrip("\r\n") == ")":
            close = i
            break
    if close is None:
        raise SystemExit("vcpkg_from_github( has no closing `)` on a line of its own")

    nl = "\r\n" if lines[start].endswith("\r\n") else "\n"
    replacement = nl.join(
        [
            "# CI overlay (generated by tools/vcpkg-port/make_ci_overlay.py): the real",
            "# port's vcpkg_from_github() download is replaced by the checkout under",
            "# test, so the recipe below is exercised against THIS commit's cpp/ tree.",
            "# Every other line in this file is byte-identical to the submission port.",
            f'set(SOURCE_PATH "{source_path}")',
            "",
        ]
    )
    return "".join(lines[:start]) + replacement + "".join(lines[close + 1:])


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("overlay_dir", help="directory to write the overlay port tree into")
    parser.add_argument("source_path", help="path vcpkg should build from (the repo checkout)")
    args = parser.parse_args(argv)

    port_src = pathlib.Path(__file__).resolve().parent / "ports" / PORT_NAME
    overlay_port = pathlib.Path(args.overlay_dir).resolve() / PORT_NAME
    if overlay_port.exists():
        shutil.rmtree(overlay_port)
    shutil.copytree(port_src, overlay_port)

    portfile = overlay_port / "portfile.cmake"
    source_path = args.source_path.replace("\\", "/")
    # newline="" on both ends: the untouched lines must stay byte-identical to
    # the submission port, line endings included, so the "only the download
    # block differs" claim is verifiable with a plain diff.
    with portfile.open("r", encoding="utf-8", newline="") as fh:
        original = fh.read()
    with portfile.open("w", encoding="utf-8", newline="") as fh:
        fh.write(rewrite_portfile(original, source_path))
    print(overlay_port.parent)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
