//! Regenerate `rust/engine/src/compiled_engine.rs` from the self-hosted Ball
//! engine (`dart/self_host/engine.ball.json`) — the self-host route (issue
//! #39), mirroring the TypeScript target's regeneration command (see
//! CLAUDE.md's "Build & Test") and `dart/compiler/tool/compile_engine_cpp.dart`.
//!
//! Pipeline:
//!   1. Read `dart/self_host/engine.ball.json` — a self-describing
//!      `google.protobuf.Any` envelope (`{"@type":".../ball.v1.Program", …}`).
//!   2. **Strip the `@type` envelope** (it is not part of the `ball.v1.Program`
//!      schema) before deserializing.
//!   3. proto3-JSON -> `DynamicMessage` -> binary -> typed `Program`
//!      (the same load path `ball-shared`/`ball-compiler` tests use).
//!   4. Compile via `ball_compiler::Compiler` -> Rust source.
//!   5. Write `rust/engine/src/compiled_engine.rs` with a NEVER-edit header.
//!
//! `compiled_engine.rs` is a **generated, NEVER-edit** file — fix the compiler
//! or the wrapper and rerun this, never hand-patch the output.
//!
//! Usage (from anywhere): `cargo run -p ball-engine-regen`.

use std::path::{Path, PathBuf};

use ball_compiler::Compiler;
use ball_shared::DESCRIPTOR_POOL;
use ball_shared::proto::ball::v1::Program;
use prost::Message;
use prost_reflect::DynamicMessage;

/// The auto-generated banner prepended to `compiled_engine.rs`. The
/// `@generated` marker keeps the file out of manual review churn (many tools
/// and code hosts recognize it), and `rustfmt::skip`/broad `allow`s keep the
/// machine-emitted source from tripping lint/format gates it was never
/// hand-authored to satisfy.
const HEADER: &str = "\
// @generated by `cargo run -p ball-engine-regen` from dart/self_host/engine.ball.json.
//
// DO NOT EDIT BY HAND. This is the self-hosted Ball engine, compiled from the
// reference engine's own Ball encoding through `ball-compiler`. To change it,
// fix `rust/compiler/` (or the `dart/self_host/` source) and rerun the
// regenerator — never hand-patch this file. See rust/engine/AGENTS.md.
#![cfg_attr(rustfmt, rustfmt::skip)]
#![allow(warnings, clippy::all)]

";

fn repo_root() -> PathBuf {
    // CARGO_MANIFEST_DIR = .../rust/engine/tool ; the repo root is four levels
    // up (tool -> engine -> rust -> <repo root>).
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(3)
        .expect("rust/engine/tool must have a repo-root ancestor")
        .to_path_buf()
}

/// Load a `.ball.json` file — stripping the cosmetic `@type` Any envelope —
/// into a typed [`Program`] via prost-reflect (proto3 JSON -> `DynamicMessage`
/// -> binary -> typed `Program`), the same path `ball-compiler`'s own tests
/// use.
fn load_ball_program(path: &Path) -> Program {
    let json = std::fs::read_to_string(path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));
    let mut json_value: serde_json::Value =
        serde_json::from_str(&json).expect("engine.ball.json must be valid JSON");
    if let serde_json::Value::Object(map) = &mut json_value {
        map.remove("@type");
    }
    let program_descriptor = DESCRIPTOR_POOL
        .get_message_by_name("ball.v1.Program")
        .expect("ball.v1.Program must be resolvable from the embedded descriptor pool");
    let dynamic =
        DynamicMessage::deserialize(program_descriptor, json_value).unwrap_or_else(|err| {
            panic!(
                "{} must deserialize as a ball.v1.Program: {err}",
                path.display()
            )
        });
    Program::decode(dynamic.encode_to_vec().as_slice())
        .expect("binary re-encoded from the DynamicMessage must decode as a typed ball.v1.Program")
}

fn main() {
    let root = repo_root();
    let engine_json = root.join("dart/self_host/engine.ball.json");
    let out_path = root.join("rust/engine/src/compiled_engine.rs");

    eprintln!("[regen-engine] loading {}", engine_json.display());
    let program = load_ball_program(&engine_json);
    eprintln!(
        "[regen-engine] compiling program {:?} v{} ({} modules)",
        program.name,
        program.version,
        program.modules.len()
    );

    // The self-hosted engine is a *library* (it has no runnable top-level
    // entry point — its public surface is the `BallEngine`/`StdModuleHandler`
    // classes the wrapper drives), so compile it in library mode.
    let compiler = Compiler::new(&program);
    let rust_src = compiler.compile_library();

    let mut out = String::with_capacity(HEADER.len() + rust_src.len());
    out.push_str(HEADER);
    out.push_str(&rust_src);
    std::fs::write(&out_path, &out)
        .unwrap_or_else(|err| panic!("failed to write {}: {err}", out_path.display()));
    eprintln!(
        "[regen-engine] wrote {} ({} bytes)",
        out_path.display(),
        out.len()
    );
}
