/// Ball → TypeScript compiler.
///
/// Mirrors [DartCompiler]'s architecture: walk the Ball [Program]
/// expression tree and emit idiomatic TypeScript source. The emitted
/// code is runnable under Node 22+ via
/// `node --experimental-strip-types file.ts` — no external compiler
/// toolchain required.
///
/// Coverage scope is the 30-fixture Dart corpus under
/// `tests/fixtures/dart/` — enough to hit every statement and
/// expression kind the Dart encoder produces for straightforward
/// programs. Intentionally does NOT try to be a full Dart→TS
/// transpiler; classes, extensions, generics, records, etc. are
/// out of scope.
library;

import 'package:ball_base/gen/ball/v1/ball.pb.dart';
import 'package:protobuf/well_known_types/google/protobuf/struct.pb.dart'
    as structpb;

import 'src/ts_emit_plan.dart';
import 'src/ts_emit_runner.dart';

/// Compiles a Ball [Program] to TypeScript source.
class TsCompiler {
  final Program program;
  TsCompiler(this.program);

  /// Mutable so helper methods can temporarily redirect output to a
  /// fresh buffer (see [_captureInto]) when building body strings for
  /// the structural emit plan.
  StringBuffer _out = StringBuffer();
  int _depth = 0;
  String get _ind => '  ' * _depth;

  /// Variables currently bound to a BallException-shaped object in a
  /// catch body — field access on these compiles to bracket lookup so
  /// `e.detail` becomes `e['detail']` (Dart-style thrown maps).
  final Set<String> _catchVars = {};

  /// Runs [body] with [_out] temporarily replaced by a fresh buffer,
  /// returning the contents written into that buffer. Used to capture
  /// function / method / ctor body strings for the structural emit
  /// plan (see [buildEmitPlan]).
  String _captureInto(void Function() body) {
    final saved = _out;
    final savedDepth = _depth;
    _out = StringBuffer();
    _depth = 0;
    try {
      body();
      return _out.toString().trimRight();
    } finally {
      _out = saved;
      _depth = savedDepth;
    }
  }

  /// Compile the program. Returns ready-to-run TypeScript source.
  String compile() {
    _out.clear();
    _out.writeln('// Generated by ball_compiler (TypeScript target)');
    _out.writeln('// Source: ${program.name} v${program.version}');
    _out.writeln();

    // Find the entry module + entry function.
    Module? entryMod;
    FunctionDefinition? entryFn;
    for (final m in program.modules) {
      if (m.name == program.entryModule) {
        entryMod = m;
        for (final f in m.functions) {
          if (f.name == program.entryFunction) entryFn = f;
        }
      }
    }
    if (entryMod == null) {
      throw StateError('Entry module "${program.entryModule}" not found');
    }

    // Emit top-level functions (non-base, non-entry).
    for (final fn in entryMod.functions) {
      if (fn.isBase) continue;
      if (fn.name == program.entryFunction) continue;
      _emitFunction(fn);
    }

    // Emit entry as a top-level expression (IIFE so `return` works
    // and await / yield patterns don't leak).
    if (entryFn != null) {
      _out.writeln('(function main() {');
      _depth++;
      if (entryFn.hasBody()) _emitStatementOrExpression(entryFn.body);
      _depth--;
      _out.writeln('})();');
    }

    return _out.toString();
  }

  /// Structural compile — the Phase 2+ path.
  ///
  /// Builds a [TsEmitPlan] (imports, functions, classes, enums) by
  /// walking the program, then serializes it through the ts-morph Node
  /// helper (`dart/compiler/tool/ts_emit.mjs`). Returns the finished
  /// TS source, including formatting and proper indentation.
  ///
  /// Requires `dart/compiler/tool/node_modules` (one-time `npm install`
  /// in that directory).
  ///
  /// Feature coverage grows incrementally per the Phase 2 plan:
  /// classes (2.1), native async (2.2), generics (2.3), pattern matching
  /// + records (2.4). Until complete, any constructs not yet modeled
  /// fall through to a raw-text escape hatch.
  Future<String> compileStructural() async {
    final plan = buildEmitPlan();
    return runTsEmitAsync(plan);
  }

  /// Build a [TsEmitPlan] for the program. Exposed for tests and for
  /// tools that want to inspect the structure before emission.
  TsEmitPlan buildEmitPlan() {
    final statements = <TsStatement>[];

    // Find the entry module + entry function.
    Module? entryMod;
    FunctionDefinition? entryFn;
    for (final m in program.modules) {
      if (m.name == program.entryModule) {
        entryMod = m;
        for (final f in m.functions) {
          if (f.name == program.entryFunction) entryFn = f;
        }
      }
    }
    if (entryMod == null) {
      throw StateError('Entry module "${program.entryModule}" not found');
    }

    // Group functions by their enclosing class, if any. A function is a
    // class member when its name matches `<typeDef.name>.<memberName>`;
    // otherwise it is a free top-level function.
    final classMembers = <String, List<FunctionDefinition>>{};
    final freeFunctions = <FunctionDefinition>[];
    final typeDefByName = <String, TypeDefinition>{
      for (final td in entryMod.typeDefs) td.name: td,
    };
    for (final fn in entryMod.functions) {
      if (fn.isBase) continue;
      if (fn.name == program.entryFunction) continue;
      final enclosing = _enclosingTypeName(fn.name, typeDefByName);
      if (enclosing != null) {
        classMembers.putIfAbsent(enclosing, () => <FunctionDefinition>[]).add(fn);
      } else {
        freeFunctions.add(fn);
      }
    }

    // Classes first so they are declared before any top-level code that
    // constructs them.
    for (final td in entryMod.typeDefs) {
      final members = classMembers[td.name] ?? const <FunctionDefinition>[];
      statements.add(_buildClassStatement(td, members));
    }

    // Top-level user functions.
    for (final fn in freeFunctions) {
      statements.add(_buildFunctionStatement(fn));
    }

    // Entry function, emitted as `main` with an immediate call at end.
    if (entryFn != null) {
      statements.add(_buildFunctionStatement(entryFn, forceName: 'main'));
      statements.add(TsRaw('main();'));
    }

    return TsEmitPlan(
      path: '${program.name.isNotEmpty ? program.name : "program"}.ts',
      statements: statements,
    );
  }

  /// Returns the enclosing type name of a function, or null if the
  /// function is not a class member. Handles the Ball naming convention
  /// `<typeDef.name>.<memberName>` (where `typeDef.name` is typically
  /// `<module>:<ClassName>`).
  String? _enclosingTypeName(
    String fnName,
    Map<String, TypeDefinition> typeDefByName,
  ) {
    // Check every registered type; longest match wins so nested names
    // (e.g. Outer.Inner) resolve to Inner.
    String? best;
    for (final name in typeDefByName.keys) {
      if (fnName.startsWith('$name.') &&
          (best == null || name.length > best.length)) {
        best = name;
      }
    }
    return best;
  }

  /// Build a [TsFunction] structure for a Ball function. The body is
  /// captured as a raw TS source string via [_captureInto] — ts-morph
  /// re-indents and formats it inside the function block.
  TsFunction _buildFunctionStatement(
    FunctionDefinition fn, {
    String? forceName,
  }) {
    final params = _extractParams(fn);
    final name = forceName ?? _sanitize(fn.name);
    final body = _captureInto(() {
      // Legacy alias: some Ball programs reference `input` by name.
      if (params.length == 1 && params.first != 'input') {
        _out.writeln('const input = ${_sanitize(params.first)};');
      }
      if (fn.hasBody()) {
        _emitStatementOrExpression(fn.body, isFunctionBody: true);
      }
    });
    final isAsync = _functionIsAsync(fn);
    return TsFunction(
      name: name,
      isAsync: isAsync,
      parameters: params
          .map((p) => TsParameter(name: _sanitize(p), type: 'any'))
          .toList(),
      returnType: isAsync ? 'Promise<any>' : 'any',
      body: body,
    );
  }

  /// Infer whether a function is `async`. Looks at the metadata key
  /// `is_async` emitted by the Dart encoder.
  bool _functionIsAsync(FunctionDefinition fn) {
    if (!fn.hasMetadata()) return false;
    final flag = fn.metadata.fields['is_async'];
    return flag != null && flag.hasBoolValue() && flag.boolValue;
  }

  /// Set while emitting a method / ctor / accessor body; bare references
  /// whose names appear here (and are not shadowed by a parameter / local)
  /// are prefixed with `this.`.
  Set<String> _currentClassFields = const <String>{};

  /// Parameters of the currently-emitting method. Tracked so a parameter
  /// named the same as a class field shadows the field (matches Dart and
  /// TS lexical scoping).
  Set<String> _currentMethodParams = const <String>{};

  /// Build a TsClass for a typeDef. Fields come from descriptor +
  /// metadata; ctors/methods/getters/setters come from [members].
  TsClass _buildClassStatement(
    TypeDefinition td,
    List<FunctionDefinition> members,
  ) {
    final meta = _structToMap(td.metadata);
    final tsName = _classTsName(td.name);

    // Fields: prefer metadata.fields (richer: is_final, is_static, type)
    // but fall back to descriptor.field for simple data classes.
    final fieldSpecs = (meta['fields'] as List?)?.cast<Object>() ?? const [];
    final properties = <TsProperty>[];
    final fieldNames = <String>{};
    for (final raw in fieldSpecs) {
      if (raw is! Map) continue;
      final name = raw['name'] as String?;
      if (name == null) continue;
      fieldNames.add(name);
      properties.add(
        TsProperty(
          name: name,
          type: (raw['type'] as String?) != null
              ? _dartTypeToTs(raw['type'] as String)
              : 'any',
          isStatic: raw['is_static'] == true,
          isReadonly: raw['is_final'] == true,
        ),
      );
    }
    // Fallback: use descriptor fields if metadata didn't supply any.
    if (properties.isEmpty) {
      for (final f in td.descriptor.field) {
        fieldNames.add(f.name);
        properties.add(TsProperty(name: f.name, type: 'any'));
      }
    }

    final ctors = <TsCtor>[];
    final methods = <TsMethod>[];
    final getters = <TsGetter>[];
    final setters = <TsSetter>[];

    for (final fn in members) {
      final mMeta = fn.hasMetadata()
          ? _structToMap(fn.metadata)
          : const <String, Object?>{};
      final kind = mMeta['kind'] as String? ?? 'method';
      if (kind == 'constructor') {
        ctors.add(_buildCtor(fn, mMeta, fieldNames));
      } else if (mMeta['is_getter'] == true) {
        getters.add(_buildGetter(fn, mMeta, fieldNames));
      } else if (mMeta['is_setter'] == true) {
        setters.add(_buildSetter(fn, mMeta, fieldNames));
      } else if (kind == 'static_field') {
        // Skip — static fields end up as class properties via metadata.
        // Not yet modeled; falls through to the raw escape hatch.
      } else {
        methods.add(_buildMethod(fn, mMeta, fieldNames));
      }
    }

    // Inheritance.
    final superName = meta['superclass'] as String?;
    final interfaces = (meta['interfaces'] as List?)?.cast<String>();
    // Exception is a special case: Dart uses `implements Exception` as a
    // convention but TS has no Exception type. Drop it.
    final tsInterfaces = interfaces
        ?.where((i) => i != 'Exception')
        .map((i) => _dartTypeToTs(i))
        .toList();

    return TsClass(
      name: tsName,
      isExported: true,
      isAbstract: meta['is_abstract'] == true,
      extendsClause: superName != null ? _dartTypeToTs(superName) : null,
      implementsClause: tsInterfaces ?? const <String>[],
      properties: properties,
      ctors: ctors,
      methods: methods,
      getters: getters,
      setters: setters,
    );
  }

  TsCtor _buildCtor(
    FunctionDefinition fn,
    Map<String, Object?> meta,
    Set<String> classFields,
  ) {
    final rawParams = _extractCtorParams(meta);
    // Build parameter list + prologue body that assigns `this.<name> =
    // <name>` for any parameter with `is_this` true (Dart initializing
    // formals).
    final parameters = <TsParameter>[];
    final prologue = StringBuffer();
    for (final p in rawParams) {
      parameters.add(TsParameter(name: _sanitize(p.name), type: 'any'));
      if (p.isThis) {
        prologue.writeln('this.${p.name} = ${_sanitize(p.name)};');
      }
    }
    final captured = _withMethodContext(
      params: rawParams.map((p) => p.name).toSet(),
      fields: classFields,
      run: () => _captureInto(() {
        if (fn.hasBody()) {
          _emitStatementOrExpression(fn.body, isFunctionBody: false);
        }
      }),
    );
    final body =
        prologue.isEmpty ? captured : '${prologue.toString().trimRight()}\n$captured'.trimRight();
    return TsCtor(parameters: parameters, body: body);
  }

  TsMethod _buildMethod(
    FunctionDefinition fn,
    Map<String, Object?> meta,
    Set<String> classFields,
  ) {
    final params = _extractParams(fn);
    final body = _withMethodContext(
      params: params.toSet(),
      fields: classFields,
      run: () => _captureInto(() {
        if (params.length == 1 && params.first != 'input') {
          _out.writeln('const input = ${_sanitize(params.first)};');
        }
        if (fn.hasBody()) {
          _emitStatementOrExpression(fn.body, isFunctionBody: true);
        }
      }),
    );
    final methodName = _memberName(fn.name);
    final isAsync = _functionIsAsync(fn);
    return TsMethod(
      name: methodName,
      isAsync: isAsync,
      isStatic: meta['is_static'] == true,
      parameters: params
          .map((p) => TsParameter(name: _sanitize(p), type: 'any'))
          .toList(),
      returnType: isAsync ? 'Promise<any>' : 'any',
      body: body,
    );
  }

  TsGetter _buildGetter(
    FunctionDefinition fn,
    Map<String, Object?> meta,
    Set<String> classFields,
  ) {
    final body = _withMethodContext(
      params: const <String>{},
      fields: classFields,
      run: () => _captureInto(() {
        if (fn.hasBody()) {
          _emitStatementOrExpression(fn.body, isFunctionBody: true);
        }
      }),
    );
    return TsGetter(
      name: _memberName(fn.name),
      isStatic: meta['is_static'] == true,
      returnType: 'any',
      body: body,
    );
  }

  TsSetter _buildSetter(
    FunctionDefinition fn,
    Map<String, Object?> meta,
    Set<String> classFields,
  ) {
    final params = _extractParams(fn);
    final body = _withMethodContext(
      params: params.toSet(),
      fields: classFields,
      run: () => _captureInto(() {
        if (fn.hasBody()) {
          _emitStatementOrExpression(fn.body, isFunctionBody: false);
        }
      }),
    );
    return TsSetter(
      name: _memberName(fn.name),
      isStatic: meta['is_static'] == true,
      parameters: params
          .map((p) => TsParameter(name: _sanitize(p), type: 'any'))
          .toList(),
      body: body,
    );
  }

  /// Runs [run] with class-member context set; [_currentClassFields]
  /// and [_currentMethodParams] are swapped in and out, so
  /// [_expr] can decide whether to emit `this.<name>`.
  T _withMethodContext<T>({
    required Set<String> params,
    required Set<String> fields,
    required T Function() run,
  }) {
    final savedParams = _currentMethodParams;
    final savedFields = _currentClassFields;
    _currentMethodParams = params;
    _currentClassFields = fields;
    try {
      return run();
    } finally {
      _currentMethodParams = savedParams;
      _currentClassFields = savedFields;
    }
  }

  /// Extract the short member name from a qualified Ball function name
  /// (`main:Point.distanceSquared` → `distanceSquared`). Constructors
  /// named `.new` become just 'constructor' (placeholder — not used
  /// since ctors route through [_buildCtor]).
  String _memberName(String qualified) {
    final dot = qualified.lastIndexOf('.');
    if (dot < 0) return _sanitize(qualified);
    return _sanitize(qualified.substring(dot + 1));
  }

  /// Produce a TypeScript-friendly class name from a qualified Ball
  /// type name. `main:Point` → `Point`; `main:_Foo` → `_Foo`.
  String _classTsName(String qualified) {
    final colon = qualified.lastIndexOf(':');
    final bare = colon < 0 ? qualified : qualified.substring(colon + 1);
    return bare;
  }

  /// Hand-rolled Struct → Map decoder. structpb wraps every value, so
  /// we unwrap the common scalar kinds and recurse for lists/structs.
  Map<String, Object?> _structToMap(structpb.Struct s) {
    final out = <String, Object?>{};
    s.fields.forEach((k, v) => out[k] = _unwrapStructValue(v));
    return out;
  }

  Object? _unwrapStructValue(structpb.Value v) {
    if (v.hasNullValue()) return null;
    if (v.hasBoolValue()) return v.boolValue;
    if (v.hasNumberValue()) {
      final n = v.numberValue;
      if (n == n.truncateToDouble()) return n.toInt();
      return n;
    }
    if (v.hasStringValue()) return v.stringValue;
    if (v.hasListValue()) {
      return v.listValue.values.map(_unwrapStructValue).toList();
    }
    if (v.hasStructValue()) {
      return _structToMap(v.structValue);
    }
    return null;
  }

  List<_CtorParam> _extractCtorParams(Map<String, Object?> meta) {
    final raw = (meta['params'] as List?)?.cast<Object>() ?? const [];
    final params = <_CtorParam>[];
    for (final r in raw) {
      if (r is! Map) continue;
      final name = r['name'] as String?;
      if (name == null) continue;
      params.add(_CtorParam(name: name, isThis: r['is_this'] == true));
    }
    return params;
  }

  /// Very small Dart → TS type mapper. Covers the scalar + generic
  /// types that show up in engine.dart metadata; anything unknown
  /// falls through to `any`.
  String _dartTypeToTs(String dart) {
    final t = dart.trim();
    if (t.isEmpty) return 'any';
    // Drop null suffixes for now — TS handles `| null` separately and
    // Phase 2 doesn't need nullability precision for self-host.
    final nonNull = t.endsWith('?') ? t.substring(0, t.length - 1) : t;
    switch (nonNull) {
      case 'int':
      case 'double':
      case 'num':
        return 'number';
      case 'bool':
        return 'boolean';
      case 'String':
        return 'string';
      case 'void':
        return 'void';
      case 'dynamic':
      case 'Object':
        return 'any';
    }
    // Strip leading `main:` so generated TS uses the bare class name.
    if (nonNull.startsWith('main:')) return nonNull.substring(5);
    return nonNull;
  }

  // ─────────────────────────── Functions ───────────────────────────

  void _emitFunction(FunctionDefinition fn) {
    final params = _extractParams(fn);
    final paramList = params.map((p) => _sanitize(p)).join(', ');
    _out.writeln('${_ind}function ${_sanitize(fn.name)}($paramList): any {');
    _depth++;

    // Legacy alias: some Ball programs reference `input` in the body.
    if (params.length == 1 && params.first != 'input') {
      _out.writeln('${_ind}const input = ${_sanitize(params.first)};');
    }

    if (fn.hasBody()) {
      _emitStatementOrExpression(fn.body, isFunctionBody: true);
    }
    _depth--;
    _out.writeln('${_ind}}');
    _out.writeln();
  }

  /// Emit an Expression as a statement when possible; falls back to
  /// wrapping bare expressions as expression-statements.
  void _emitStatementOrExpression(Expression expr,
      {bool isFunctionBody = false}) {
    // Function body is a bare expression (Dart `int f() => x + 1;`).
    // Emit a `return` so the value flows out. `_expr` picks the
    // ternary form for `if`, IIFE form for `block` / `try`, etc., so
    // this one line handles all expression-body kinds uniformly.
    if (isFunctionBody &&
        expr.whichExpr() != Expression_Expr.block) {
      _out.writeln('${_ind}return ${_expr(expr)};');
      return;
    }
    if (expr.whichExpr() == Expression_Expr.block) {
      _emitBlock(expr.block, isFunctionBody: isFunctionBody);
      return;
    }
    if (expr.whichExpr() == Expression_Expr.call && _isControlFlow(expr.call)) {
      _emitControlFlowStatement(expr.call);
      return;
    }
    _out.writeln('$_ind${_expr(expr)};');
  }

  void _emitBlock(Block block, {bool isFunctionBody = false}) {
    for (final stmt in block.statements) {
      _emitStatement(stmt);
    }
    if (block.hasResult() && isFunctionBody) {
      final r = block.result;
      if (r.whichExpr() == Expression_Expr.literal &&
          r.literal.whichValue() == Literal_Value.notSet) {
        // No value — skip.
      } else {
        _out.writeln('${_ind}return ${_expr(r)};');
      }
    } else if (block.hasResult()) {
      _out.writeln('$_ind${_expr(block.result)};');
    }
  }

  void _emitStatement(Statement stmt) {
    if (stmt.hasLet()) {
      final meta = _structMap(stmt.let.metadata);
      final keyword = meta['keyword'] as String? ?? 'final';
      final kw = (keyword == 'var') ? 'let' : 'const';
      final name = _sanitize(stmt.let.name);
      if (stmt.let.hasValue()) {
        _out.writeln('$_ind$kw $name = ${_expr(stmt.let.value)};');
      } else {
        _out.writeln('$_ind$kw $name;');
      }
      return;
    }
    if (stmt.hasExpression()) {
      final e = stmt.expression;
      if (e.whichExpr() == Expression_Expr.call && _isControlFlow(e.call)) {
        _emitControlFlowStatement(e.call);
        return;
      }
      _out.writeln('$_ind${_expr(e)};');
    }
  }

  // ──────────────────────── Control flow statements ────────────────

  bool _isControlFlow(FunctionCall call) {
    if (!_isStd(call.module)) return false;
    const kinds = {
      'if', 'for', 'for_in', 'while', 'do_while', 'try',
      'return', 'break', 'continue', 'labeled', 'throw', 'rethrow',
      'assign',
    };
    return kinds.contains(call.function);
  }

  bool _isStd(String module) => module == 'std' || module == 'dart_std';

  void _emitControlFlowStatement(FunctionCall call) {
    switch (call.function) {
      case 'if':
        _emitIfStmt(call);
        break;
      case 'for':
        _emitForStmt(call);
        break;
      case 'for_in':
        _emitForInStmt(call);
        break;
      case 'while':
        _emitWhileStmt(call);
        break;
      case 'do_while':
        _emitDoWhileStmt(call);
        break;
      case 'try':
        _emitTryStmt(call);
        break;
      case 'return':
        {
          final v = _field(call, 'value');
          if (v != null) {
            _out.writeln('${_ind}return ${_expr(v)};');
          } else {
            _out.writeln('${_ind}return;');
          }
          break;
        }
      case 'break':
        {
          final label = _stringField(call, 'label');
          _out.writeln(label != null && label.isNotEmpty
              ? '${_ind}break $label;'
              : '${_ind}break;');
          break;
        }
      case 'continue':
        {
          final label = _stringField(call, 'label');
          _out.writeln(label != null && label.isNotEmpty
              ? '${_ind}continue $label;'
              : '${_ind}continue;');
          break;
        }
      case 'labeled':
        {
          final label = _stringField(call, 'label');
          _out.writeln('$_ind$label:');
          final body = _field(call, 'body');
          if (body != null) _emitStatementOrExpression(body);
          break;
        }
      case 'throw':
        {
          final v = _field(call, 'value');
          if (v != null) {
            final str = _compileThrowValue(v) ?? _expr(v);
            _out.writeln('${_ind}throw $str;');
          } else {
            _out.writeln('${_ind}throw null;');
          }
          break;
        }
      case 'rethrow':
        // Re-raise via a sentinel: the catch binds the raw error to a
        // symbol, which we re-throw here. JS/TS don't have bare
        // `throw;`, so we rely on the catch clause using the bound
        // variable directly and re-throwing it explicitly.
        _out.writeln('${_ind}throw __ball_active_error;');
        break;
      case 'assign':
        _emitAssignStmt(call);
        break;
    }
  }

  void _emitIfStmt(FunctionCall call) {
    final cond = _field(call, 'condition');
    final then_ = _field(call, 'then');
    final else_ = _field(call, 'else');
    _out.writeln('${_ind}if (${_expr(cond!)}) {');
    _depth++;
    if (then_ != null) _emitStatementOrExpression(then_);
    _depth--;
    if (else_ != null) {
      _out.writeln('$_ind} else {');
      _depth++;
      _emitStatementOrExpression(else_);
      _depth--;
    }
    _out.writeln('$_ind}');
  }

  void _emitForStmt(FunctionCall call) {
    final init = _field(call, 'init');
    final cond = _field(call, 'condition');
    final update = _field(call, 'update');
    final body = _field(call, 'body');

    String initStr;
    if (init != null &&
        init.whichExpr() == Expression_Expr.literal &&
        init.literal.whichValue() == Literal_Value.stringValue) {
      // Legacy: encoder emits `init` as the source string `"var i = 0"`.
      // Translate to JS `let i = 0`.
      initStr = _translateInitString(init.literal.stringValue);
    } else if (init != null) {
      initStr = _expr(init);
    } else {
      initStr = '';
    }
    final condStr = cond != null ? _expr(cond) : '';
    final updateStr = update != null ? _expr(update) : '';
    _out.writeln('${_ind}for ($initStr; $condStr; $updateStr) {');
    _depth++;
    if (body != null) _emitStatementOrExpression(body);
    _depth--;
    _out.writeln('$_ind}');
  }

  String _translateInitString(String raw) {
    // Same logic as the C++ compiler's translation — strip the
    // leading keyword (var/final/int/double/String/bool/num) and
    // prepend `let`.
    for (final kw in const ['var', 'final', 'int', 'double', 'String',
                            'bool', 'num']) {
      if (raw.length > kw.length + 1 &&
          raw.substring(0, kw.length) == kw &&
          raw[kw.length] == ' ') {
        return 'let ${raw.substring(kw.length + 1)}';
      }
    }
    return 'let $raw';
  }

  void _emitForInStmt(FunctionCall call) {
    final variable = _stringField(call, 'variable') ?? 'item';
    final iterable = _field(call, 'iterable')!;
    final body = _field(call, 'body');
    _out.writeln('${_ind}for (const $variable of ${_expr(iterable)}) {');
    _depth++;
    if (body != null) _emitStatementOrExpression(body);
    _depth--;
    _out.writeln('$_ind}');
  }

  void _emitWhileStmt(FunctionCall call) {
    final cond = _field(call, 'condition');
    final body = _field(call, 'body');
    _out.writeln('${_ind}while (${_expr(cond!)}) {');
    _depth++;
    if (body != null) _emitStatementOrExpression(body);
    _depth--;
    _out.writeln('$_ind}');
  }

  void _emitDoWhileStmt(FunctionCall call) {
    final cond = _field(call, 'condition');
    final body = _field(call, 'body');
    _out.writeln('${_ind}do {');
    _depth++;
    if (body != null) _emitStatementOrExpression(body);
    _depth--;
    _out.writeln('$_ind} while (${_expr(cond!)});');
  }

  void _emitTryStmt(FunctionCall call) {
    final body = _field(call, 'body');
    final catches = _field(call, 'catches');
    final fin = _field(call, 'finally');

    _out.writeln('${_ind}try {');
    _depth++;
    if (body != null) _emitStatementOrExpression(body);
    _depth--;

    // JS/TS has only one catch clause. Collapse all catches into a
    // single `catch (e)` with if-else on the thrown value's shape.
    _out.writeln('$_ind} catch (__ball_active_error) {');
    _depth++;
    if (catches != null &&
        catches.whichExpr() == Expression_Expr.literal &&
        catches.literal.whichValue() == Literal_Value.listValue) {
      final clauses = catches.literal.listValue.elements;
      bool first = true;
      Expression? untypedBody;
      String untypedVar = 'e';
      for (final ce in clauses) {
        if (ce.whichExpr() != Expression_Expr.messageCreation) continue;
        final cf = _fieldMap(ce.messageCreation.fields);
        final type = _stringFieldVal(cf, 'type');
        final variable = _stringFieldVal(cf, 'variable') ?? 'e';
        final cbody = cf['body'];
        if (type == null || type.isEmpty) {
          untypedBody = cbody;
          untypedVar = variable;
          continue;
        }
        // Typed catch.
        final cond = _typedCatchCondition(type);
        final keyword = first ? 'if' : 'else if';
        _out.writeln('$_ind$keyword ($cond) {');
        _depth++;
        _out.writeln('${_ind}const $variable = __ball_active_error;');
        _catchVars.add(variable);
        if (cbody != null) _emitStatementOrExpression(cbody);
        _catchVars.remove(variable);
        _depth--;
        _out.writeln('$_ind}');
        first = false;
      }
      // Fallback (untyped catch, or rethrow if none).
      if (!first) _out.writeln('${_ind}else {');
      if (!first) _depth++;
      if (untypedBody != null) {
        _out.writeln('${_ind}const $untypedVar = __ball_active_error;');
        _catchVars.add(untypedVar);
        _emitStatementOrExpression(untypedBody);
        _catchVars.remove(untypedVar);
      } else {
        _out.writeln('${_ind}throw __ball_active_error;');
      }
      if (!first) {
        _depth--;
        _out.writeln('$_ind}');
      }
    } else {
      _out.writeln('${_ind}throw __ball_active_error;');
    }
    _depth--;

    if (fin != null) {
      _out.writeln('$_ind} finally {');
      _depth++;
      _emitStatementOrExpression(fin);
      _depth--;
    }
    _out.writeln('$_ind}');
  }

  String _typedCatchCondition(String type) {
    // Real JS built-in error classes.
    const builtins = {
      'Error', 'TypeError', 'RangeError', 'SyntaxError',
      'ReferenceError', 'URIError', 'EvalError',
    };
    if (builtins.contains(type)) {
      return '__ball_active_error instanceof $type';
    }
    // Dart-style error classes map to JS equivalents where applicable.
    if (type == 'FormatException') {
      // Our string_to_int / string_to_double shim throws a plain
      // Error whose message starts with "FormatException:". Match on
      // that instead of `instanceof FormatException` (no such class).
      return "(__ball_active_error instanceof Error && "
          "__ball_active_error.message.startsWith('FormatException'))";
    }
    // Ball-tag throws: thrown values are objects with a `__type` field.
    return "(typeof __ball_active_error === 'object' && "
        "__ball_active_error !== null && "
        "__ball_active_error['__type'] === '$type')";
  }

  void _emitAssignStmt(FunctionCall call) {
    final target = _field(call, 'target');
    final value = _field(call, 'value');
    if (target == null || value == null) return;
    final op = _stringField(call, 'op');
    final opStr = (op != null && op.isNotEmpty) ? op : '=';
    _out.writeln('$_ind${_expr(target)} $opStr ${_expr(value)};');
  }

  // ─────────────────────────── Expressions ─────────────────────────

  String _expr(Expression expr) {
    switch (expr.whichExpr()) {
      case Expression_Expr.call:
        return _compileCall(expr.call);
      case Expression_Expr.literal:
        return _compileLiteral(expr.literal);
      case Expression_Expr.reference:
        final refName = expr.reference.name;
        // Inside a method body, a bare reference to a class field
        // (not shadowed by a parameter) is implicit `this.<name>` in
        // Dart. TS has no such implicit resolution, so emit it
        // explicitly.
        if (_currentClassFields.contains(refName) &&
            !_currentMethodParams.contains(refName)) {
          return 'this.${_sanitize(refName)}';
        }
        return _sanitize(refName);
      case Expression_Expr.fieldAccess:
        return _compileFieldAccess(expr.fieldAccess);
      case Expression_Expr.messageCreation:
        return _compileMessageCreation(expr.messageCreation);
      case Expression_Expr.block:
        return _compileBlockExpression(expr.block);
      case Expression_Expr.lambda:
        return _compileLambda(expr.lambda);
      case Expression_Expr.notSet:
        return 'null /* notSet */';
    }
  }

  String _compileLiteral(Literal lit) {
    switch (lit.whichValue()) {
      case Literal_Value.intValue:
        return lit.intValue.toString();
      case Literal_Value.doubleValue:
        return lit.doubleValue.toString();
      case Literal_Value.stringValue:
        return _jsStringLiteral(lit.stringValue);
      case Literal_Value.boolValue:
        return lit.boolValue ? 'true' : 'false';
      case Literal_Value.listValue:
        final parts = lit.listValue.elements.map(_expr).toList();
        return '[${parts.join(', ')}]';
      case Literal_Value.bytesValue:
        return '/* bytes */ new Uint8Array()';
      case Literal_Value.notSet:
        return 'null';
    }
  }

  String _jsStringLiteral(String s) {
    final buf = StringBuffer("'");
    for (final cu in s.codeUnits) {
      if (cu == 0x27) {
        buf.write(r"\'");
      } else if (cu == 0x5C) {
        buf.write(r'\\');
      } else if (cu == 0x0A) {
        buf.write(r'\n');
      } else if (cu == 0x0D) {
        buf.write(r'\r');
      } else if (cu == 0x09) {
        buf.write(r'\t');
      } else if (cu >= 0x20 && cu < 0x7F) {
        buf.writeCharCode(cu);
      } else {
        buf.write('\\u${cu.toRadixString(16).padLeft(4, '0')}');
      }
    }
    buf.write("'");
    return buf.toString();
  }

  String _compileFieldAccess(FieldAccess fa) {
    final obj = _expr(fa.object);
    final field = fa.field_2;
    // `.length` on a string or array is a property in JS.
    if (field == 'length') return '$obj.length';
    // Catch-bound vars are (map-shaped) thrown values: bracket lookup.
    if (fa.object.whichExpr() == Expression_Expr.reference &&
        _catchVars.contains(fa.object.reference.name)) {
      return "$obj['$field']";
    }
    return '$obj.$field';
  }

  String _compileMessageCreation(MessageCreation msg) {
    // Empty type name → render as an inline object literal (throw
    // values, ad-hoc arg packs).
    if (msg.typeName.isEmpty) {
      final entries = msg.fields
          .map((f) => "'${f.name}': ${_expr(f.value)}")
          .join(', ');
      return '{$entries}';
    }
    // Named type → a class constructor invocation. The encoder emits
    // positional arguments as `arg0`, `arg1`, ...; named parameters
    // keep their Dart names. Re-order by Ball field name → `arg0`
    // first to preserve positional order.
    if (_typeIsUserDefinedClass(msg.typeName)) {
      final positional = <String>[];
      final named = <String, String>{};
      for (final f in msg.fields) {
        final argMatch = RegExp(r'^arg(\d+)$').firstMatch(f.name);
        if (argMatch != null) {
          positional.add(_expr(f.value));
        } else {
          named[f.name] = _expr(f.value);
        }
      }
      final allArgs = [
        ...positional,
        if (named.isNotEmpty)
          '{ ${named.entries.map((e) => "${e.key}: ${e.value}").join(", ")} }',
      ].join(', ');
      return 'new ${_classTsName(msg.typeName)}($allArgs)';
    }
    // Protobuf messages and other external types: fall back to a
    // tagged object literal for now.
    final entries = [
      "'__type': '${msg.typeName}'",
      ...msg.fields.map((f) => "'${f.name}': ${_expr(f.value)}"),
    ].join(', ');
    return '{$entries}';
  }

  /// Whether [typeName] is a user-defined class declared in the
  /// current program's entry module (qualified form `main:Foo`).
  bool _typeIsUserDefinedClass(String typeName) {
    if (typeName.isEmpty) return false;
    for (final m in program.modules) {
      if (m.name != program.entryModule) continue;
      for (final td in m.typeDefs) {
        if (td.name == typeName) return true;
      }
    }
    return false;
  }

  String _compileBlockExpression(Block block) {
    // Immediately-invoked arrow function with return.
    final saved = _out.toString();
    _out.clear();
    final savedDepth = _depth;
    _depth = 1;
    _out.writeln('(() => {');
    for (final stmt in block.statements) {
      _emitStatement(stmt);
    }
    if (block.hasResult()) {
      _out.writeln('${_ind}return ${_expr(block.result)};');
    }
    _out.write('})()');
    final body = _out.toString();
    _out.clear();
    _out.write(saved);
    _depth = savedDepth;
    return body;
  }

  String _compileLambda(FunctionDefinition fn) {
    final params = _extractParams(fn);
    final paramList = params.map(_sanitize).join(', ');
    final savedDepth = _depth;
    final saved = _out.toString();
    _out.clear();
    _depth = 1;
    _out.writeln('(($paramList) => {');
    if (params.length == 1 && params.first != 'input') {
      _out.writeln('${_ind}const input = ${_sanitize(params.first)};');
    }
    if (fn.hasBody()) {
      _emitStatementOrExpression(fn.body, isFunctionBody: true);
    }
    _out.write('})');
    final body = _out.toString();
    _out.clear();
    _out.write(saved);
    _depth = savedDepth;
    return body;
  }

  // ─────────────────────────── Calls ───────────────────────────────

  String _compileCall(FunctionCall call) {
    // Known std built-ins with empty module (encoder sometimes omits
    // `module: 'std'` for these). Everything else with empty module is
    // a user-defined call.
    const emptyModuleStd = {
      'labeled', 'paren', 'switch_expr', 'set_create', 'map_create',
      'yield_each', 'rethrow', 'assert',
    };
    if (_isStd(call.module) ||
        (call.module.isEmpty && emptyModuleStd.contains(call.function))) {
      return _compileStdCall(call);
    }
    // User-defined call. Input is a messageCreation whose field values
    // are flattened to positional args. Matches the Dart/C++ compiler
    // strategy.
    final fn = _sanitize(call.function);
    if (!call.hasInput()) return '$fn()';
    final input = call.input;
    if (input.whichExpr() == Expression_Expr.messageCreation) {
      final fields = input.messageCreation.fields;
      // Method call convention: first field named `self` is the receiver.
      // Emit as `<self>.<method>(<other-args>)`.
      final selfField = fields.where((f) => f.name == 'self').firstOrNull;
      if (selfField != null) {
        final selfStr = _expr(selfField.value);
        final otherArgs = fields
            .where((f) => f.name != 'self' && f.name != '__type_args__')
            .map((f) => _expr(f.value))
            .join(', ');
        return otherArgs.isEmpty
            ? '$selfStr.$fn()'
            : '$selfStr.$fn($otherArgs)';
      }
      final args = fields.map((f) => _expr(f.value)).join(', ');
      return '$fn($args)';
    }
    return '$fn(${_expr(input)})';
  }

  String _compileStdCall(FunctionCall call) {
    final fn = call.function;
    final f = call.hasInput() &&
            call.input.whichExpr() == Expression_Expr.messageCreation
        ? _fieldMap(call.input.messageCreation.fields)
        : <String, Expression>{};

    String bin(String op) {
      final l = f['left']!;
      final r = f['right']!;
      return '(${_expr(l)} $op ${_expr(r)})';
    }

    String un(String op) {
      final v = f['value']!;
      final inner = _expr(v);
      // Stacked unary minus → add parens.
      if (op == '-' && inner.startsWith('-')) return '-($inner)';
      return '$op$inner';
    }

    switch (fn) {
      // Arithmetic
      case 'add':          return bin('+');
      case 'subtract':     return bin('-');
      case 'multiply':     return bin('*');
      // Dart `~/` (integer division): truncate toward zero.
      case 'divide':
        return 'Math.trunc(${_expr(f['left']!)} / ${_expr(f['right']!)})';
      case 'divide_double': return bin('/');
      case 'modulo':       return bin('%');
      case 'negate':       return un('-');
      // Comparison
      case 'equals':       return bin('===');
      case 'not_equals':   return bin('!==');
      case 'less_than':    return bin('<');
      case 'greater_than': return bin('>');
      case 'lte':          return bin('<=');
      case 'gte':          return bin('>=');
      // Logical
      case 'and':          return bin('&&');
      case 'or':           return bin('||');
      case 'not':          return un('!');
      // Bitwise (note: JS bitwise ops force 32-bit; matches Dart in this range)
      case 'bitwise_and':  return bin('&');
      case 'bitwise_or':   return bin('|');
      case 'bitwise_xor':  return bin('^');
      case 'bitwise_not':  return un('~');
      case 'left_shift':   return bin('<<');
      case 'right_shift':  return bin('>>');
      case 'unsigned_right_shift': return bin('>>>');
      // Integer division: Dart `~/` = truncate toward zero.
      case 'integer_divide':
        return 'Math.trunc(${_expr(f['left']!)} / ${_expr(f['right']!)})';
      // Concat (strings and numbers coerced).
      case 'concat':       return bin('+');
      // to_string: mirror Dart's output conventions.
      case 'to_string':
        return '__ball_to_string(${_expr(f['value']!)})';
      case 'int_to_string':
        return 'String(${_expr(f['value']!)})';
      case 'double_to_string':
        return '__ball_double_to_string(${_expr(f['value']!)})';
      case 'string_to_int':
        return '__ball_parse_int(${_expr(f['value']!)})';
      case 'string_to_double':
        return '__ball_parse_double(${_expr(f['value']!)})';
      // String ops
      case 'string_length':
        return '${_expr(f['value']!)}.length';
      case 'string_to_upper':
        return '${_wrapIfNeeded(f['value']!)}.toUpperCase()';
      case 'string_to_lower':
        return '${_wrapIfNeeded(f['value']!)}.toLowerCase()';
      case 'string_trim':
        return '${_wrapIfNeeded(f['value']!)}.trim()';
      case 'string_trim_start':
        return '${_wrapIfNeeded(f['value']!)}.trimStart()';
      case 'string_trim_end':
        return '${_wrapIfNeeded(f['value']!)}.trimEnd()';
      case 'string_contains':
        return '${_expr(f['left']!)}.includes(${_expr(f['right']!)})';
      case 'string_starts_with':
        return '${_expr(f['left']!)}.startsWith(${_expr(f['right']!)})';
      case 'string_ends_with':
        return '${_expr(f['left']!)}.endsWith(${_expr(f['right']!)})';
      case 'string_is_empty':
        return '(${_expr(f['value']!)}.length === 0)';
      case 'string_split':
        return '${_expr(f['value']!)}.split(${_expr(f['separator']!)})';
      case 'string_substring':
        {
          final v = _expr(f['value']!);
          final s = _expr(f['start']!);
          if (f['end'] != null) {
            return '$v.substring($s, ${_expr(f['end']!)})';
          }
          return '$v.substring($s)';
        }
      case 'string_interpolation':
        {
          final parts = f['parts'];
          if (parts != null &&
              parts.whichExpr() == Expression_Expr.literal &&
              parts.literal.whichValue() == Literal_Value.listValue) {
            final pieces = parts.literal.listValue.elements
                .map((p) => '(${_expr(p)})')
                .join(' + ');
            return '($pieces)';
          }
          return "''";
        }
      // Math
      case 'math_abs':     return 'Math.abs(${_expr(f['value']!)})';
      case 'math_round':   return 'Math.round(${_expr(f['value']!)})';
      case 'math_floor':   return 'Math.floor(${_expr(f['value']!)})';
      case 'math_ceil':    return 'Math.ceil(${_expr(f['value']!)})';
      case 'math_trunc':   return 'Math.trunc(${_expr(f['value']!)})';
      case 'math_sqrt':    return 'Math.sqrt(${_expr(f['value']!)})';
      case 'math_pow':     return 'Math.pow(${_expr(f['left']!)}, ${_expr(f['right']!)})';
      case 'math_min':     return 'Math.min(${_expr(f['left']!)}, ${_expr(f['right']!)})';
      case 'math_max':     return 'Math.max(${_expr(f['left']!)}, ${_expr(f['right']!)})';
      case 'math_pi':      return 'Math.PI';
      case 'math_e':       return 'Math.E';
      // Print
      case 'print':
        return 'console.log(__ball_to_string(${_expr(f['message']!)}))';
      // Index
      case 'index':
        return '${_expr(f['target']!)}[${_expr(f['index']!)}]';
      // Null / type ops
      case 'null_coalesce':
        return '(${_expr(f['left']!)} ?? ${_expr(f['right']!)})';
      case 'null_check':
        return _expr(f['value']!);
      case 'is':           return 'true /* is check */';
      case 'is_not':       return 'false /* is_not check */';
      case 'as':           return _expr(f['value']!);
      // Control-flow as expression (ternary for if; IIFE for others).
      case 'if':
        {
          final cond = _expr(f['condition']!);
          final t = _expr(f['then']!);
          final e = f['else'] != null ? _expr(f['else']!) : 'undefined';
          return '($cond ? $t : $e)';
        }
      case 'paren':
        return '(${_expr(f['value']!)})';
      case 'assert':
        return 'console.assert(${_expr(f['condition']!)})';
      // Assignment as an expression.
      case 'assign':
        {
          final op = _stringField(call, 'op');
          final opStr = (op != null && op.isNotEmpty) ? op : '=';
          return '(${_expr(f['target']!)} $opStr ${_expr(f['value']!)})';
        }
      // Post/pre inc/dec
      case 'pre_increment':  return '(++${_expr(f['value']!)})';
      case 'pre_decrement':  return '(--${_expr(f['value']!)})';
      case 'post_increment': return '(${_expr(f['value']!)}++)';
      case 'post_decrement': return '(${_expr(f['value']!)}--)';
      // Throw/rethrow as expression-position fallback.
      case 'throw':
        {
          final v = f['value'];
          if (v == null) return '(() => { throw null; })()';
          final str = _compileThrowValue(v) ?? _expr(v);
          return '(() => { throw $str; })()';
        }
      case 'rethrow':
        return '(() => { throw __ball_active_error; })()';
      // Async: `await x` lowers to native TS `await`. The caller is
      // expected to be an async function — ensured by the `is_async`
      // metadata flag we honor in _buildFunctionStatement /
      // _buildMethod.
      case 'await':
        return 'await ${_expr(f['value']!)}';
      // Generator yield: TS supports `yield x` in `function*`; until
      // generators are first-class we emit the same form. Expression
      // position works for both `function` and `function*`.
      case 'yield':
        return 'yield ${_expr(f['value']!)}';
      case 'yield_each':
        return 'yield* ${_expr(f['value']!)}';
      // Std function without a case → still emit as a call so the
      // runtime catches it clearly.
      default:
        {
          final args = f.values.map(_expr).join(', ');
          return '/* std.$fn */ ${_sanitize(fn)}($args)';
        }
    }
  }

  String _wrapIfNeeded(Expression e) {
    final s = _expr(e);
    // Wrap unary/infix operands that need parens before `.method()`.
    if (s.isEmpty) return s;
    final first = s.codeUnitAt(0);
    if (first == 0x21 /* ! */ || first == 0x7E /* ~ */ || first == 0x2D /* - */) {
      return '($s)';
    }
    return s;
  }

  String? _compileThrowValue(Expression v) {
    if (v.whichExpr() != Expression_Expr.messageCreation) return null;
    if (v.messageCreation.typeName.isNotEmpty) return null;
    final entries = v.messageCreation.fields
        .map((f) => "'${f.name}': ${_expr(f.value)}")
        .join(', ');
    return '{$entries}';
  }

  // ─────────────────────────── Helpers ─────────────────────────────

  Expression? _field(FunctionCall call, String name) {
    if (!call.hasInput()) return null;
    if (call.input.whichExpr() != Expression_Expr.messageCreation) return null;
    for (final f in call.input.messageCreation.fields) {
      if (f.name == name) return f.value;
    }
    return null;
  }

  String? _stringField(FunctionCall call, String name) {
    final e = _field(call, name);
    if (e == null) return null;
    if (e.whichExpr() == Expression_Expr.literal &&
        e.literal.whichValue() == Literal_Value.stringValue) {
      return e.literal.stringValue;
    }
    return null;
  }

  String? _stringFieldVal(Map<String, Expression> f, String name) {
    final e = f[name];
    if (e == null) return null;
    if (e.whichExpr() == Expression_Expr.literal &&
        e.literal.whichValue() == Literal_Value.stringValue) {
      return e.literal.stringValue;
    }
    return null;
  }

  Map<String, Expression> _fieldMap(Iterable<FieldValuePair> fields) {
    final m = <String, Expression>{};
    for (final f in fields) {
      m[f.name] = f.value;
    }
    return m;
  }

  List<String> _extractParams(FunctionDefinition fn) {
    if (!fn.hasMetadata()) return const [];
    final params = fn.metadata.fields['params'];
    if (params == null ||
        params.whichKind() != structpb.Value_Kind.listValue) {
      return const [];
    }
    final out = <String>[];
    for (final v in params.listValue.values) {
      if (v.whichKind() != structpb.Value_Kind.structValue) continue;
      final name = v.structValue.fields['name'];
      if (name != null && name.whichKind() == structpb.Value_Kind.stringValue) {
        out.add(name.stringValue);
      }
    }
    return out;
  }

  Map<String, Object?> _structMap(structpb.Struct meta) {
    final out = <String, Object?>{};
    for (final entry in meta.fields.entries) {
      final v = entry.value;
      switch (v.whichKind()) {
        case structpb.Value_Kind.stringValue:
          out[entry.key] = v.stringValue;
          break;
        case structpb.Value_Kind.boolValue:
          out[entry.key] = v.boolValue;
          break;
        case structpb.Value_Kind.numberValue:
          out[entry.key] = v.numberValue;
          break;
        default:
          break;
      }
    }
    return out;
  }

  String _sanitize(String name) {
    var out = name;
    final colon = out.indexOf(':');
    if (colon >= 0) out = out.substring(colon + 1);
    out = out.replaceAll('.', '_').replaceAll('-', '_');
    const reserved = {
      'class', 'function', 'return', 'new', 'delete', 'var', 'let',
      'const', 'typeof', 'instanceof', 'interface', 'enum', 'export',
      'import', 'yield', 'package', 'private', 'protected', 'public',
      'static', 'super', 'this', 'true', 'false', 'null', 'undefined',
    };
    if (reserved.contains(out)) out = '${out}_';
    return out;
  }
}

/// The TypeScript runtime preamble — helper functions that every
/// emitted program needs. Returned separately from [TsCompiler.compile]
/// so downstream tooling can inject it once (before compiled modules)
/// or splice it into the top of the emitted source.
const tsRuntimePreamble = r'''
// Ball TypeScript runtime preamble.
// Auto-prepended to every emitted program. Provides the small set of
// helpers the compiler's std-call emissions rely on.

function __ball_to_string(v: any): string {
  if (typeof v === 'string') return v;
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'number') {
    // Dart's `.toString()` on an int produces "13", not "13.0". Ball
    // programs that explicitly want the ".0" suffix on whole doubles
    // call `std.double_to_string` instead, which routes to
    // `__ball_double_to_string`. The generic path assumes int-like
    // formatting when the number is integral, matching Dart's int
    // default.
    if (Number.isInteger(v)) return v.toString();
    return __ball_double_to_string(v);
  }
  if (typeof v === 'bigint') return v.toString();
  if (v === null || v === undefined) return 'null';
  if (Array.isArray(v)) return '[' + v.map(__ball_to_string).join(', ') + ']';
  return String(v);
}

function __ball_double_to_string(d: number): string {
  if (Number.isNaN(d)) return 'NaN';
  if (d === Infinity) return 'Infinity';
  if (d === -Infinity) return '-Infinity';
  // Dart-style: whole numbers render as "6.0", not "6".
  if (Number.isInteger(d) && Math.abs(d) < 1e16) {
    return `${d.toString()}.0`;
  }
  return d.toString();
}

function __ball_parse_int(s: string): number {
  const trimmed = s.trim();
  if (!/^-?\d+$/.test(trimmed)) {
    const err = new Error(`FormatException: ${s}`);
    throw err;
  }
  return parseInt(trimmed, 10);
}

function __ball_parse_double(s: string): number {
  const n = parseFloat(s);
  if (Number.isNaN(n)) {
    const err = new Error(`FormatException: ${s}`);
    throw err;
  }
  return n;
}

// Active exception marker used by `rethrow` — the catch block binds
// the raw error to this name and `throw __ball_active_error;` re-raises
// it. Declared as `any` so it's visible everywhere; the catch binding
// shadows it within scope.
let __ball_active_error: any = undefined;
''';

/// Constructor parameter shape (structurally similar to what the Dart
/// encoder stores under `metadata.params` for a constructor function).
/// `isThis` marks Dart's initializing-formal pattern (`this.x`).
class _CtorParam {
  final String name;
  final bool isThis;
  const _CtorParam({required this.name, this.isThis = false});
}
