/// Emit golden CLI-verb outputs from the Dart-native `cli_core` — the source of
/// truth for the C++ parity gate (`cpp/test/test_cli_parity.cpp`, the C++ mirror
/// of `dart/cli/test/cli_core_parity_test.dart`).
///
/// For every `tests/conformance/*.ball.json`, writes three files into the output
/// directory:
///   - `<stem>.info.txt`      = cli_core.infoReport(program)
///   - `<stem>.validate.txt`  = cli_core.validateReport(program)
///   - `<stem>.tree.txt`      = cli_core.treeReport(program)
///
/// plus a single `version.txt` = cli_core.versionLine(cli version).
///
/// The C++ `test_cli_parity` runs the *compiled* `cli_core` (`dart/self_host/lib/
/// cli_rt.h`, produced by `gen_cli_cpp.dart`) over the same fixtures and asserts
/// byte-identical output — so the C++ `ball` verbs and the Dart CLI are proven to
/// compute the same reports. `audit` is excluded (see `gen_cli_cpp.dart`).
///
///   cd dart && dart run cli/tool/gen_cli_parity_goldens.dart OUT_DIR
///
/// The goldens are a build artifact (regenerated by CI), not checked in.
library;

import 'dart:convert';
import 'dart:io';

import 'package:ball_base/ball_base.dart' show decodeProgramJson;
import 'package:ball_base/cli_core.dart' as cli_core;
import 'package:ball_cli/version.g.dart';

String _findRepoRoot() {
  var dir = Directory.current;
  while (true) {
    if (File('${dir.path}/proto/ball/v1/ball.proto').existsSync()) {
      return dir.path.replaceAll('\\', '/');
    }
    final parent = dir.parent;
    if (parent.path == dir.path) throw StateError('Not in ball repo');
    dir = parent;
  }
}

void main(List<String> args) {
  if (args.isEmpty) {
    stderr.writeln(
      'Usage: dart run cli/tool/gen_cli_parity_goldens.dart <out_dir>',
    );
    exit(1);
  }
  final root = _findRepoRoot();
  final outDir = Directory(args[0]);
  outDir.createSync(recursive: true);

  final conformance = Directory('$root/tests/conformance');
  final fixtures =
      conformance
          .listSync()
          .whereType<File>()
          .where((f) => f.path.endsWith('.ball.json'))
          .toList()
        ..sort((a, b) => a.path.compareTo(b.path));

  var count = 0;
  for (final f in fixtures) {
    final stem = f.uri.pathSegments.last.replaceAll('.ball.json', '');
    final program = decodeProgramJson(jsonDecode(f.readAsStringSync()));
    File('${outDir.path}/$stem.info.txt')
        .writeAsStringSync(cli_core.infoReport(program));
    File('${outDir.path}/$stem.validate.txt')
        .writeAsStringSync(cli_core.validateReport(program));
    File('${outDir.path}/$stem.tree.txt')
        .writeAsStringSync(cli_core.treeReport(program));
    count++;
  }

  File(
    '${outDir.path}/version.txt',
  ).writeAsStringSync(cli_core.versionLine(ballCliVersion));

  stdout.writeln(
    'Wrote CLI parity goldens for $count fixtures (+version) → ${outDir.path}',
  );
}
