# CMake generated Testfile for 
# Source directory: D:/packages/ball/cpp/test
# Build directory: D:/packages/ball/cpp/build2/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(engine_tests "D:/packages/ball/cpp/build2/test/Debug/test_engine.exe")
  set_tests_properties(engine_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/packages/ball/cpp/test/CMakeLists.txt;168;add_test;D:/packages/ball/cpp/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(engine_tests "D:/packages/ball/cpp/build2/test/Release/test_engine.exe")
  set_tests_properties(engine_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/packages/ball/cpp/test/CMakeLists.txt;168;add_test;D:/packages/ball/cpp/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(engine_tests "D:/packages/ball/cpp/build2/test/MinSizeRel/test_engine.exe")
  set_tests_properties(engine_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/packages/ball/cpp/test/CMakeLists.txt;168;add_test;D:/packages/ball/cpp/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(engine_tests "D:/packages/ball/cpp/build2/test/RelWithDebInfo/test_engine.exe")
  set_tests_properties(engine_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/packages/ball/cpp/test/CMakeLists.txt;168;add_test;D:/packages/ball/cpp/test/CMakeLists.txt;0;")
else()
  add_test(engine_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(compiler_tests "D:/packages/ball/cpp/build2/test/Debug/test_compiler.exe")
  set_tests_properties(compiler_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/packages/ball/cpp/test/CMakeLists.txt;169;add_test;D:/packages/ball/cpp/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(compiler_tests "D:/packages/ball/cpp/build2/test/Release/test_compiler.exe")
  set_tests_properties(compiler_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/packages/ball/cpp/test/CMakeLists.txt;169;add_test;D:/packages/ball/cpp/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(compiler_tests "D:/packages/ball/cpp/build2/test/MinSizeRel/test_compiler.exe")
  set_tests_properties(compiler_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/packages/ball/cpp/test/CMakeLists.txt;169;add_test;D:/packages/ball/cpp/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(compiler_tests "D:/packages/ball/cpp/build2/test/RelWithDebInfo/test_compiler.exe")
  set_tests_properties(compiler_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/packages/ball/cpp/test/CMakeLists.txt;169;add_test;D:/packages/ball/cpp/test/CMakeLists.txt;0;")
else()
  add_test(compiler_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(conformance_tests "D:/packages/ball/cpp/build2/test/Debug/test_conformance.exe")
  set_tests_properties(conformance_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/packages/ball/cpp/test/CMakeLists.txt;170;add_test;D:/packages/ball/cpp/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(conformance_tests "D:/packages/ball/cpp/build2/test/Release/test_conformance.exe")
  set_tests_properties(conformance_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/packages/ball/cpp/test/CMakeLists.txt;170;add_test;D:/packages/ball/cpp/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(conformance_tests "D:/packages/ball/cpp/build2/test/MinSizeRel/test_conformance.exe")
  set_tests_properties(conformance_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/packages/ball/cpp/test/CMakeLists.txt;170;add_test;D:/packages/ball/cpp/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(conformance_tests "D:/packages/ball/cpp/build2/test/RelWithDebInfo/test_conformance.exe")
  set_tests_properties(conformance_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/packages/ball/cpp/test/CMakeLists.txt;170;add_test;D:/packages/ball/cpp/test/CMakeLists.txt;0;")
else()
  add_test(conformance_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(encoder_tests "D:/packages/ball/cpp/build2/test/Debug/test_encoder.exe")
  set_tests_properties(encoder_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/packages/ball/cpp/test/CMakeLists.txt;171;add_test;D:/packages/ball/cpp/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(encoder_tests "D:/packages/ball/cpp/build2/test/Release/test_encoder.exe")
  set_tests_properties(encoder_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/packages/ball/cpp/test/CMakeLists.txt;171;add_test;D:/packages/ball/cpp/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(encoder_tests "D:/packages/ball/cpp/build2/test/MinSizeRel/test_encoder.exe")
  set_tests_properties(encoder_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/packages/ball/cpp/test/CMakeLists.txt;171;add_test;D:/packages/ball/cpp/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(encoder_tests "D:/packages/ball/cpp/build2/test/RelWithDebInfo/test_encoder.exe")
  set_tests_properties(encoder_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/packages/ball/cpp/test/CMakeLists.txt;171;add_test;D:/packages/ball/cpp/test/CMakeLists.txt;0;")
else()
  add_test(encoder_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(e2e_tests "D:/packages/ball/cpp/build2/test/Debug/test_e2e.exe")
  set_tests_properties(e2e_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/packages/ball/cpp/test/CMakeLists.txt;172;add_test;D:/packages/ball/cpp/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(e2e_tests "D:/packages/ball/cpp/build2/test/Release/test_e2e.exe")
  set_tests_properties(e2e_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/packages/ball/cpp/test/CMakeLists.txt;172;add_test;D:/packages/ball/cpp/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(e2e_tests "D:/packages/ball/cpp/build2/test/MinSizeRel/test_e2e.exe")
  set_tests_properties(e2e_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/packages/ball/cpp/test/CMakeLists.txt;172;add_test;D:/packages/ball/cpp/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(e2e_tests "D:/packages/ball/cpp/build2/test/RelWithDebInfo/test_e2e.exe")
  set_tests_properties(e2e_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/packages/ball/cpp/test/CMakeLists.txt;172;add_test;D:/packages/ball/cpp/test/CMakeLists.txt;0;")
else()
  add_test(e2e_tests NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(snapshot_tests "D:/packages/ball/cpp/build2/test/Debug/test_snapshot.exe")
  set_tests_properties(snapshot_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/packages/ball/cpp/test/CMakeLists.txt;173;add_test;D:/packages/ball/cpp/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(snapshot_tests "D:/packages/ball/cpp/build2/test/Release/test_snapshot.exe")
  set_tests_properties(snapshot_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/packages/ball/cpp/test/CMakeLists.txt;173;add_test;D:/packages/ball/cpp/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(snapshot_tests "D:/packages/ball/cpp/build2/test/MinSizeRel/test_snapshot.exe")
  set_tests_properties(snapshot_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/packages/ball/cpp/test/CMakeLists.txt;173;add_test;D:/packages/ball/cpp/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(snapshot_tests "D:/packages/ball/cpp/build2/test/RelWithDebInfo/test_snapshot.exe")
  set_tests_properties(snapshot_tests PROPERTIES  _BACKTRACE_TRIPLES "D:/packages/ball/cpp/test/CMakeLists.txt;173;add_test;D:/packages/ball/cpp/test/CMakeLists.txt;0;")
else()
  add_test(snapshot_tests NOT_AVAILABLE)
endif()
