// Package compiler implements the Ball → Go compiler: it walks a Ball `Program`
// protobuf and emits Go source as a string (the string-emission approach shared
// by the C++ and Rust compilers, rather than an AST builder like Dart's
// code_builder).
//
// # Shape of the emitted code
//
// Every Ball expression compiles to a Go expression that evaluates to a
// `ballrt.Value` (package `github.com/ball-lang/ball/go/runtime`) — there are no
// "void" expressions, so every position (block tail, if/else arm, function
// body) stays type-uniform, exactly like the Rust compiler's invariant. Go has
// no block/if/loop *expressions*, so anything used in value position that needs
// statements is wrapped in an immediately-invoked function expression (IIFE),
// `func() ballrt.Value { … }()` — the same device C++ uses (its IIFE lambdas).
//
// The seven Ball expression node types (invariant: call, literal, reference,
// fieldAccess, messageCreation, block, lambda) are each handled by a
// `compile*` method. The special reference name "input" is the current
// function's single parameter (invariant #1). Control flow (`if`/`for`/`while`/
// `for_in`) is a set of `std` base functions compiled to *native* Go control
// flow evaluated lazily (never eagerly evaluating every branch — invariant #4);
// `return`/`break`/`continue`/`throw` become `ballrt` flow signals so they cross
// the IIFE boundaries (see `go/runtime/flow.go`).
package compiler

import (
	"fmt"
	"strconv"
	"strings"

	ballv1 "github.com/ball-lang/ball/go/shared/gen/ball/v1"
)

// runtimeImportPath is the module path of the emitted code's runtime dependency.
const runtimeImportPath = "github.com/ball-lang/ball/go/runtime"

// Compiler holds the lookup tables needed to compile one Program.
type Compiler struct {
	prog *ballv1.Program

	// baseModules is the set of module names whose functions are all base
	// (is_base = true) — e.g. "std", "std_collections". A call into one of
	// these dispatches through compileBaseCall; a call into any other module
	// (or the empty "current module") is a direct Go function call.
	baseModules map[string]bool

	// userFuncs is the set of sanitized names of every non-base, non-entry user
	// function — the direct-call / tear-off targets.
	userFuncs map[string]bool

	// scopes is the lexical scope stack of sanitized local names (parameters,
	// let-bindings, loop variables). Used to tell a reference to a local from a
	// bare reference to a top-level function (a tear-off).
	scopes []map[string]bool

	// errs accumulates fail-loud compile errors (unsupported base functions,
	// unhandled shapes). A non-empty errs makes Compile return an error rather
	// than silently emitting degraded code (issue #55 doctrine).
	errs []string
}

// New builds a Compiler for prog, scanning modules to classify base modules and
// collect user function names.
func New(prog *ballv1.Program) *Compiler {
	c := &Compiler{
		prog:        prog,
		baseModules: map[string]bool{},
		userFuncs:   map[string]bool{},
	}
	for _, m := range prog.GetModules() {
		fns := m.GetFunctions()
		allBase := len(fns) > 0
		for _, f := range fns {
			if !f.GetIsBase() {
				allBase = false
				break
			}
		}
		if allBase {
			c.baseModules[m.GetName()] = true
		}
	}
	for _, m := range prog.GetModules() {
		if c.baseModules[m.GetName()] {
			continue
		}
		for _, f := range m.GetFunctions() {
			if f.GetIsBase() {
				continue
			}
			if m.GetName() == prog.GetEntryModule() && f.GetName() == prog.GetEntryFunction() {
				continue
			}
			c.userFuncs[sanitize(f.GetName())] = true
		}
	}
	return c
}

// Compile compiles the whole Program to a formatted-ready Go source string
// (package main). Returns an error if any expression shape or base function was
// unsupported (fail-loud), listing every such site.
func Compile(prog *ballv1.Program) (string, error) {
	return New(prog).Compile()
}

// Compile emits the Go source for the receiver's Program.
func (c *Compiler) Compile() (string, error) {
	entryMod, entryFn := c.entryPoint()
	if entryFn == nil {
		return "", fmt.Errorf("entry function %q not found in module %q",
			c.prog.GetEntryFunction(), c.prog.GetEntryModule())
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by the Ball Go compiler from program %q v%s. DO NOT EDIT.\n",
		c.prog.GetName(), c.prog.GetVersion())
	b.WriteString("package main\n\n")
	fmt.Fprintf(&b, "import ballrt %q\n\n", runtimeImportPath)

	// Type definitions from every non-base module's typeDefs[].
	for _, m := range c.prog.GetModules() {
		if c.baseModules[m.GetName()] {
			continue
		}
		b.WriteString(c.compileModuleTypes(m))
	}

	// Every non-base, non-entry function as a free Go func.
	for _, m := range c.prog.GetModules() {
		if c.baseModules[m.GetName()] {
			continue
		}
		for _, f := range m.GetFunctions() {
			if f.GetIsBase() {
				continue
			}
			if m.GetName() == entryMod.GetName() && f.GetName() == c.prog.GetEntryFunction() {
				continue
			}
			b.WriteString(c.compileFunction(f))
			b.WriteString("\n")
		}
	}

	// The entry point, inlined into Go's func main via ballrt.RunEntry.
	b.WriteString(c.compileEntry(entryFn))

	if len(c.errs) > 0 {
		return b.String(), fmt.Errorf("ball→go: %d unsupported construct(s):\n  - %s",
			len(c.errs), strings.Join(c.errs, "\n  - "))
	}
	return b.String(), nil
}

func (c *Compiler) entryPoint() (*ballv1.Module, *ballv1.FunctionDefinition) {
	for _, m := range c.prog.GetModules() {
		if m.GetName() != c.prog.GetEntryModule() {
			continue
		}
		for _, f := range m.GetFunctions() {
			if f.GetName() == c.prog.GetEntryFunction() {
				return m, f
			}
		}
	}
	return nil, nil
}

// ── Function emission ───────────────────────────────────────────────────────

// compileFunction emits a non-entry function as
// `func name(input ballrt.Value) (__ret ballrt.Value) { … }` (invariant #1 —
// one input, one output). A deferred ballrt.CatchReturn captures a std.return
// that unwinds the body; a normal tail value flows through the named return.
func (c *Compiler) compileFunction(f *ballv1.FunctionDefinition) string {
	name := sanitize(f.GetName())
	c.pushScope()
	c.bind("input")
	prologue := c.paramPrologue(f)
	body := c.compileBody(f)
	c.popScope()

	var b strings.Builder
	fmt.Fprintf(&b, "func %s(input ballrt.Value) (__ret ballrt.Value) {\n", name)
	b.WriteString("\t_ = input\n")
	b.WriteString(prologue)
	b.WriteString("\tdefer ballrt.CatchReturn(&__ret)\n")
	fmt.Fprintf(&b, "\t__ret = %s\n", body)
	b.WriteString("\treturn\n}\n")
	return b.String()
}

// compileEntry inlines the entry function's body into Go's func main, run via
// ballrt.RunEntry (which swallows a top-level return and reports an uncaught
// Ball exception).
func (c *Compiler) compileEntry(f *ballv1.FunctionDefinition) string {
	c.pushScope()
	c.bind("input")
	prologue := c.paramPrologue(f)
	body := c.compileBody(f)
	c.popScope()

	var b strings.Builder
	b.WriteString("func main() {\n")
	b.WriteString("\tballrt.RunEntry(func() ballrt.Value {\n")
	if prologue != "" {
		// Re-indent the prologue one extra level for the closure body.
		b.WriteString(indent(prologue, "\t"))
	}
	fmt.Fprintf(&b, "\t\treturn %s\n", body)
	b.WriteString("\t})\n}\n")
	return b.String()
}

func (c *Compiler) compileBody(f *ballv1.FunctionDefinition) string {
	if f.GetBody() == nil {
		return "ballrt.Value(nil)"
	}
	return c.compileExpr(f.GetBody())
}

// paramPrologue emits the `let`-style aliases that bind a function's declared
// parameter names to its single `input` (invariant #1). One positional
// parameter is passed directly (`n := input`); multiple parameters are the
// encoder's anonymous-message convention, each read by name from the input
// (`a := ballrt.FieldGet(input, "a")`).
func (c *Compiler) paramPrologue(f *ballv1.FunctionDefinition) string {
	params := funcParams(f)
	if len(params) == 0 {
		return ""
	}
	var b strings.Builder
	if len(params) == 1 {
		n := sanitize(params[0])
		c.bind(params[0])
		fmt.Fprintf(&b, "\t%s := input\n\t_ = %s\n", n, n)
		return b.String()
	}
	for _, p := range params {
		n := sanitize(p)
		c.bind(p)
		fmt.Fprintf(&b, "\t%s := ballrt.FieldGet(input, %q)\n\t_ = %s\n", n, p, n)
	}
	return b.String()
}

// ── Expression compilation (the 7 node types) ───────────────────────────────

// compileExpr recursively compiles any Ball Expression to a Go expression
// string that evaluates to a ballrt.Value.
func (c *Compiler) compileExpr(e *ballv1.Expression) string {
	if e == nil || e.GetExpr() == nil {
		return "ballrt.Value(nil)"
	}
	switch x := e.GetExpr().(type) {
	case *ballv1.Expression_Literal:
		return c.compileLiteral(x.Literal)
	case *ballv1.Expression_Reference:
		return c.compileReference(x.Reference)
	case *ballv1.Expression_Call:
		return c.compileCall(x.Call)
	case *ballv1.Expression_FieldAccess:
		return c.compileFieldAccess(x.FieldAccess)
	case *ballv1.Expression_MessageCreation:
		return c.compileMessageCreation(x.MessageCreation)
	case *ballv1.Expression_Block:
		return c.compileBlock(x.Block)
	case *ballv1.Expression_Lambda:
		return c.compileLambda(x.Lambda)
	default:
		c.fail("unhandled expression node %T", x)
		return "ballrt.Value(nil)"
	}
}

// compileLiteral emits a Go literal for each Ball literal value.
func (c *Compiler) compileLiteral(l *ballv1.Literal) string {
	switch v := l.GetValue().(type) {
	case *ballv1.Literal_IntValue:
		return fmt.Sprintf("int64(%d)", v.IntValue)
	case *ballv1.Literal_DoubleValue:
		return fmt.Sprintf("float64(%s)", goFloat(v.DoubleValue))
	case *ballv1.Literal_StringValue:
		return strconv.Quote(v.StringValue)
	case *ballv1.Literal_BoolValue:
		return strconv.FormatBool(v.BoolValue)
	case *ballv1.Literal_BytesValue:
		return goBytes(v.BytesValue)
	case *ballv1.Literal_ListValue:
		elems := v.ListValue.GetElements()
		parts := make([]string, len(elems))
		for i, el := range elems {
			parts[i] = c.compileExpr(el)
		}
		return "ballrt.NewList(" + strings.Join(parts, ", ") + ")"
	default:
		// Unset Literal.value oneof = Ball null.
		return "ballrt.Value(nil)"
	}
}

// noInitSentinel is the encoders' shared marker for an uninitialized
// `late`/nullable local; a reference to it reads as Ball null.
const noInitSentinel = "__no_init__"

// compileReference emits an identifier read. "input" is the function parameter;
// a bare reference to a top-level user function used as a value becomes a
// tear-off (*ballrt.Function).
func (c *Compiler) compileReference(r *ballv1.Reference) string {
	name := r.GetName()
	if name == "input" {
		return "input"
	}
	if name == noInitSentinel {
		return "ballrt.Value(nil)"
	}
	sn := sanitize(name)
	if !c.isLocal(name) && c.userFuncs[sn] {
		return fmt.Sprintf("ballrt.Fn(%q, %s)", name, sn)
	}
	return sn
}

// compileFieldAccess emits object.field via the runtime helper (dynamic
// *Message / *Map receiver).
func (c *Compiler) compileFieldAccess(fa *ballv1.FieldAccess) string {
	obj := c.compileExpr(fa.GetObject())
	return fmt.Sprintf("ballrt.FieldGet(%s, %q)", obj, fa.GetField())
}

// compileMessageCreation constructs a runtime value from named field
// expressions: an anonymous message (empty type_name — the shape base-function
// inputs use, though those are normally consumed by compileBaseCall before ever
// reaching here) becomes an ordered *Map; a named type becomes a *Message.
func (c *Compiler) compileMessageCreation(mc *ballv1.MessageCreation) string {
	var b strings.Builder
	b.WriteString("func() ballrt.Value {\n")
	b.WriteString("\t\t__m := ballrt.NewMap()\n")
	for _, fv := range mc.GetFields() {
		fmt.Fprintf(&b, "\t\t__m.Set(%q, %s)\n", fv.GetName(), c.compileExpr(fv.GetValue()))
	}
	if mc.GetTypeName() == "" {
		b.WriteString("\t\treturn __m\n\t}()")
	} else {
		fmt.Fprintf(&b, "\t\treturn ballrt.NewMessage(%q, __m)\n\t}()", mc.GetTypeName())
	}
	return b.String()
}

// compileBlock emits a Go IIFE: let-bindings become `:=` declarations,
// non-let statements are evaluated for effect, and the result expression is the
// IIFE's return value (nil when a block has no result).
func (c *Compiler) compileBlock(block *ballv1.Block) string {
	c.pushScope()
	defer c.popScope()

	var b strings.Builder
	b.WriteString("func() ballrt.Value {\n")
	b.WriteString(indent(c.compileStatements(block.GetStatements()), "\t"))
	if block.GetResult() != nil {
		fmt.Fprintf(&b, "\t\treturn %s\n", c.compileExpr(block.GetResult()))
	} else {
		b.WriteString("\t\treturn ballrt.Value(nil)\n")
	}
	b.WriteString("\t}()")
	return b.String()
}

// compileStatements emits a block/loop-body's statements (no result). A let
// binds a `:=` local (with a `_ = name` guard against Go's unused-variable
// error and to keep the binding live for closures); a bare expression statement
// is assigned to `_`.
func (c *Compiler) compileStatements(stmts []*ballv1.Statement) string {
	var b strings.Builder
	for _, s := range stmts {
		switch st := s.GetStmt().(type) {
		case *ballv1.Statement_Let:
			n := sanitize(st.Let.GetName())
			val := c.compileExpr(st.Let.GetValue())
			c.bind(st.Let.GetName())
			// Declare every local as ballrt.Value (not the inferred concrete
			// type) so a later std.assign — which yields a dynamic ballrt.Value —
			// can reassign it without a Go type mismatch.
			fmt.Fprintf(&b, "var %s ballrt.Value = %s\n_ = %s\n", n, val, n)
		case *ballv1.Statement_Expression:
			fmt.Fprintf(&b, "_ = %s\n", c.compileExpr(st.Expression))
		default:
			c.fail("unhandled statement node %T", st)
		}
	}
	return b.String()
}

// compileLambda emits an anonymous FunctionDefinition (name "") as a
// *ballrt.Function value.
func (c *Compiler) compileLambda(f *ballv1.FunctionDefinition) string {
	c.pushScope()
	c.bind("input")
	prologue := c.paramPrologue(f)
	body := c.compileBody(f)
	c.popScope()

	var b strings.Builder
	b.WriteString("ballrt.Fn(\"\", func(input ballrt.Value) (__ret ballrt.Value) {\n")
	b.WriteString("\t\t_ = input\n")
	if prologue != "" {
		b.WriteString(indent(prologue, "\t"))
	}
	b.WriteString("\t\tdefer ballrt.CatchReturn(&__ret)\n")
	fmt.Fprintf(&b, "\t\t__ret = %s\n", body)
	b.WriteString("\t\treturn\n\t})")
	return b.String()
}

// ── Scope tracking ──────────────────────────────────────────────────────────

func (c *Compiler) pushScope() { c.scopes = append(c.scopes, map[string]bool{}) }
func (c *Compiler) popScope()  { c.scopes = c.scopes[:len(c.scopes)-1] }

func (c *Compiler) bind(name string) {
	if len(c.scopes) > 0 {
		c.scopes[len(c.scopes)-1][sanitize(name)] = true
	}
}

func (c *Compiler) isLocal(name string) bool {
	sn := sanitize(name)
	for i := len(c.scopes) - 1; i >= 0; i-- {
		if c.scopes[i][sn] {
			return true
		}
	}
	return false
}

func (c *Compiler) fail(format string, args ...any) {
	c.errs = append(c.errs, fmt.Sprintf(format, args...))
}
