/// Dart target emitter: turns a [GenFile] into `.pb.dart` source.
///
/// The emitted shape follows §4.3 of `docs/PROTOBUF_CODEGEN_PLAN.md`: each
/// message is a **mutable class wrapping a `Map<String, Object?>` backing
/// store**, with typed getters/setters that read/write that map, plus an
/// **embedded `ball_protobuf` descriptor** carrying the resolved Editions
/// features. All serialization delegates to the runtime (`marshal`/`unmarshal`,
/// `messageToJson`/`messageFromJson`) — no wire logic is generated.
///
/// ## Descriptor graph
///
/// The bridge's resolved descriptors form a (possibly cyclic) object graph:
/// a message field's `'messageDescriptor'` is an identity reference to another
/// message's field list (so `recursive_message` / `corecursive` terminate). A
/// `const` Dart literal cannot express cycles, so instead of inlining the
/// referenced list we emit a single lazily-populated registry,
/// `_$descriptors` (`Map<String, List<Map<String, Object?>>>`), keyed by FQN.
/// Each field map is emitted as a literal **except** that `'messageDescriptor'`
/// (and a map field's message-typed `'messageDescriptor'`) becomes a registry
/// lookup `_lookup('<fqn>')`, breaking the cycle. Every class delegates to its
/// registry entry via `static List<Map<String, Object?>> get descriptor`.
library;

import 'gen_model.dart';

/// Header marking generated files (do not edit).
String _header(String protoPath) =>
    '// GENERATED CODE — DO NOT EDIT.\n'
    '//\n'
    '// Generated by protoc-gen-ball from $protoPath.\n'
    '// Mutable-over-Map models bound to the ball_protobuf runtime.\n'
    '//\n'
    '// ignore_for_file: prefer_const_constructors, non_constant_identifier_names\n'
    '// ignore_for_file: constant_identifier_names, library_prefixes\n'
    '// ignore_for_file: unnecessary_cast, unused_element, deprecated_member_use\n'
    '// ignore_for_file: lines_longer_than_80_chars, camel_case_types\n'
    '// ignore_for_file: annotate_overrides, prefer_final_fields\n';

/// Emits the full `.pb.dart` source for [file].
String emitDartFile(GenFile file) {
  final b = StringBuffer();
  b.write(_header(file.protoPath));
  b.writeln();
  b.writeln("import 'package:ball_protobuf/ball_protobuf.dart' as \$pb;");
  b.writeln();

  // Enums first (messages reference them).
  for (final e in file.enums) {
    _emitEnum(b, e);
    b.writeln();
  }

  // Messages (map-entry helpers are skipped — absorbed into map fields).
  for (final m in file.messages) {
    if (m.isMapEntry) continue;
    _emitMessage(b, m);
    b.writeln();
  }

  // The shared descriptor registry + lazy builders.
  _emitDescriptorRegistry(b, file);

  return b.toString();
}

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

void _emitEnum(StringBuffer b, GenEnum e) {
  // Emit an int-backed enum: a class with const instances + a value map. An
  // int wrapper (not a Dart `enum`) so open enums can carry unknown integers
  // without crashing, mirroring the runtime's open-enum behavior.
  b.writeln('/// Generated from `${e.fullName}`.');
  b.writeln('class ${e.dartName} {');
  b.writeln('  final int value;');
  b.writeln('  final String name;');
  b.writeln('  const ${e.dartName}._(this.value, this.name);');
  b.writeln();

  // De-duplicate by number for the const instances (first declared name wins,
  // matching the registry's canonical-name choice); later aliases reuse it.
  final seen = <int>{};
  for (final v in e.values) {
    if (!seen.add(v.number)) continue;
    b.writeln(
      "  static const ${v.dartName} = "
      "${e.dartName}._(${v.number}, '${v.protoName}');",
    );
  }
  b.writeln();

  // All canonical instances, for `values` and lookup.
  final canonical = <GenEnumValue>[];
  final seen2 = <int>{};
  for (final v in e.values) {
    if (seen2.add(v.number)) canonical.add(v);
  }
  b.write('  static const List<${e.dartName}> values = [');
  b.write(canonical.map((v) => v.dartName).join(', '));
  b.writeln('];');
  b.writeln();

  // Construct from an integer; unknown values yield an unnamed instance so
  // open enums preserve out-of-range ints.
  b.writeln('  factory ${e.dartName}.fromValue(int value) {');
  b.writeln('    for (final v in values) {');
  b.writeln('      if (v.value == value) return v;');
  b.writeln('    }');
  b.writeln("    return ${e.dartName}._(value, 'UNKNOWN');");
  b.writeln('  }');
  b.writeln();
  b.writeln('  @override');
  b.writeln('  bool operator ==(Object other) =>');
  b.writeln('      other is ${e.dartName} && other.value == value;');
  b.writeln('  @override');
  b.writeln('  int get hashCode => value.hashCode;');
  b.writeln('  @override');
  b.writeln("  String toString() => '${e.dartName}.\$name';");
  b.writeln('}');
}

// ---------------------------------------------------------------------------
// Messages
// ---------------------------------------------------------------------------

void _emitMessage(StringBuffer b, GenMessage m) {
  b.writeln('/// Generated from `${m.fullName}`.');
  b.writeln('class ${m.dartName} {');
  b.writeln('  /// The dynamic backing store (proto field names -> values).');
  b.writeln('  final Map<String, Object?> \$fields;');
  b.writeln();
  b.writeln(
    '  ${m.dartName}([Map<String, Object?>? fields]) '
    ': \$fields = fields ?? <String, Object?>{};',
  );
  b.writeln();
  b.writeln('  /// The fully-qualified protobuf type name.');
  b.writeln("  static const String fullName = '${m.fullName}';");
  b.writeln();
  b.writeln(
    '  /// The resolved ball_protobuf field descriptor (Editions-aware).',
  );
  b.writeln(
    '  static List<Map<String, Object?>> get descriptor => '
    "\$descriptorFor('${m.fullName}');",
  );
  b.writeln();

  // Oneof discriminants.
  final oneofs = <String, List<GenField>>{};
  for (final f in m.fields) {
    if (f.oneofName != null) {
      oneofs.putIfAbsent(f.oneofName!, () => []).add(f);
    }
  }
  for (final entry in oneofs.entries) {
    _emitOneofDiscriminant(b, m, entry.key, entry.value);
  }

  // Field accessors.
  for (final f in m.fields) {
    _emitField(b, m, f);
  }

  // Serialization delegates.
  b.writeln('  /// Encodes this message to protobuf binary bytes.');
  b.writeln('  List<int> toBytes() => \$pb.marshal(\$fields, descriptor);');
  b.writeln();
  b.writeln('  /// Decodes [bytes] into a new ${m.dartName}.');
  b.writeln(
    '  static ${m.dartName} fromBytes(List<int> bytes) => '
    '${m.dartName}(\$pb.unmarshal(bytes, descriptor));',
  );
  b.writeln();
  b.writeln('  /// Converts this message to its proto3-JSON representation.');
  b.writeln(
    '  Object? toProto3Json() => \$pb.messageToJson(\$fields, descriptor,\n'
    '      anyTypeResolver: \$descriptorForOrNull);',
  );
  b.writeln();
  b.writeln(
    '  /// Parses a proto3-JSON value [json] into a new ${m.dartName}.',
  );
  b.writeln(
    '  static ${m.dartName} fromProto3Json(Object? json) => ${m.dartName}(\n'
    '      \$pb.messageFromJson(json, descriptor,\n'
    '          anyTypeResolver: \$descriptorForOrNull));',
  );
  b.writeln('}');
}

void _emitOneofDiscriminant(
  StringBuffer b,
  GenMessage m,
  String oneofName,
  List<GenField> members,
) {
  final enumName = '${m.dartName}_${_pascal(oneofName)}Case';
  b.writeln('  /// Discriminant for the `$oneofName` oneof.');
  b.writeln('  $enumName get which${_pascal(oneofName)} {');
  for (final f in members) {
    b.writeln(
      "    if (\$fields['${f.protoName}'] != null) {\n"
      '      return $enumName.${f.dartName};\n'
      '    }',
    );
  }
  b.writeln('    return $enumName.notSet;');
  b.writeln('  }');
  b.writeln();
  b.writeln('  /// Clears whichever member of `$oneofName` is set.');
  b.writeln('  void clear${_pascal(oneofName)}() {');
  for (final f in members) {
    b.writeln("    \$fields.remove('${f.protoName}');");
  }
  b.writeln('  }');
  b.writeln();
}

void _emitField(StringBuffer b, GenMessage m, GenField f) {
  switch (f.cardinality) {
    case FieldCardinality.singular:
      _emitSingular(b, m, f);
    case FieldCardinality.repeated:
      _emitRepeated(b, f);
    case FieldCardinality.map:
      _emitMap(b, f);
  }
}

void _emitSingular(StringBuffer b, GenMessage m, GenField f) {
  final key = f.protoName;
  if (f.isMessage) {
    final type = _messageDartType(f.messageTypeName!);
    // Getter returns a typed view over the stored sub-map (or null when absent).
    b.writeln('  /// `${f.protoName}` (message `${f.messageTypeName}`).');
    b.writeln('  $type? get ${f.dartName} {');
    b.writeln("    final v = \$fields['$key'];");
    b.writeln('    if (v == null) return null;');
    b.writeln('    return $type(v as Map<String, Object?>);');
    b.writeln('  }');
    b.writeln(
      '  set ${f.dartName}($type? v) => v == null\n'
      "      ? \$fields.remove('$key')\n"
      "      : \$fields['$key'] = v.\$fields;",
    );
    _emitPresence(b, f, key);
    return;
  }

  if (f.isEnum) {
    final type = _enumDartType(f.enumTypeName!);
    b.writeln('  /// `${f.protoName}` (enum `${f.enumTypeName}`).');
    if (f.presence == PresenceKind.implicit) {
      b.writeln('  $type get ${f.dartName} {');
      b.writeln("    final v = \$fields['$key'];");
      b.writeln('    return $type.fromValue(v == null ? 0 : v as int);');
      b.writeln('  }');
      b.writeln("  set ${f.dartName}($type v) => \$fields['$key'] = v.value;");
    } else {
      b.writeln('  $type? get ${f.dartName} {');
      b.writeln("    final v = \$fields['$key'];");
      b.writeln('    return v == null ? null : $type.fromValue(v as int);');
      b.writeln('  }');
      b.writeln(
        '  set ${f.dartName}($type? v) => v == null\n'
        "      ? \$fields.remove('$key')\n"
        "      : \$fields['$key'] = v.value;",
      );
    }
    _emitPresence(b, f, key);
    return;
  }

  // Scalar. The getter always falls back to the type default; EXPLICIT /
  // LEGACY_REQUIRED presence is distinguished only by the generated
  // `hasX()` / `clearX()` (and by the descriptor, which makes the runtime
  // serialize a present default). IMPLICIT fields get no presence accessors.
  final type = _scalarDartType(f.protoType);
  final defaultExpr = _scalarDefault(f.protoType);
  b.writeln('  /// `${f.protoName}`.');
  b.writeln(
    '  $type get ${f.dartName} => '
    "(\$fields['$key'] as $type?) ?? $defaultExpr;",
  );
  b.writeln("  set ${f.dartName}($type v) => \$fields['$key'] = v;");
  _emitPresence(b, f, key);
}

/// For EXPLICIT / LEGACY_REQUIRED fields, emit `hasX()` / `clearX()`. IMPLICIT
/// fields get neither (presence is value != default, with no tracking).
void _emitPresence(StringBuffer b, GenField f, String key) {
  if (f.presence == PresenceKind.implicit) {
    b.writeln();
    return;
  }
  final name = _pascal(f.dartName);
  b.writeln("  bool has$name() => \$fields['$key'] != null;");
  b.writeln("  void clear$name() => \$fields.remove('$key');");
  b.writeln();
}

void _emitRepeated(StringBuffer b, GenField f) {
  final key = f.protoName;
  final String elemType;
  if (f.isMessage) {
    elemType = _messageDartType(f.messageTypeName!);
  } else if (f.isEnum) {
    elemType = _enumDartType(f.enumTypeName!);
  } else {
    elemType = _scalarDartType(f.protoType);
  }
  b.writeln('  /// repeated `${f.protoName}`.');
  if (f.isMessage) {
    // Typed view over the stored list of sub-maps.
    b.writeln('  List<$elemType> get ${f.dartName} {');
    b.writeln("    final v = \$fields['$key'] as List?;");
    b.writeln('    if (v == null) return <$elemType>[];');
    b.writeln(
      '    return [for (final e in v) '
      '$elemType(e as Map<String, Object?>)];',
    );
    b.writeln('  }');
    b.writeln(
      '  set ${f.dartName}(List<$elemType> v) =>\n'
      "      \$fields['$key'] = [for (final e in v) e.\$fields];",
    );
  } else if (f.isEnum) {
    b.writeln('  List<$elemType> get ${f.dartName} {');
    b.writeln("    final v = \$fields['$key'] as List?;");
    b.writeln('    if (v == null) return <$elemType>[];');
    b.writeln('    return [for (final e in v) $elemType.fromValue(e as int)];');
    b.writeln('  }');
    b.writeln(
      '  set ${f.dartName}(List<$elemType> v) =>\n'
      "      \$fields['$key'] = [for (final e in v) e.value];",
    );
  } else {
    b.writeln(
      '  List<$elemType> get ${f.dartName} =>\n'
      "      (\$fields['$key'] as List?)?.cast<$elemType>() ?? <$elemType>[];",
    );
    b.writeln(
      "  set ${f.dartName}(List<$elemType> v) => \$fields['$key'] = v;",
    );
  }
  b.writeln();
}

void _emitMap(StringBuffer b, GenField f) {
  final key = f.protoName;
  final keyType = _scalarDartType(f.mapKeyType!);
  final String valType;
  if (f.mapValueType == 'TYPE_MESSAGE') {
    valType = _messageDartType(f.messageTypeName!);
  } else if (f.mapValueType == 'TYPE_ENUM') {
    valType = _enumDartType(f.enumTypeName!);
  } else {
    valType = _scalarDartType(f.mapValueType!);
  }
  b.writeln('  /// map `${f.protoName}`.');
  if (f.mapValueType == 'TYPE_MESSAGE') {
    b.writeln('  Map<$keyType, $valType> get ${f.dartName} {');
    b.writeln("    final v = \$fields['$key'] as Map?;");
    b.writeln('    if (v == null) return <$keyType, $valType>{};');
    b.writeln('    return {');
    b.writeln(
      '      for (final e in v.entries)\n'
      '        e.key as $keyType: '
      '$valType(e.value as Map<String, Object?>),',
    );
    b.writeln('    };');
    b.writeln('  }');
    b.writeln('  set ${f.dartName}(Map<$keyType, $valType> v) {');
    b.writeln('    \$fields[\'$key\'] = {');
    b.writeln('      for (final e in v.entries) e.key: e.value.\$fields,');
    b.writeln('    };');
    b.writeln('  }');
  } else if (f.mapValueType == 'TYPE_ENUM') {
    b.writeln('  Map<$keyType, $valType> get ${f.dartName} {');
    b.writeln("    final v = \$fields['$key'] as Map?;");
    b.writeln('    if (v == null) return <$keyType, $valType>{};');
    b.writeln('    return {');
    b.writeln(
      '      for (final e in v.entries)\n'
      '        e.key as $keyType: $valType.fromValue(e.value as int),',
    );
    b.writeln('    };');
    b.writeln('  }');
    b.writeln('  set ${f.dartName}(Map<$keyType, $valType> v) {');
    b.writeln('    \$fields[\'$key\'] = {');
    b.writeln('      for (final e in v.entries) e.key: e.value.value,');
    b.writeln('    };');
    b.writeln('  }');
  } else {
    b.writeln(
      '  Map<$keyType, $valType> get ${f.dartName} =>\n'
      "      (\$fields['$key'] as Map?)?.cast<$keyType, $valType>() ??\n"
      '      <$keyType, $valType>{};',
    );
    b.writeln(
      "  set ${f.dartName}(Map<$keyType, $valType> v) => \$fields['$key'] = v;",
    );
  }
  b.writeln();
}

// ---------------------------------------------------------------------------
// Descriptor registry emission
// ---------------------------------------------------------------------------

/// Emits the shared lazily-built descriptor registry plus the oneof-case enums
/// and the `$descriptorFor` / `$descriptorForOrNull` lookups every class uses.
void _emitDescriptorRegistry(StringBuffer b, GenFile file) {
  // Oneof-case enums (one per message oneof).
  for (final m in file.messages) {
    if (m.isMapEntry) continue;
    final oneofs = <String, List<GenField>>{};
    for (final f in m.fields) {
      if (f.oneofName != null) {
        oneofs.putIfAbsent(f.oneofName!, () => []).add(f);
      }
    }
    for (final entry in oneofs.entries) {
      final enumName = '${m.dartName}_${_pascal(entry.key)}Case';
      b.write('enum $enumName { ');
      b.write(entry.value.map((f) => f.dartName).join(', '));
      b.writeln(', notSet }');
      b.writeln();
    }
  }

  final rule = '// ${'-' * 73}';
  b.writeln(rule);
  b.writeln('// Resolved ball_protobuf descriptors (Editions features baked');
  b.writeln('// in). Built lazily so recursive message references terminate.');
  b.writeln(rule);
  b.writeln();
  b.writeln(
    'final Map<String, List<Map<String, Object?>>> \$descriptors = {};',
  );
  b.writeln();
  b.writeln(
    'final Map<String, List<Map<String, Object?>> Function()> '
    '\$descriptorBuilders = {',
  );
  for (final m in file.messages) {
    b.writeln("  '${m.fullName}': _build_${_safe(m.fullName)},");
  }
  b.writeln('};');
  b.writeln();
  b.writeln('/// Returns the resolved descriptor for [fullName], building it');
  b.writeln('/// (and memoizing it) on first use.');
  b.writeln('List<Map<String, Object?>> \$descriptorFor(String fullName) {');
  b.writeln('  final existing = \$descriptors[fullName];');
  b.writeln('  if (existing != null) return existing;');
  b.writeln('  final builder = \$descriptorBuilders[fullName];');
  b.writeln('  if (builder == null) {');
  b.writeln(
    "    throw StateError('No descriptor for \$fullName in "
    "${file.protoPath}');",
  );
  b.writeln('  }');
  b.writeln('  final fields = <Map<String, Object?>>[];');
  b.writeln('  \$descriptors[fullName] = fields; // publish before populating');
  b.writeln('  fields.addAll(builder());');
  b.writeln('  return fields;');
  b.writeln('}');
  b.writeln();
  b.writeln('/// Like [\$descriptorFor] but returns null for unknown types');
  b.writeln('/// (the Any/registry resolver shape the runtime expects).');
  b.writeln(
    'List<Map<String, Object?>>? \$descriptorForOrNull(String fullName) {',
  );
  b.writeln('  if (\$descriptorBuilders.containsKey(fullName)) {');
  b.writeln('    return \$descriptorFor(fullName);');
  b.writeln('  }');
  b.writeln('  return null;');
  b.writeln('}');
  b.writeln();

  // One builder function per message — emits its field-descriptor literals.
  for (final m in file.messages) {
    _emitDescriptorBuilder(b, m);
    b.writeln();
  }
}

void _emitDescriptorBuilder(StringBuffer b, GenMessage m) {
  b.writeln('List<Map<String, Object?>> _build_${_safe(m.fullName)}() => [');
  for (final field in m.descriptor) {
    b.write('  ');
    _writeFieldDescriptor(b, field);
    b.writeln(',');
  }
  b.writeln('];');
}

/// Writes a single field-descriptor map literal. Cross-references
/// (`messageDescriptor`) become `$descriptorFor('<fqn>')` lookups so the
/// emitted graph terminates on recursion.
void _writeFieldDescriptor(StringBuffer b, Map<String, Object?> field) {
  b.write('<String, Object?>{');
  var first = true;
  for (final entry in field.entries) {
    if (!first) b.write(', ');
    first = false;
    final k = entry.key;
    b.write("'$k': ");
    if (k == 'messageDescriptor') {
      // Resolve via the registry. The referenced message FQN is the field's
      // 'typeName' (for singular/repeated message fields) or 'valueTypeName'
      // (for map<K, message> fields).
      final ref =
          (field['valueTypeName'] as String?) ?? (field['typeName'] as String?);
      if (ref == null) {
        // No reference name (shouldn't happen) — emit null.
        b.write('null');
      } else {
        b.write("\$descriptorFor('$ref')");
      }
    } else {
      _writeDartLiteral(b, entry.value);
    }
  }
  b.write('}');
}

/// Writes [value] as a Dart literal. Handles the JSON-ish scalar/list/map shapes
/// the descriptor maps contain (`String`, `int`, `bool`, nested `Map`/`List`).
void _writeDartLiteral(StringBuffer b, Object? value) {
  if (value == null) {
    b.write('null');
  } else if (value is String) {
    b.write(_dartStringLiteral(value));
  } else if (value is bool) {
    b.write(value ? 'true' : 'false');
  } else if (value is int) {
    b.write(value.toString());
  } else if (value is double) {
    b.write(value.toString());
  } else if (value is Map) {
    b.write('<${_mapTypeArgs(value)}>{');
    var first = true;
    value.forEach((k, v) {
      if (!first) b.write(', ');
      first = false;
      _writeDartLiteral(b, k);
      b.write(': ');
      _writeDartLiteral(b, v);
    });
    b.write('}');
  } else if (value is List) {
    b.write('[');
    var first = true;
    for (final e in value) {
      if (!first) b.write(', ');
      first = false;
      _writeDartLiteral(b, e);
    }
    b.write(']');
  } else {
    throw ArgumentError(
      'Cannot emit descriptor literal for ${value.runtimeType}',
    );
  }
}

/// Picks the type arguments for a descriptor sub-map literal. The bridge uses
/// `Map<String, String>` for `'features'`, `Map<int, String>` for
/// `'enumValues'`, and `Map<String, int>` for `'enumNames'`.
String _mapTypeArgs(Map<dynamic, dynamic> m) {
  if (m.isEmpty) return 'String, String';
  final firstKey = m.keys.first;
  final firstVal = m.values.first;
  final kt = firstKey is int ? 'int' : 'String';
  final vt = firstVal is int ? 'int' : 'String';
  return '$kt, $vt';
}

String _dartStringLiteral(String s) {
  final escaped = s
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll('\n', r'\n')
      .replaceAll('\r', r'\r')
      .replaceAll(r'$', r'\$');
  return "'$escaped'";
}

// ---------------------------------------------------------------------------
// Type mapping helpers
// ---------------------------------------------------------------------------

/// The Dart type for a singular scalar protobuf [type].
String _scalarDartType(String type) {
  switch (type) {
    case 'TYPE_INT32':
    case 'TYPE_INT64':
    case 'TYPE_UINT32':
    case 'TYPE_UINT64':
    case 'TYPE_SINT32':
    case 'TYPE_SINT64':
    case 'TYPE_FIXED32':
    case 'TYPE_FIXED64':
    case 'TYPE_SFIXED32':
    case 'TYPE_SFIXED64':
      return 'int';
    case 'TYPE_FLOAT':
    case 'TYPE_DOUBLE':
      return 'double';
    case 'TYPE_BOOL':
      return 'bool';
    case 'TYPE_STRING':
      return 'String';
    case 'TYPE_BYTES':
      return 'List<int>';
    default:
      throw ArgumentError('Not a scalar protobuf type: $type');
  }
}

/// The default-value Dart expression for a singular scalar [type].
String _scalarDefault(String type) {
  switch (type) {
    case 'TYPE_FLOAT':
    case 'TYPE_DOUBLE':
      return '0.0';
    case 'TYPE_BOOL':
      return 'false';
    case 'TYPE_STRING':
      return "''";
    case 'TYPE_BYTES':
      return '<int>[]';
    default:
      return '0';
  }
}

/// Maps a message FQN to its flattened Dart class name.
String _messageDartType(String fqn) => _flattenName(fqn);

/// Maps an enum FQN to its flattened Dart class name.
String _enumDartType(String fqn) => _flattenName(fqn);

/// Flattens a (possibly cross-package, possibly nested) FQN to the Dart class
/// name used in the generated file. The package prefix is dropped and the
/// nested-type path is joined with `_` — matching [GenModelBuilder]'s naming.
String _flattenName(String fqn) {
  // Find the message/enum simple-name chain after the package. We can't know
  // the package boundary from the FQN alone, but the descriptor naming convention
  // joins all *type* segments (after the package) with `_`. The package segments
  // are lowercase-dotted; type segments start with an uppercase letter. Split on
  // '.' and keep the trailing run of segments whose first char is uppercase.
  final parts = fqn.split('.');
  final typeSegs = <String>[];
  for (var i = parts.length - 1; i >= 0; i--) {
    final p = parts[i];
    if (p.isNotEmpty &&
        p[0] == p[0].toUpperCase() &&
        p[0] != p[0].toLowerCase()) {
      typeSegs.insert(0, p);
    } else {
      break;
    }
  }
  if (typeSegs.isEmpty) return parts.last;
  return typeSegs.join('_');
}

/// PascalCase from a lowerCamel / snake identifier (for `whichX`, `hasX`).
String _pascal(String name) {
  if (name.isEmpty) return name;
  // If snake-cased, camelize first.
  final camel = name.contains('_') ? toLowerCamel(name) : name;
  return camel[0].toUpperCase() + camel.substring(1);
}

/// A FQN turned into a safe Dart identifier suffix (for builder fn names).
String _safe(String fqn) =>
    fqn.replaceAll('.', r'$').replaceAll(RegExp(r'[^A-Za-z0-9$_]'), '_');
