/// Regenerate `dart/self_host/cli.ball.json` (+ `.pb`) from the portable CLI
/// verbs in `dart/shared/lib/cli_core.dart`. This is the CLI counterpart of
/// `gen_engine_json.dart` (which self-encodes the engine): it encodes the
/// `cli_core` library into a Ball [Program] so the `info` / `validate` / `tree`
/// / `version` verbs execute on the Ball engine, byte-identical to the native
/// CLI (proven by `dart/cli/test/cli_core_parity_test.dart`).
///
///   cd dart && dart run compiler/tool/gen_cli_json.dart
///
/// Like `engine.ball.json`, the outputs are generated build artifacts kept out
/// of git (see `dart/self_host/.gitignore`) and regenerated by CI.
library;

import 'dart:convert';
import 'dart:io';

import 'package:ball_base/ball_base.dart'
    show encodeBallFileBinary, encodeBallFileJson;
import 'package:ball_encoder/encoder.dart';
import 'package:ball_encoder/parts_resolver.dart';

String _findRepoRoot() {
  var dir = Directory.current;
  while (true) {
    if (File('${dir.path}/proto/ball/v1/ball.proto').existsSync()) {
      return dir.path.replaceAll('\\', '/');
    }
    final parent = dir.parent;
    if (parent.path == dir.path) throw StateError('Not in ball repo');
    dir = parent;
  }
}

void main() {
  final root = _findRepoRoot();
  final mainPath = '$root/dart/shared/lib/cli_core.dart';
  stdout.writeln('Resolving parts + extensions...');
  final src = resolveDartLibrary(mainPath);
  stdout.writeln('  merged source: ${src.length} bytes');
  stdout.writeln('Encoding...');
  final prog = DartEncoder().encode(src, name: 'cli_core');
  stdout.writeln(
    '  ${prog.modules.length} modules, '
    '${prog.modules.fold<int>(0, (n, m) => n + m.functions.length)} fns, '
    '${prog.modules.fold<int>(0, (n, m) => n + m.typeDefs.length)} typeDefs',
  );

  final jsonMap = encodeBallFileJson(prog);
  final jsonStr = const JsonEncoder.withIndent('  ').convert(jsonMap);
  final jsonPath = '$root/dart/self_host/cli.ball.json';
  File(jsonPath).writeAsStringSync(jsonStr);
  stdout.writeln('Wrote ${jsonStr.length} bytes → $jsonPath');

  final bytes = encodeBallFileBinary(prog);
  final pbPath = '$root/dart/self_host/cli.ball.pb';
  File(pbPath).writeAsBytesSync(bytes);
  stdout.writeln('Wrote ${bytes.length} bytes → $pbPath');
}
