// GENERATED by dart/ball_protobuf/tool/gen_program_descriptor_cpp.dart
// DO NOT EDIT. Regenerate via:
//   dart run dart/ball_protobuf/tool/gen_program_descriptor_cpp.dart
//
// Minimal ball.v1 message descriptors for ball_protobuf_rt.h. Every
// google.protobuf.* field is an opaque TYPE_BYTES passthrough (a message
// and a bytes field are byte-identical on the wire), so the descriptor
// needs no descriptor.proto / struct.proto closure and round-trips the
// original bytes verbatim. See #18 Stage 3.
#pragma once

#include <any>
#include <map>
#include <string>

#include "ball_protobuf_rt.h"

namespace ball_protobuf {
namespace descriptor {

// Appends one field descriptor to message [msg]'s shared field list.
// [refType], when non-null, is a ball.v1.* FQN whose shared descriptor list
// is referenced (copied BallDyn shares the underlying vector -> recursion).
inline void _push(std::map<std::string, BallDyn>& r, const char* msg,
                  const char* name, long long number, const char* type,
                  const char* label, bool repeated, const char* refType,
                  const char* oneof, bool mapEntry,
                  const char* keyType, const char* valueType) {
  BallMap m;
  m["name"s] = std::any(std::string(name));
  m["number"s] = std::any(static_cast<int64_t>(number));
  m["type"s] = std::any(std::string(type));
  if (label) m["label"s] = std::any(std::string(label));
  if (repeated) m["repeated"s] = std::any(true);
  if (refType) {
    m["typeName"s] = std::any(std::string(refType));
    m["messageDescriptor"s] = std::any(r.at(refType));
  }
  if (oneof) m["oneof"s] = std::any(std::string(oneof));
  if (mapEntry) {
    m["mapEntry"s] = std::any(true);
    m["keyType"s] = std::any(std::string(keyType));
    m["valueType"s] = std::any(std::string(valueType));
  }
  r.at(msg)._listPtr()->push_back(std::any(BallDyn(std::move(m))));
}

// Builds the ball.v1 descriptor registry once (thread-safe static init).
inline const std::map<std::string, BallDyn>& _registry() {
  static const std::map<std::string, BallDyn> reg = [] {
    std::map<std::string, BallDyn> r;
    // Phase 1: one empty shared field-list per message.
    r["ball.v1.Block"] = BallDyn(BallList{});
    r["ball.v1.Constant"] = BallDyn(BallList{});
    r["ball.v1.Expression"] = BallDyn(BallList{});
    r["ball.v1.FieldAccess"] = BallDyn(BallList{});
    r["ball.v1.FieldValuePair"] = BallDyn(BallList{});
    r["ball.v1.FileSource"] = BallDyn(BallList{});
    r["ball.v1.FunctionCall"] = BallDyn(BallList{});
    r["ball.v1.FunctionDefinition"] = BallDyn(BallList{});
    r["ball.v1.GitSource"] = BallDyn(BallList{});
    r["ball.v1.HttpSource"] = BallDyn(BallList{});
    r["ball.v1.InlineSource"] = BallDyn(BallList{});
    r["ball.v1.LetBinding"] = BallDyn(BallList{});
    r["ball.v1.ListLiteral"] = BallDyn(BallList{});
    r["ball.v1.Literal"] = BallDyn(BallList{});
    r["ball.v1.MessageCreation"] = BallDyn(BallList{});
    r["ball.v1.Module"] = BallDyn(BallList{});
    r["ball.v1.ModuleAsset"] = BallDyn(BallList{});
    r["ball.v1.ModuleImport"] = BallDyn(BallList{});
    r["ball.v1.Program"] = BallDyn(BallList{});
    r["ball.v1.Reference"] = BallDyn(BallList{});
    r["ball.v1.RegistrySource"] = BallDyn(BallList{});
    r["ball.v1.Statement"] = BallDyn(BallList{});
    r["ball.v1.TypeAlias"] = BallDyn(BallList{});
    r["ball.v1.TypeDefinition"] = BallDyn(BallList{});
    r["ball.v1.TypeParameter"] = BallDyn(BallList{});
    r["ball.v1.TypeRef"] = BallDyn(BallList{});
    // Phase 2: populate fields (recursive refs share the lists above).
    _push(r, "ball.v1.Block", "statements", 1, "TYPE_MESSAGE", "LABEL_REPEATED", true, "ball.v1.Statement", nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.Block", "result", 2, "TYPE_MESSAGE", "LABEL_OPTIONAL", false, "ball.v1.Expression", nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.Constant", "name", 1, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.Constant", "type", 2, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.Constant", "value", 3, "TYPE_MESSAGE", "LABEL_OPTIONAL", false, "ball.v1.Expression", nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.Constant", "metadata", 4, "TYPE_BYTES", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.Expression", "call", 1, "TYPE_MESSAGE", "LABEL_OPTIONAL", false, "ball.v1.FunctionCall", "expr", false, nullptr, nullptr);
    _push(r, "ball.v1.Expression", "literal", 2, "TYPE_MESSAGE", "LABEL_OPTIONAL", false, "ball.v1.Literal", "expr", false, nullptr, nullptr);
    _push(r, "ball.v1.Expression", "reference", 3, "TYPE_MESSAGE", "LABEL_OPTIONAL", false, "ball.v1.Reference", "expr", false, nullptr, nullptr);
    _push(r, "ball.v1.Expression", "field_access", 4, "TYPE_MESSAGE", "LABEL_OPTIONAL", false, "ball.v1.FieldAccess", "expr", false, nullptr, nullptr);
    _push(r, "ball.v1.Expression", "message_creation", 5, "TYPE_MESSAGE", "LABEL_OPTIONAL", false, "ball.v1.MessageCreation", "expr", false, nullptr, nullptr);
    _push(r, "ball.v1.Expression", "block", 6, "TYPE_MESSAGE", "LABEL_OPTIONAL", false, "ball.v1.Block", "expr", false, nullptr, nullptr);
    _push(r, "ball.v1.Expression", "lambda", 7, "TYPE_MESSAGE", "LABEL_OPTIONAL", false, "ball.v1.FunctionDefinition", "expr", false, nullptr, nullptr);
    _push(r, "ball.v1.FieldAccess", "object", 1, "TYPE_MESSAGE", "LABEL_OPTIONAL", false, "ball.v1.Expression", nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.FieldAccess", "field", 2, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.FieldValuePair", "name", 1, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.FieldValuePair", "value", 2, "TYPE_MESSAGE", "LABEL_OPTIONAL", false, "ball.v1.Expression", nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.FileSource", "path", 1, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.FileSource", "encoding", 2, "TYPE_ENUM", "LABEL_OPTIONAL", false, "ball.v1.ModuleEncoding", nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.FunctionCall", "module", 1, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.FunctionCall", "function", 2, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.FunctionCall", "input", 3, "TYPE_MESSAGE", "LABEL_OPTIONAL", false, "ball.v1.Expression", nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.FunctionCall", "type_args", 4, "TYPE_MESSAGE", "LABEL_REPEATED", true, "ball.v1.TypeRef", nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.FunctionDefinition", "name", 1, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.FunctionDefinition", "input_type", 2, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.FunctionDefinition", "output_type", 3, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.FunctionDefinition", "body", 4, "TYPE_MESSAGE", "LABEL_OPTIONAL", false, "ball.v1.Expression", nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.FunctionDefinition", "description", 5, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.FunctionDefinition", "is_base", 6, "TYPE_BOOL", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.FunctionDefinition", "metadata", 7, "TYPE_BYTES", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.GitSource", "url", 1, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.GitSource", "ref", 2, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.GitSource", "path", 3, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.GitSource", "encoding", 4, "TYPE_ENUM", "LABEL_OPTIONAL", false, "ball.v1.ModuleEncoding", nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.HttpSource", "url", 1, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.HttpSource", "encoding", 2, "TYPE_ENUM", "LABEL_OPTIONAL", false, "ball.v1.ModuleEncoding", nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.HttpSource", "headers", 3, "TYPE_MESSAGE", "LABEL_REPEATED", true, nullptr, nullptr, true, "TYPE_STRING", "TYPE_STRING");
    _push(r, "ball.v1.InlineSource", "proto_bytes", 1, "TYPE_BYTES", "LABEL_OPTIONAL", false, nullptr, "content", false, nullptr, nullptr);
    _push(r, "ball.v1.InlineSource", "json", 2, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, "content", false, nullptr, nullptr);
    _push(r, "ball.v1.LetBinding", "name", 1, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.LetBinding", "value", 2, "TYPE_MESSAGE", "LABEL_OPTIONAL", false, "ball.v1.Expression", nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.LetBinding", "metadata", 3, "TYPE_BYTES", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.ListLiteral", "elements", 1, "TYPE_MESSAGE", "LABEL_REPEATED", true, "ball.v1.Expression", nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.Literal", "int_value", 1, "TYPE_INT64", "LABEL_OPTIONAL", false, nullptr, "value", false, nullptr, nullptr);
    _push(r, "ball.v1.Literal", "double_value", 2, "TYPE_DOUBLE", "LABEL_OPTIONAL", false, nullptr, "value", false, nullptr, nullptr);
    _push(r, "ball.v1.Literal", "string_value", 3, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, "value", false, nullptr, nullptr);
    _push(r, "ball.v1.Literal", "bool_value", 4, "TYPE_BOOL", "LABEL_OPTIONAL", false, nullptr, "value", false, nullptr, nullptr);
    _push(r, "ball.v1.Literal", "bytes_value", 5, "TYPE_BYTES", "LABEL_OPTIONAL", false, nullptr, "value", false, nullptr, nullptr);
    _push(r, "ball.v1.Literal", "list_value", 6, "TYPE_MESSAGE", "LABEL_OPTIONAL", false, "ball.v1.ListLiteral", "value", false, nullptr, nullptr);
    _push(r, "ball.v1.MessageCreation", "type_name", 1, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.MessageCreation", "fields", 2, "TYPE_MESSAGE", "LABEL_REPEATED", true, "ball.v1.FieldValuePair", nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.MessageCreation", "metadata", 3, "TYPE_BYTES", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.Module", "name", 1, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.Module", "enums", 7, "TYPE_BYTES", "LABEL_REPEATED", true, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.Module", "functions", 3, "TYPE_MESSAGE", "LABEL_REPEATED", true, "ball.v1.FunctionDefinition", nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.Module", "description", 5, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.Module", "metadata", 6, "TYPE_BYTES", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.Module", "module_imports", 4, "TYPE_MESSAGE", "LABEL_REPEATED", true, "ball.v1.ModuleImport", nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.Module", "type_defs", 8, "TYPE_MESSAGE", "LABEL_REPEATED", true, "ball.v1.TypeDefinition", nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.Module", "type_aliases", 11, "TYPE_MESSAGE", "LABEL_REPEATED", true, "ball.v1.TypeAlias", nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.Module", "module_constants", 12, "TYPE_MESSAGE", "LABEL_REPEATED", true, "ball.v1.Constant", nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.Module", "assets", 13, "TYPE_MESSAGE", "LABEL_REPEATED", true, "ball.v1.ModuleAsset", nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.ModuleAsset", "path", 1, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.ModuleAsset", "content", 2, "TYPE_BYTES", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.ModuleAsset", "media_type", 3, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.ModuleAsset", "metadata", 4, "TYPE_BYTES", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.ModuleImport", "name", 1, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.ModuleImport", "integrity", 2, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.ModuleImport", "metadata", 3, "TYPE_BYTES", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.ModuleImport", "http", 4, "TYPE_MESSAGE", "LABEL_OPTIONAL", false, "ball.v1.HttpSource", "source", false, nullptr, nullptr);
    _push(r, "ball.v1.ModuleImport", "file", 5, "TYPE_MESSAGE", "LABEL_OPTIONAL", false, "ball.v1.FileSource", "source", false, nullptr, nullptr);
    _push(r, "ball.v1.ModuleImport", "inline", 6, "TYPE_MESSAGE", "LABEL_OPTIONAL", false, "ball.v1.InlineSource", "source", false, nullptr, nullptr);
    _push(r, "ball.v1.ModuleImport", "git", 7, "TYPE_MESSAGE", "LABEL_OPTIONAL", false, "ball.v1.GitSource", "source", false, nullptr, nullptr);
    _push(r, "ball.v1.ModuleImport", "registry", 8, "TYPE_MESSAGE", "LABEL_OPTIONAL", false, "ball.v1.RegistrySource", "source", false, nullptr, nullptr);
    _push(r, "ball.v1.Program", "name", 1, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.Program", "version", 2, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.Program", "modules", 3, "TYPE_MESSAGE", "LABEL_REPEATED", true, "ball.v1.Module", nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.Program", "entry_module", 4, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.Program", "entry_function", 5, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.Program", "metadata", 6, "TYPE_BYTES", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.Reference", "name", 1, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.RegistrySource", "registry", 1, "TYPE_ENUM", "LABEL_OPTIONAL", false, "ball.v1.Registry", nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.RegistrySource", "package", 2, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.RegistrySource", "version", 3, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.RegistrySource", "module_path", 4, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.RegistrySource", "encoding", 5, "TYPE_ENUM", "LABEL_OPTIONAL", false, "ball.v1.ModuleEncoding", nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.RegistrySource", "registry_url", 6, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.Statement", "let", 1, "TYPE_MESSAGE", "LABEL_OPTIONAL", false, "ball.v1.LetBinding", "stmt", false, nullptr, nullptr);
    _push(r, "ball.v1.Statement", "expression", 2, "TYPE_MESSAGE", "LABEL_OPTIONAL", false, "ball.v1.Expression", "stmt", false, nullptr, nullptr);
    _push(r, "ball.v1.TypeAlias", "name", 1, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.TypeAlias", "target_type", 2, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.TypeAlias", "type_params", 3, "TYPE_MESSAGE", "LABEL_REPEATED", true, "ball.v1.TypeParameter", nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.TypeAlias", "metadata", 4, "TYPE_BYTES", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.TypeDefinition", "name", 1, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.TypeDefinition", "descriptor", 2, "TYPE_BYTES", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.TypeDefinition", "type_params", 3, "TYPE_MESSAGE", "LABEL_REPEATED", true, "ball.v1.TypeParameter", nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.TypeDefinition", "description", 4, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.TypeDefinition", "metadata", 5, "TYPE_BYTES", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.TypeParameter", "name", 1, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.TypeParameter", "metadata", 2, "TYPE_BYTES", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.TypeRef", "name", 1, "TYPE_STRING", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.TypeRef", "type_args", 2, "TYPE_MESSAGE", "LABEL_REPEATED", true, "ball.v1.TypeRef", nullptr, false, nullptr, nullptr);
    _push(r, "ball.v1.TypeRef", "nullable", 3, "TYPE_BOOL", "LABEL_OPTIONAL", false, nullptr, nullptr, false, nullptr, nullptr);
    return r;
  }();
  return reg;
}

// The ball.v1.Program descriptor (shared list — cheap to copy).
inline BallDyn programDescriptor() { return _registry().at("ball.v1.Program"); }

// The ball.v1.Module descriptor.
inline BallDyn moduleDescriptor() { return _registry().at("ball.v1.Module"); }

}  // namespace descriptor
}  // namespace ball_protobuf
