// Command regen regenerates go/cli/compiled/compiled_cli.go from the self-hosted
// Ball CLI core (dart/self_host/cli.ball.pb) — the Go cli-core adoption route
// (issue #570), mirroring rust/cli/tool/src/main.rs, csharp/cli/tool, and
// go/engine/cmd/regen.
//
// Pipeline: read cli.ball.pb (a google.protobuf.Any envelope wrapping the
// ball.v1.Program; falls back to cli.ball.json, whose @type envelope the JSON
// loader strips), unpack to a typed Program, compile via compiler.CompileLibrary
// in package `compiled` (library shape — cli_core has no runnable entry point;
// its public surface is the infoReport/validateReport/treeReport/versionLine
// report functions), gofmt, and write with a NEVER-edit header.
//
// compiled_cli.go is a GENERATED, NEVER-edit build artifact that is TRACKED in
// git (issue #586) and diffed by ci.yml's `Ball Artifact Freshness` job — fix
// dart/shared/lib/cli_core.dart (then rerun gen_cli_json.dart) or go/compiler,
// rerun this, and commit the result.
//
// Until #586 this command also REWROTE the `//go:build selfhost` constraint
// compiler.CompileLibrary stamped onto every library it emitted into cli-core's
// own `//go:build clicore`. CompileLibrary now emits no constraint at all (both
// generated artifacts are tracked and must build everywhere, since `go install`
// accepts no `-tags`), so there is nothing left to rewrite.
//
// Usage:  cd go/cli && go run ./cmd/regen
package main

import (
	"fmt"
	"os"
	"path/filepath"

	compiler "github.com/ball-lang/ball/go/compiler"
	ballv1 "github.com/ball-lang/ball/go/shared/gen/ball/v1"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/anypb"
)

const header = `// Code generated by ` + "`go run ./cmd/regen`" + ` from dart/self_host/cli.ball.pb.
//
// DO NOT EDIT BY HAND. This is the self-hosted Ball CLI core (the info/validate/
// tree/version report functions), compiled from dart/shared/lib/cli_core.dart's
// own Ball encoding through the Ball -> Go compiler. To change it, fix
// dart/shared/lib/cli_core.dart (then rerun gen_cli_json.dart) or go/compiler,
// rerun the regenerator, and COMMIT the result — this file is tracked and CI
// diffs it (issue #586). See go/cli/AGENTS.md.

`

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "[regen-cli]", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := findRepoRoot()
	if err != nil {
		return err
	}
	pbPath := filepath.Join(root, "dart", "self_host", "cli.ball.pb")
	jsonPath := filepath.Join(root, "dart", "self_host", "cli.ball.json")
	outPath := filepath.Join(root, "go", "cli", "compiled", "compiled_cli.go")

	program, err := loadProgram(pbPath, jsonPath)
	if err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "[regen-cli] compiling program %q v%s (%d modules)\n",
		program.GetName(), program.GetVersion(), len(program.GetModules()))

	src, compileErr := compiler.CompileLibrary(program, "compiled")

	// Try to gofmt; if the emitted Go is not yet valid (a compiler gap), write
	// the raw source so it can be inspected, and surface the error.
	out := src
	if formatted, ferr := compiler.Format(src); ferr == nil {
		out = formatted
	} else {
		fmt.Fprintf(os.Stderr, "[regen-cli] gofmt failed (emitted Go not yet valid): %v\n", ferr)
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(outPath, []byte(header+out), 0o644); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "[regen-cli] wrote %s (%d bytes)\n", outPath, len(header)+len(out))

	if compileErr != nil {
		return fmt.Errorf("compile reported unsupported constructs:\n%w", compileErr)
	}
	return nil
}

func loadProgram(pbPath, jsonPath string) (*ballv1.Program, error) {
	if data, err := os.ReadFile(pbPath); err == nil {
		fmt.Fprintf(os.Stderr, "[regen-cli] loading %s\n", pbPath)
		var any anypb.Any
		if err := proto.Unmarshal(data, &any); err == nil {
			var program ballv1.Program
			if err := any.UnmarshalTo(&program); err == nil {
				return &program, nil
			}
		}
		// A bare (non-Any) Program binary.
		return compiler.LoadProgramBinary(data)
	}
	data, err := os.ReadFile(jsonPath)
	if err != nil {
		return nil, fmt.Errorf("neither %s nor %s is readable; regenerate the self-host source first "+
			"(cd dart && dart run compiler/tool/gen_cli_json.dart): %w", pbPath, jsonPath, err)
	}
	fmt.Fprintf(os.Stderr, "[regen-cli] loading %s\n", jsonPath)
	return compiler.LoadProgramJSON(data)
}

func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "proto", "ball", "v1", "ball.proto")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("not inside the ball repo (no proto/ball/v1/ball.proto found)")
		}
		dir = parent
	}
}
