// Generated by ball compiler
// Source: encoded v1.0.0
// Target: Dart

void main() {
  var a = 10;
  var b = 3;
  print(((a + b)).toString());
  print(((a - b)).toString());
  print(((a * b)).toString());
  print(((a ~/ b)).toString());
  print(((a % b)).toString());
}
