// Generated by ball compiler
// Source: encoded v1.0.0
// Target: Dart

int add(int a, int b) => (a + b);
int square(int input) {
  final int x = input;
  return (x * x);
}

void main() {
  print((add(2, 3)).toString());
  print(square(7).toString());
}
