// Generated by ball compiler
// Source: encoded v1.0.0
// Target: Dart

int triple(int input) {
  int x = input;
  return (x * 3);
}

int addOne(int input) {
  int x = input;
  return (x + 1);
}

int pipeline(int input) {
  int x = input;
  return triple(addOne(triple(x)));
}

void main() {
  print(pipeline(2).toString());
  print(pipeline(0).toString());
  print(triple(triple(triple(1))).toString());
}
