// Generated by ball compiler
// Source: encoded v1.0.0
// Target: Dart

void main() {
  var s = '  hello world  ';
  print(s.trim());
  print('abc'.toUpperCase());
  print('XYZ'.toLowerCase());
  print('padme'.length.toString());
  print((('a' + 'b') + 'c'));
}
