// Generated by ball compiler
// Source: encoded v1.0.0
// Target: Dart

int sumTo(int input) {
  final int n = input;
  if ((n <= 0)) {
    return 0;
  }
  return (n + sumTo((n - 1)));
}

int power(int base, int exp) {
  if ((exp == 0)) {
    return 1;
  }
  return (base * power(base, (exp - 1)));
}

void main() {
  print(sumTo(10).toString());
  print(sumTo(100).toString());
  print(power(2, 10).toString());
  print(power(3, 4).toString());
}
