// Generated by ball compiler
// Source: encoded v1.0.0
// Target: Dart

int fib(int input) {
  int n = input;
  if ((n <= 1)) {
    return n;
  }
  return (fib((n - 1)) + fib((n - 2)));
}

void main() {
  for (int i = 0; (i < 8); i++) {
    print(fib(i).toString());
  }
}
