// Generated by ball compiler
// Source: encoded v1.0.0
// Target: Dart

void main() {
  try {
    throw 'boom';
  } catch (__ball_e, stack) {
    final e = __ball_e;
    print(e.toString());
    print(((stack.toString().length > 0) ? 'has-stack' : 'no-stack'));
  }
}
