# EmbedRuntimeHeader.cmake — reads `IN` and writes `OUT` as a C++ header
# that exports the input's contents as a string constant.
#
# Invoked via `cmake -DIN=... -DOUT=... -P EmbedRuntimeHeader.cmake`.
#
# The output contains a single `constexpr const char*` named
# BALL_EMIT_RUNTIME_SOURCE plus a length constant. The compiler splices
# this string into the preamble of every emitted C++ program so the
# runtime helpers have one canonical source.

if(NOT DEFINED IN OR NOT DEFINED OUT)
    message(FATAL_ERROR "EmbedRuntimeHeader.cmake requires -DIN=... -DOUT=...")
endif()

file(READ "${IN}" RUNTIME_SOURCE)

# Pick a raw-string delimiter that isn't present in the source. `BALL_RT(`
# / `)BALL_RT"` is extremely unlikely to appear in the runtime header.
if(RUNTIME_SOURCE MATCHES "\\)BALL_RT\"")
    message(FATAL_ERROR "Runtime source contains the raw-string delimiter")
endif()

file(WRITE "${OUT}"
"// GENERATED by EmbedRuntimeHeader.cmake from ball_emit_runtime.h
// DO NOT EDIT — edit ball_emit_runtime.h instead and rebuild.
//
// The compiler splices BALL_EMIT_RUNTIME_SOURCE into the preamble of
// every emitted C++ program, so the runtime helpers live in exactly
// one source file.
#pragma once

namespace ball {
inline constexpr const char* BALL_EMIT_RUNTIME_SOURCE = R\"BALL_RT(${RUNTIME_SOURCE})BALL_RT\";
}  // namespace ball
")
