# EmbedRuntimeHeader.cmake — reads `IN` and writes `OUT` as a C++ header
# that exports the input's contents as a string constant.
#
# Invoked via `cmake -DIN=... -DOUT=... [-DVAR_NAME=...] -P EmbedRuntimeHeader.cmake`.
#
# The output contains a single `constexpr const char*` named
# BALL_EMIT_RUNTIME_SOURCE (or VAR_NAME if provided) plus the source content.
# The compiler splices this string into the preamble of every emitted C++
# program so the runtime helpers have one canonical source.
#
# MSVC limits raw string literals to 16380 characters, so the source is
# split into chunks that are concatenated at compile time.

if(NOT DEFINED IN OR NOT DEFINED OUT)
    message(FATAL_ERROR "EmbedRuntimeHeader.cmake requires -DIN=... -DOUT=...")
endif()

if(NOT DEFINED VAR_NAME)
    set(VAR_NAME "BALL_EMIT_RUNTIME_SOURCE")
endif()

file(READ "${IN}" RUNTIME_SOURCE)

# Pick a raw-string delimiter that isn't present in the source. `BALL_RT(`
# / `)BALL_RT"` is extremely unlikely to appear in the runtime header.
if(RUNTIME_SOURCE MATCHES "\\)BALL_RT\"")
    message(FATAL_ERROR "Runtime source contains the raw-string delimiter")
endif()

# MSVC has a 16380 character limit for string literals. Split the source
# into chunks of ~14000 characters to stay within the limit. Adjacent
# raw string literals concatenate in C++.
string(LENGTH "${RUNTIME_SOURCE}" SRC_LEN)
set(CHUNK_SIZE 14000)
set(CHUNKS "")
set(POS 0)
while(POS LESS SRC_LEN)
    string(SUBSTRING "${RUNTIME_SOURCE}" ${POS} ${CHUNK_SIZE} CHUNK)
    string(APPEND CHUNKS "R\"BALL_RT(${CHUNK})BALL_RT\"\n")
    math(EXPR POS "${POS} + ${CHUNK_SIZE}")
endwhile()

file(WRITE "${OUT}"
"// GENERATED by EmbedRuntimeHeader.cmake
// DO NOT EDIT — edit the source file instead and rebuild.
//
// The source is split into chunks because MSVC limits raw string
// literals to 16380 characters.
#pragma once

namespace ball {
inline constexpr const char* ${VAR_NAME} =
${CHUNKS};
}  // namespace ball
")
