//! `ball version` — print the CLI's version (issue #365).
//!
//! VERSION POLICY (issue #366): `ball version` reports the ECOSYSTEM package
//! version — the crates.io `ball-lang-cli` version, i.e. the cargo workspace
//! version via `CARGO_PKG_VERSION`. This is the deliberate cross-target
//! decision: each CLI stays true to its own registry (crates.io for Rust,
//! npm's semantic-release line for TypeScript, the pubspec version for Dart),
//! rather than carrying a shared toolchain string. See rust/AGENTS.md
//! § Publishing.
//!
//! Single-sourced from `Cargo.toml` (`CARGO_PKG_VERSION`, the same value
//! `clap`'s own `--version`/`-V` flag reports via `#[command(version)]` in
//! `main.rs`) — mirrors the Dart CLI's single-sourcing of `ball version` off
//! `pubspec.yaml` (`dart/cli/tool/gen_version.dart`, issue #363).
//!
//! Unlike `info`/`validate`/`tree`, this subcommand is **not** gated behind
//! the `cli_core` feature: `cli_core::versionLine`'s entire logic is
//! `"ball " + version` (see `dart/shared/lib/cli_core.dart`), a Program-free,
//! one-line format. Duplicating that single line here keeps `ball version`
//! working in every build (matching `clap`'s always-on `--version`), while
//! still calling the *actual* compiled `versionLine` when `cli_core` is built
//! in — [`tests::compiled_version_line_matches_dart_cli_core_format`] below
//! proves the two are identical for every input, and
//! `tests/cli_general.rs`'s `version_subcommand_prints_ball_prefixed_crate_version_and_exits_0`
//! proves the fallback matches the real crate version end-to-end.
const VERSION: &str = env!("CARGO_PKG_VERSION");

pub fn version() {
    println!("{}", version_line());
}

#[cfg(feature = "cli_core")]
fn version_line() -> String {
    use ball_lang_shared::BallValue;
    crate::compiled_cli::versionLine(BallValue::String(VERSION.to_string())).to_string()
}

#[cfg(not(feature = "cli_core"))]
fn version_line() -> String {
    format!("ball {VERSION}")
}

#[cfg(all(test, feature = "cli_core"))]
mod tests {
    use ball_lang_shared::BallValue;

    /// Mirrors `dart/cli/test/cli_core_parity_test.dart`'s `versionReport`
    /// test — the same three representative version strings, checked
    /// against the compiled `cli_core.versionLine`'s Rust translation
    /// (`src/compiled_cli.rs`, generated by `cargo run -p ball-cli-regen`)
    /// rather than the Dart-engine-run program the Dart test uses (Rust has
    /// no live self-hosted-engine comparison available — see
    /// `tests/cli_core_parity.rs`'s module doc comment).
    #[test]
    fn compiled_version_line_matches_dart_cli_core_format() {
        for v in ["0.3.0+6", "1.0.0", "0.1.0"] {
            let got = crate::compiled_cli::versionLine(BallValue::String(v.to_string()));
            assert_eq!(got.to_string(), format!("ball {v}"));
        }
    }
}
