#!/usr/bin/env node
/**
 * Ball CLI — command-line interface for the Ball programming language.
 *
 * Commands:
 *   ball run <program.ball.json>               Execute a Ball program.
 *   ball audit <program.ball.json>             Static capability analysis.
 *   ball --version                             Print version.
 *   ball --help                                Print usage.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  analyzeCapabilities,
  checkPolicy,
  formatCapabilityReport,
  type Program,
} from './capability_analyzer.ts';

// `@ball-lang/engine` (compiled_engine.ts) and `./cli_core.ts`
// (compiled_cli.ts) are BOTH auto-generated by compiling a self-hosted Ball
// program through `@ball-lang/compiler`, and each installs its own runtime
// preamble as a side effect of module evaluation — including monkey-patching
// shared native prototypes (`Map.prototype.get`/`entries`/`keys`/`values`).
// That patching is idempotent against being installed *once*, but NOT against
// a second, independently-compiled preamble installing on top of it: the
// second artifact's "capture the native method before shadowing it" step
// actually captures the FIRST artifact's already-shadowed version, and a
// later call against a genuine native Map throws ("Method Map.prototype.entries
// called on incompatible receiver"). Every `ball` invocation is a fresh,
// single-command process, so the fix is to never let both load in the same
// one: import each compiled engine LAZILY, only inside the command handler
// that actually needs it (`cmdRun` / the info-validate-tree-version handlers
// below), instead of eagerly at module top level.
type EngineModule = typeof import('@ball-lang/engine');
type CliCoreModule = typeof import('./cli_core.ts');

const VERSION = readVersion();

const USAGE = `ball — the Ball language CLI (v${VERSION})

USAGE
  ball <command> [options]

COMMANDS
  run <program.ball.json>        Execute a Ball program and print stdout.
  info <program.ball.json>       Inspect ball program structure.
  validate <program.ball.json>   Check ball program validity.
  tree <program.ball.json>       Print module/import structure.
  audit <program.ball.json>      Static capability analysis (I/O, fs, network, ...).
  version                        Print version.

OPTIONS
  -h, --help                     Print this help message.
  -v, --version                  Print version information.

AUDIT OPTIONS
  --output <path>                Write the JSON report to <path>.
  --deny <caps>                  Comma-separated capabilities to deny
                                 (e.g. 'fs,network,process'). Exit 1 on violation.
  --reachable-only               Only analyze functions reachable from the entry.
  --json                         Emit JSON report to stdout (instead of text).

EXAMPLES
  ball run examples/hello_world/hello_world.ball.json
  ball audit my_program.ball.json
  ball audit my_program.ball.json --deny fs,network
  ball audit my_program.ball.json --output report.json --json
`;

type ParsedArgs = {
  command?: string;
  positional: string[];
  flags: Record<string, string | true>;
};

function parseArgs(argv: string[]): ParsedArgs {
  const flags: Record<string, string | true> = {};
  const positional: string[] = [];
  let command: string | undefined;

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i]!;

    if (arg === '--') {
      for (let j = i + 1; j < argv.length; j++) positional.push(argv[j]!);
      break;
    }

    if (arg.startsWith('--')) {
      const eq = arg.indexOf('=');
      if (eq >= 0) {
        const key = arg.substring(2, eq);
        flags[key] = arg.substring(eq + 1);
      } else {
        const key = arg.substring(2);
        const next = argv[i + 1];
        if (next !== undefined && !next.startsWith('-')) {
          flags[key] = next;
          i++;
        } else {
          flags[key] = true;
        }
      }
      continue;
    }

    if (arg.startsWith('-') && arg.length > 1) {
      const short = arg.substring(1);
      flags[short] = true;
      continue;
    }

    if (command === undefined) {
      command = arg;
    } else {
      positional.push(arg);
    }
  }

  return { command, positional, flags };
}

function readVersion(): string {
  // package.json lives one directory up from either dist/ or src/.
  try {
    const here = dirname(fileURLToPath(import.meta.url));
    const pkgPath = join(here, '..', 'package.json');
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8')) as { version?: string };
    if (typeof pkg.version === 'string') return pkg.version;
  } catch {
    // Pure packaging defense (a missing/malformed package.json next to a
    // real install or build) — not exercised by any test. Honestly
    // triggering it needs an isolated copy of this whole directory minus
    // its sibling package.json, with @ball-lang/engine's module
    // resolution still working from there; not worth the fragility for
    // a fallback this deep. Documented exclusion, not a coverage gap.
  }
  return '0.0.0';
}

function loadProgram(path: string): Program {
  let raw: string;
  try {
    raw = readFileSync(path, 'utf8');
  } catch (e) {
    const err = e as NodeJS.ErrnoException;
    if (err.code === 'ENOENT') {
      fail(`File not found: ${path}`);
    }
    fail(`Could not read ${path}: ${err.message}`);
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (e) {
    const err = e as Error;
    fail(`Invalid JSON in ${path}: ${err.message}`);
  }
  try {
    return unwrapBallFile(parsed) as Program;
  } catch (e) {
    const err = e as Error;
    fail(`Invalid ball file ${path}: ${err.message}`);
  }
}

/**
 * Ball files are self-describing `google.protobuf.Any` envelopes. Strip the
 * `@type` key (if present) to recover the bare proto3-JSON Program; bare
 * Program objects without `@type` pass through unchanged.
 */
function unwrapBallFile(json: unknown): unknown {
  if (json === null || typeof json !== 'object' || Array.isArray(json)) return json;
  const obj = json as Record<string, unknown>;
  const type = obj['@type'];
  if (type === undefined) return json;
  const ok =
    typeof type === 'string' &&
    (type.endsWith('/ball.v1.Program') || type.endsWith('/ball.v1.Module'));
  if (!ok) throw new Error(`unknown ball file @type: ${JSON.stringify(type)}`);
  const body: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) {
    if (k !== '@type') body[k] = v;
  }
  return body;
}

/**
 * Abort the current command with a user-facing error. Thrown (not
 * process.exit) so the entrypoint can set process.exitCode and let the
 * process drain naturally — a hard exit() discards buffered stdout/stderr
 * pipe writes, truncating program output mid-stream (issue #138).
 */
class CliError extends Error {}

function fail(message: string): never {
  throw new CliError(message);
}

async function cmdRun(args: ParsedArgs): Promise<number> {
  const programPath = args.positional[0];
  if (!programPath) {
    process.stderr.write('ball: run requires a program path\n\n');
    process.stderr.write(USAGE);
    return 1;
  }

  const { BallEngine }: EngineModule = await import('@ball-lang/engine');
  const program = loadProgram(programPath);
  const engine = new BallEngine(program as any, {
    stdout: (msg: string) => process.stdout.write(msg + '\n'),
    stderr: (msg: string) => process.stderr.write(msg + '\n'),
  });

  // run() is async (Promise<string[]>). Without the await, process.exit(0)
  // fired before the program executed — `ball run` printed NOTHING and
  // swallowed runtime errors as unhandled rejections (issue #138).
  try {
    await engine.run();
  } catch (e) {
    const err = e as Error;
    fail(`runtime error: ${err.message}`);
  }
  return 0;
}

// ── info / validate / tree ──────────────────────────────────────────────────
//
// All three delegate their report text to `cli_core.ts` (a thin wrapper over
// `compiled_cli.ts`, compiled from `dart/shared/lib/cli_core.dart` — see
// CLAUDE.md's "Regenerate compiled TS CLI core" recipe), so the computed
// output is byte-identical to the native Dart CLI's (proven by
// `test/cli_core_parity_test.ts`). Only argv parsing / usage-error text stays
// TS-local, matching `cmdRun`/`cmdAudit`'s existing style.

async function cmdInfo(args: ParsedArgs): Promise<number> {
  const programPath = args.positional[0];
  if (!programPath) {
    process.stderr.write('ball: info requires a program path\n\n');
    process.stderr.write(USAGE);
    return 1;
  }

  const cliCore: CliCoreModule = await import('./cli_core.ts');
  const program = loadProgram(programPath);
  process.stdout.write(cliCore.infoReport(program) + '\n');
  return 0;
}

async function cmdValidate(args: ParsedArgs): Promise<number> {
  const programPath = args.positional[0];
  if (!programPath) {
    process.stderr.write('ball: validate requires a program path\n\n');
    process.stderr.write(USAGE);
    return 1;
  }

  const cliCore: CliCoreModule = await import('./cli_core.ts');
  const program = loadProgram(programPath);
  const report = cliCore.validateReport(program);
  if (cliCore.validateOk(program)) {
    process.stdout.write(report + '\n');
    return 0;
  }
  process.stderr.write(report + '\n');
  return 1;
}

async function cmdTree(args: ParsedArgs): Promise<number> {
  const programPath = args.positional[0];
  if (!programPath) {
    process.stderr.write('ball: tree requires a program path\n\n');
    process.stderr.write(USAGE);
    return 1;
  }

  const cliCore: CliCoreModule = await import('./cli_core.ts');
  const program = loadProgram(programPath);
  process.stdout.write(cliCore.treeReport(program) + '\n');
  return 0;
}

async function cmdVersion(): Promise<number> {
  const cliCore: CliCoreModule = await import('./cli_core.ts');
  process.stdout.write(`${cliCore.versionLine(VERSION)}\n`);
  return 0;
}

function cmdAudit(args: ParsedArgs): number {
  const programPath = args.positional[0];
  if (!programPath) {
    process.stderr.write('ball: audit requires a program path\n\n');
    process.stderr.write(USAGE);
    return 1;
  }

  const program = loadProgram(programPath);
  const reachableOnly = args.flags['reachable-only'] === true;
  const report = analyzeCapabilities(program, { reachableOnly });

  const denyRaw = args.flags['deny'];
  const denySet =
    typeof denyRaw === 'string'
      ? new Set(
          denyRaw
            .split(',')
            .map((c) => c.trim())
            .filter((c) => c.length > 0),
        )
      : new Set<string>();

  const outputPath = args.flags['output'];
  if (typeof outputPath === 'string') {
    try {
      writeFileSync(outputPath, JSON.stringify(report, null, 2) + '\n');
    } catch (e) {
      const err = e as Error;
      fail(`could not write ${outputPath}: ${err.message}`);
    }
  }

  const asJson = args.flags['json'] === true;
  if (asJson) {
    process.stdout.write(JSON.stringify(report, null, 2) + '\n');
  } else {
    process.stdout.write(formatCapabilityReport(report));
  }

  if (denySet.size > 0) {
    const violations = checkPolicy(report, denySet);
    if (violations.length > 0) {
      process.stderr.write('\nPolicy violations:\n');
      for (const v of violations) process.stderr.write(`  - ${v}\n`);
      return 1;
    }
  }

  return 0;
}

async function main(argv: string[]): Promise<number> {
  const args = parseArgs(argv);

  if (args.flags['help'] === true || args.flags['h'] === true) {
    process.stdout.write(USAGE);
    return 0;
  }

  if (args.flags['version'] === true || args.flags['v'] === true) {
    // Matches the Dart CLI's `version`/`--version`/`-v` cases (all three
    // dispatch to the same `cli_core.versionLine`) — see the `case 'version'`
    // branch below for the bare-command spelling.
    return await cmdVersion();
  }

  switch (args.command) {
    case 'run':
      return await cmdRun(args);
    case 'info':
      return await cmdInfo(args);
    case 'validate':
      return await cmdValidate(args);
    case 'tree':
      return await cmdTree(args);
    case 'audit':
      return cmdAudit(args);
    case 'version':
      return await cmdVersion();
    case undefined:
      process.stdout.write(USAGE);
      return 0;
    default:
      process.stderr.write(`ball: unknown command '${args.command}'\n\n`);
      process.stderr.write(USAGE);
      return 1;
  }
}

// Set exitCode instead of process.exit(): a hard exit drops whatever part
// of the engine's output is still buffered in the stdout pipe (the fib
// test saw "0 1 1 2" of 8 lines). With exitCode the process exits when
// the event loop drains, after all writes flush.
try {
  process.exitCode = await main(process.argv.slice(2));
} catch (e) {
  if (e instanceof CliError) {
    process.stderr.write(`ball: ${e.message}\n`);
    process.exitCode = 1;
  } else {
    throw e;
  }
}
