// Package compiled holds the self-hosted Ball engine compiled from
// dart/self_host/engine.ball.pb through the Ball → Go compiler (epic #426
// Phase 4).
//
// The generated compiled_engine.go is a TRACKED build artifact (issue #586),
// regenerated by `go run ./cmd/regen` and gated by ci.yml's `Ball Artifact
// Freshness` regen-and-diff job — the same contract ts/engine's
// compiled_engine.ts has had since #517. It carries no build constraint: it used
// to be gitignored and `selfhost`-tagged, but `go install` accepts no `-tags`
// and the module a proxy serves is the repository AT THE TAG, so a
// registry-acquired `ball` could not run a single program (#586). Rust and C#
// keep their `self_host` feature / `-p:SelfHost=true` property because their
// registry channels regenerate at publish time; Go has no such step.
package compiled
