//! `ball-engine` — runs Ball programs via the self-hosted engine (issue #39).
//!
//! ## Design: self-host, mirroring the TS/C++ targets
//!
//! Rather than hand-writing a tree-walking interpreter, `ball-engine` follows
//! the recommended self-hosting route (see
//! `.claude/skills/new-ball-language/SKILL.md` Phase 4, Option B): the
//! reference engine is itself a Ball program
//! (`dart/self_host/engine.ball.json`), which `ball-engine-regen`
//! (`rust/engine/tool/`) compiles through `ball-compiler` into
//! `src/compiled_engine.rs`. A thin wrapper (this crate) then supplies what
//! compiled Ball can't express natively:
//! - loading a target [`Program`] from proto3-JSON `.ball.json` or binary
//!   `.ball.bin` and viewing it as the canonical proto3-JSON [`BallValue`] the
//!   compiled engine reads ([`loader`]);
//! - the `ball_proto` access-pattern functions the compiled engine calls to
//!   inspect that program — oneof discriminators, presence checks, safe field
//!   access ([`ball_proto`]);
//! - the lexical [`scope`] chain and [`scope::FlowSignal`] flow signals;
//! - virtual properties ([`ball_proto::virtual_property`]).
//!
//! `src/compiled_engine.rs` is a **generated, NEVER-edit** file — regenerate
//! it with `cargo run -p ball-engine-regen`, never hand-patch it.
//!
//! ## Self-host status (#39/#298/#300)
//!
//! The self-hosted engine compiles cleanly **and RUNS** (`cargo build -p
//! ball-engine --features self_host`; the `self_host_run` integration tests).
//! Issue #300 wired the base-function runtime surface — `ball_proto.*`
//! AST-inspection, `std.map_create`/`record`/`typed_list`/`switch_expr`/…,
//! `std_collections`/`std_convert`, and the class-hierarchy/wrapper-class
//! plumbing — so [`BallEngine::run`] (under `self_host`) constructs the compiled
//! `main_BallEngine`, registers the `StdModuleHandler`, drives its `run`, and
//! produces output **identical to the Dart reference engine**: `hello_world`
//! prints `Hello, World!` and recursive `fibonacci(10)` prints `55`. The key
//! enablers beyond the base-function dispatch were reference-`this` (#298),
//! control-flow-through-`try` (`return`/`break`/`continue` escape a `try`'s
//! `catch_unwind` closure via `ball_shared::runtime::BallFlow`), the
//! method/constructor field write-back-on-early-`return` IIFE, and a large-stack
//! run thread. The default build (no `self_host`) still returns
//! [`EngineError::SelfHostPending`].
//!
//! **Corpus status (#39/#300): see `rust/engine/AGENTS.md` for the current
//! tally and per-bucket categorization** (this comment does not track it). The
//! loop-scope, string-surface, and reference-semantic-`List` blockers are
//! **resolved**:
//! - Loop counters now persist. The engine routes `i++`/`i--` through a Dart
//!   `switch` whose increment/decrement labels *fall through* to one shared
//!   body; the Rust compiler lowered `switch` to an if-chain that gave each
//!   body-less fall-through label an empty arm, so three of the four
//!   increment/decrement functions silently no-op'd and every `for`/`while`
//!   loop spun forever. `compile_switch` now implements fall-through, so
//!   loops/recursion-with-loops/closures run (`self_host_run` acceptance tests).
//! - String/field access works. The engine reads `FieldAccess.field` via the
//!   Dart-renamed getter `.field_2`; `ball_field_get` now aliases that (and
//!   `descriptor_`) back to the proto key, and the loader materializes proto3
//!   defaults (`skip_default_fields(false)`) so an empty list literal `[]` no
//!   longer reads back as `null`.
//!
//! **Reference-semantic `List` (issues #39/#300) — DONE.** Dart's `List` is a
//! reference type: the engine mutates a list passed as a function argument
//! (`_addCollectionElement(element, scope, result)` appends to `result`), and
//! `BallValue::List` now shares its backing (`Arc<Mutex<Vec>>`, like
//! `BallMessage`), so that append is observed by the caller and list literals /
//! comprehensions / sorts evaluate correctly. Only aliasing *reads* share; the
//! copy points (`toList()`/`List.from`/spread) still snapshot. See
//! `rust/shared/src/value.rs` (`BallList`) and `rust/engine/AGENTS.md`.
//!
//! **Remaining (follow-up):** some class `toString`/constructor edge cases. The
//! default build (no `self_host`) still returns `EngineError::SelfHostPending`;
//! its foundation (loader + scope + ball_proto) stays green.

pub mod ball_proto;
pub mod loader;
pub mod scope;

// The generated self-hosted engine. Present only under the `self_host`
// feature (see Cargo.toml) — it is regenerated by `ball-engine-regen` and does
// not yet compile through `ball-compiler` (see "Self-host status" above), so
// the default build must not include it.
#[cfg(feature = "self_host")]
pub mod compiled_engine;

use std::fmt;

use ball_shared::BallValue;
use ball_shared::proto::ball::v1::Program;
// `BallList` is only constructed on the `self_host` run path (the compiled
// engine's std-handler/constructor input below); gate the import so the default
// build (which stops at `SelfHostPending`) doesn't flag it unused.
#[cfg(feature = "self_host")]
use ball_shared::BallList;

/// A failure loading or running a Ball program.
#[derive(Debug, Clone, PartialEq)]
pub enum EngineError {
    /// The input was not a valid `ball.v1.Program` (bad JSON, wrong shape, or
    /// undecodable binary).
    Parse(String),
    /// A runtime failure while executing the program (a Ball `throw` that
    /// escaped the program, or an engine-level error).
    Runtime(String),
    /// The self-hosted engine driver is not yet wired in — the generated
    /// `compiled_engine.rs` does not compile through the current
    /// `ball-compiler` (issue #39; see the crate doc comment's "Self-host
    /// status"). Carries a short description of the blocking gap.
    SelfHostPending(String),
}

impl fmt::Display for EngineError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            EngineError::Parse(msg) => write!(f, "parse error: {msg}"),
            EngineError::Runtime(msg) => write!(f, "runtime error: {msg}"),
            EngineError::SelfHostPending(msg) => {
                write!(f, "self-hosted engine not yet available: {msg}")
            }
        }
    }
}

impl std::error::Error for EngineError {}

/// A loaded Ball program, ready to run.
///
/// Holds both the typed [`Program`] (for the wrapper's structural needs) and
/// its canonical proto3-JSON [`BallValue`] view (what the compiled engine
/// reads through `ball_proto`). Construct with [`BallEngine::from_json`] or
/// [`BallEngine::from_binary`].
#[derive(Debug)]
pub struct BallEngine {
    program: Program,
    program_value: BallValue,
}

impl BallEngine {
    /// Load a program from proto3-JSON `.ball.json` source (the `@type` Any
    /// envelope is stripped automatically).
    pub fn from_json(json: &str) -> Result<Self, EngineError> {
        let (program, program_value) = loader::parse_program_json(json)?;
        Ok(BallEngine {
            program,
            program_value,
        })
    }

    /// Load a program from binary-protobuf `.ball.bin` bytes.
    pub fn from_binary(bytes: &[u8]) -> Result<Self, EngineError> {
        let (program, program_value) = loader::parse_program_binary(bytes)?;
        Ok(BallEngine {
            program,
            program_value,
        })
    }

    /// The typed program (entry point, modules, functions).
    pub fn program(&self) -> &Program {
        &self.program
    }

    /// The canonical proto3-JSON [`BallValue`] view of the program — the shape
    /// the `ball_proto` access-pattern helpers read.
    pub fn program_value(&self) -> &BallValue {
        &self.program_value
    }

    /// Run the program, returning its captured stdout lines.
    ///
    /// Under the `self_host` feature this drives the compiled self-hosted engine
    /// (see [`Self::run_self_hosted`]) — `hello_world`/`fibonacci` produce
    /// Dart-identical output (issue #300). The default build (no `self_host`,
    /// which excludes the generated `compiled_engine.rs`) returns
    /// [`EngineError::SelfHostPending`]; the loader, scope chain, and
    /// `ball_proto` access patterns this wrapper provides are still exercised.
    pub fn run(&self) -> Result<Vec<String>, EngineError> {
        #[cfg(feature = "self_host")]
        {
            self.run_self_hosted()
        }
        #[cfg(not(feature = "self_host"))]
        {
            Err(EngineError::SelfHostPending(
                "compiled_engine.rs compiles through ball-compiler but does not \
                 yet run: the by-value instance model loses a method's mutations \
                 to `this` (issue #39; see rust/engine/AGENTS.md 'Run blocker')"
                    .to_string(),
            ))
        }
    }

    /// Drive the compiled self-hosted engine (issue #298): build its 16-field
    /// constructor input (the program view, a stdout callback capturing into a
    /// shared buffer, and permissive limits), construct the `BallEngine`
    /// instance, then call its `run`. Reference-`this` semantics + implicit-`this`
    /// injection (issue #298) now let construction and dispatch actually
    /// *proceed* — the by-value clone no longer loses `this._functions`, and
    /// `this._buildLookupTables()`/`this._callFunction(...)` find their
    /// receiver. Execution runs until it reaches a base function the Rust
    /// runtime does not yet implement (`ball_unsupported_base_call` for
    /// `ball_proto.*`/`std.map_create`/`std.record`/… — the ~38-function
    /// runtime surface + `StdModuleHandler` dispatch that remain; see
    /// `rust/engine/AGENTS.md`), which panics and is surfaced here as a
    /// `Runtime` error. A clean completion returns the captured stdout lines.
    ///
    /// `moduleHandlers` is empty for now (registering the compiled
    /// `StdModuleHandler` requires those same unimplemented base functions in
    /// its `init`/`_buildStdDispatch`), so a program's own `std.print` dispatch
    /// is not yet wired — this is the driver seam the remaining runtime work
    /// plugs into, not a finished runner.
    #[cfg(feature = "self_host")]
    fn run_self_hosted(&self) -> Result<Vec<String>, EngineError> {
        use std::sync::{Arc, Mutex};

        use ball_shared::{BallFunction, BallMap, BallMessage};

        // Register the compiled engine's class hierarchy (`BallObject extends
        // BallMap`, …) so runtime `is`/`as` supertype checks resolve (issue #300).
        compiled_engine::__ball_register_types();

        let output: Arc<Mutex<Vec<String>>> = Arc::new(Mutex::new(Vec::new()));
        let sink = Arc::clone(&output);
        let stdout_fn = BallValue::Function(BallFunction::new("stdout", move |message| {
            sink.lock()
                .unwrap_or_else(|e| e.into_inner())
                .push(message.to_string());
            BallValue::Null
        }));

        // The compiled `StdModuleHandler` (issue #300) — the module handler the
        // engine consults for every `std`/`std_collections`/… base call. It is
        // constructed here (rather than via the constructor's `moduleHandlers ??
        // [StdModuleHandler()]` default, which the Rust constructor does not
        // evaluate) with its field-level defaults: `_dispatch`/`_composedDispatch`
        // are mutated (`putIfAbsent`) by `init`, `_tombstones` is a (List-backed)
        // set the built-in registration checks, and `_allowlist` is `null`
        // (expose every built-in). The engine constructor calls `init(this)` on
        // it, which populates `_dispatch` from `engine._buildStdDispatch()`.
        let std_fields = BallMap::new();
        std_fields.insert("_dispatch".to_string(), BallValue::Map(BallMap::new()));
        std_fields.insert(
            "_composedDispatch".to_string(),
            BallValue::Map(BallMap::new()),
        );
        std_fields.insert("_tombstones".to_string(), BallValue::List(BallList::new()));
        std_fields.insert("_allowlist".to_string(), BallValue::Null);
        let std_handler = BallValue::Message(BallMessage::new("main:StdModuleHandler", std_fields));

        // The compiled `BallEngine` constructor reads `program` via
        // `ball_arg_get(input, "program", "arg0")` and every other field by
        // name (see the generated `main_BallEngine::new`).
        let ctor_input = BallMap::new();
        ctor_input.insert("program".to_string(), self.program_value.clone());
        ctor_input.insert("stdout".to_string(), stdout_fn);
        ctor_input.insert("stderr".to_string(), BallValue::Null);
        ctor_input.insert("stdinReader".to_string(), BallValue::Null);
        ctor_input.insert("envGet".to_string(), BallValue::Null);
        ctor_input.insert("args".to_string(), BallValue::List(BallList::new()));
        ctor_input.insert("enableProfiling".to_string(), BallValue::Bool(false));
        ctor_input.insert("maxRecursionDepth".to_string(), BallValue::Int(100_000));
        ctor_input.insert("timeoutMs".to_string(), BallValue::Null);
        ctor_input.insert("maxMemoryBytes".to_string(), BallValue::Null);
        ctor_input.insert("maxModules".to_string(), BallValue::Int(1_000_000));
        ctor_input.insert("maxExpressionDepth".to_string(), BallValue::Int(1_000_000));
        ctor_input.insert("maxProgramSizeBytes".to_string(), BallValue::Null);
        ctor_input.insert("sandbox".to_string(), BallValue::Bool(false));
        ctor_input.insert(
            "moduleHandlers".to_string(),
            BallValue::List(BallList::from(vec![std_handler])),
        );
        ctor_input.insert("resolver".to_string(), BallValue::Null);

        // Run the compiled engine on a **large-stack thread** (issue #300). The
        // self-hosted engine is a deep tree-walker whose compiled methods
        // (`_evalExpression` → `_evalCall` → `_callFunction` → …) each carry a
        // very large frame (hundreds of field-alias locals), so even a modestly
        // recursive target program (`fibonacci(10)`) overflows the default 8 MB
        // stack — a `SIGABRT` that `catch_unwind` cannot recover. A 512 MB stack
        // (mirroring the compiler/encoder's own bumped stacks) gives ample
        // headroom while `maxRecursionDepth` still bounds runaway recursion.
        let outcome = std::thread::Builder::new()
            .stack_size(512 * 1024 * 1024)
            .spawn(move || {
                std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                    let engine = compiled_engine::main_BallEngine::new(BallValue::Map(ctor_input));
                    let run_input = BallMap::new();
                    run_input.insert("self".to_string(), engine);
                    compiled_engine::run(BallValue::Map(run_input))
                }))
            })
            .expect("spawn self-host engine thread")
            .join()
            // A panic *outside* the inner `catch_unwind` (none is expected) is
            // surfaced as the `Runtime` error path below.
            .unwrap_or_else(Err);

        match outcome {
            Ok(_) => Ok(output.lock().unwrap_or_else(|e| e.into_inner()).clone()),
            Err(payload) => {
                let value = ball_shared::runtime::ball_catch_payload(payload);
                Err(EngineError::Runtime(format!(
                    "self-hosted engine did not complete: {value}"
                )))
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const HELLO: &str = r#"{
        "@type": "type.googleapis.com/ball.v1.Program",
        "name": "hello", "version": "1.0.0",
        "entryModule": "main", "entryFunction": "main",
        "modules": [ { "name": "main", "functions": [
            { "name": "main", "body": { "literal": { "stringValue": "hi" } } }
        ] } ]
    }"#;

    #[test]
    fn loads_a_program_and_exposes_typed_and_value_views() {
        let engine = BallEngine::from_json(HELLO).expect("load");
        assert_eq!(engine.program().name, "hello");
        assert!(matches!(engine.program_value(), BallValue::Map(_)));
    }

    #[test]
    fn invalid_json_is_a_parse_error() {
        let err = BallEngine::from_json("{ not valid").unwrap_err();
        assert!(matches!(err, EngineError::Parse(_)));
    }

    #[cfg(not(feature = "self_host"))]
    #[test]
    fn run_reports_self_host_pending_in_default_build() {
        let engine = BallEngine::from_json(HELLO).expect("load");
        let err = engine.run().unwrap_err();
        assert!(matches!(err, EngineError::SelfHostPending(_)));
    }

    #[cfg(feature = "self_host")]
    #[test]
    fn self_host_run_evidence() {
        // Not an assertion of success — a probe (issue #298): with reference
        // `this` + implicit-`this` injection, does execution now *proceed*
        // past construction/dispatch (which previously panicked on a `Null`
        // receiver / lost `_functions`) and reach the remaining unimplemented
        // runtime surface? Print the outcome so `--nocapture` shows exactly how
        // far it gets.
        std::panic::set_hook(Box::new(|_| {})); // silence the caught-panic noise
        let engine = BallEngine::from_json(HELLO).expect("load");
        match engine.run() {
            Ok(lines) => eprintln!("[self-host evidence] completed, stdout = {lines:?}"),
            Err(e) => eprintln!("[self-host evidence] {e}"),
        }
    }
}
