//! `ball-engine` — runs Ball programs via the self-hosted engine (issue #39).
//!
//! ## Design: self-host, mirroring the TS/C++ targets
//!
//! Rather than hand-writing a tree-walking interpreter, `ball-engine` follows
//! the recommended self-hosting route (see
//! `.claude/skills/new-ball-language/SKILL.md` Phase 4, Option B): the
//! reference engine is itself a Ball program
//! (`dart/self_host/engine.ball.json`), which `ball-engine-regen`
//! (`rust/engine/tool/`) compiles through `ball-compiler` into
//! `src/compiled_engine.rs`. A thin wrapper (this crate) then supplies what
//! compiled Ball can't express natively:
//! - loading a target [`Program`] from proto3-JSON `.ball.json` or binary
//!   `.ball.bin` and viewing it as the canonical proto3-JSON [`BallValue`] the
//!   compiled engine reads ([`loader`]);
//! - the `ball_proto` access-pattern functions the compiled engine calls to
//!   inspect that program — oneof discriminators, presence checks, safe field
//!   access ([`ball_proto`]);
//! - the lexical [`scope`] chain and [`scope::FlowSignal`] flow signals;
//! - virtual properties ([`ball_proto::virtual_property`]).
//!
//! `src/compiled_engine.rs` is a **generated, NEVER-edit** file — regenerate
//! it with `cargo run -p ball-engine-regen`, never hand-patch it.
//!
//! ## Self-host status (#39/#298)
//!
//! The regeneration pipeline is complete and produces ~19k lines of Rust from
//! the self-hosted engine, and **that whole engine compiles cleanly** through
//! `ball-compiler` (`cargo build -p ball-engine --features self_host` succeeds).
//! With issue #298's **reference-`this`** (shared `Arc<Mutex>` instance fields)
//! + **implicit-`this` injection**, the compiled engine now *executes*:
//! [`BallEngine::run`] (under the `self_host` feature) constructs the compiled
//! `main_BallEngine` and drives its `run`, and execution proceeds through
//! construction, implicit-`this` dispatch, and `this._functions` population —
//! reaching the base-function frontier instead of the old "self is `Null`" /
//! "entry point not found" failure (the `self_host_run_evidence` probe in the
//! tests below shows exactly how far). It does not yet *complete* a program:
//! ~38 base functions (`ball_proto.*`, `std.map_create`/`record`/`await`/…)
//! still lower to a panicking `ball_unsupported_base_call`, and the
//! compiled-`StdModuleHandler` dispatch (needed for `std.print`) isn't wired —
//! see `rust/engine/AGENTS.md`'s "Remaining run blocker". The default build
//! (no `self_host`) still returns [`EngineError::SelfHostPending`].
//!
//! The crate's foundation (loader + scope + ball_proto access patterns, all
//! unit-tested) builds and tests green in the default build.

pub mod ball_proto;
pub mod loader;
pub mod scope;

// The generated self-hosted engine. Present only under the `self_host`
// feature (see Cargo.toml) — it is regenerated by `ball-engine-regen` and does
// not yet compile through `ball-compiler` (see "Self-host status" above), so
// the default build must not include it.
#[cfg(feature = "self_host")]
pub mod compiled_engine;

use std::fmt;

use ball_shared::BallValue;
use ball_shared::proto::ball::v1::Program;

/// A failure loading or running a Ball program.
#[derive(Debug, Clone, PartialEq)]
pub enum EngineError {
    /// The input was not a valid `ball.v1.Program` (bad JSON, wrong shape, or
    /// undecodable binary).
    Parse(String),
    /// A runtime failure while executing the program (a Ball `throw` that
    /// escaped the program, or an engine-level error).
    Runtime(String),
    /// The self-hosted engine driver is not yet wired in — the generated
    /// `compiled_engine.rs` does not compile through the current
    /// `ball-compiler` (issue #39; see the crate doc comment's "Self-host
    /// status"). Carries a short description of the blocking gap.
    SelfHostPending(String),
}

impl fmt::Display for EngineError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            EngineError::Parse(msg) => write!(f, "parse error: {msg}"),
            EngineError::Runtime(msg) => write!(f, "runtime error: {msg}"),
            EngineError::SelfHostPending(msg) => {
                write!(f, "self-hosted engine not yet available: {msg}")
            }
        }
    }
}

impl std::error::Error for EngineError {}

/// A loaded Ball program, ready to run.
///
/// Holds both the typed [`Program`] (for the wrapper's structural needs) and
/// its canonical proto3-JSON [`BallValue`] view (what the compiled engine
/// reads through `ball_proto`). Construct with [`BallEngine::from_json`] or
/// [`BallEngine::from_binary`].
#[derive(Debug)]
pub struct BallEngine {
    program: Program,
    program_value: BallValue,
}

impl BallEngine {
    /// Load a program from proto3-JSON `.ball.json` source (the `@type` Any
    /// envelope is stripped automatically).
    pub fn from_json(json: &str) -> Result<Self, EngineError> {
        let (program, program_value) = loader::parse_program_json(json)?;
        Ok(BallEngine {
            program,
            program_value,
        })
    }

    /// Load a program from binary-protobuf `.ball.bin` bytes.
    pub fn from_binary(bytes: &[u8]) -> Result<Self, EngineError> {
        let (program, program_value) = loader::parse_program_binary(bytes)?;
        Ok(BallEngine {
            program,
            program_value,
        })
    }

    /// The typed program (entry point, modules, functions).
    pub fn program(&self) -> &Program {
        &self.program
    }

    /// The canonical proto3-JSON [`BallValue`] view of the program — the shape
    /// the `ball_proto` access-pattern helpers read.
    pub fn program_value(&self) -> &BallValue {
        &self.program_value
    }

    /// Run the program, returning its captured stdout lines.
    ///
    /// Returns [`EngineError::SelfHostPending`] in every build for now: the
    /// compiled self-hosted engine **compiles** through `ball-compiler` (issue
    /// #39) but does not yet **run** correctly — the interpreter needs a mutable
    /// `this`, which this crate's by-value `BallValue::Message` instance model
    /// cannot provide (a method's field mutations land on a clone and are lost).
    /// See the crate doc comment and `rust/engine/AGENTS.md`'s "Run blocker".
    /// The loader, scope chain, and `ball_proto` access patterns this wrapper
    /// provides are the foundation the driver will use once that lands.
    pub fn run(&self) -> Result<Vec<String>, EngineError> {
        #[cfg(feature = "self_host")]
        {
            self.run_self_hosted()
        }
        #[cfg(not(feature = "self_host"))]
        {
            Err(EngineError::SelfHostPending(
                "compiled_engine.rs compiles through ball-compiler but does not \
                 yet run: the by-value instance model loses a method's mutations \
                 to `this` (issue #39; see rust/engine/AGENTS.md 'Run blocker')"
                    .to_string(),
            ))
        }
    }

    /// Drive the compiled self-hosted engine (issue #298): build its 16-field
    /// constructor input (the program view, a stdout callback capturing into a
    /// shared buffer, and permissive limits), construct the `BallEngine`
    /// instance, then call its `run`. Reference-`this` semantics + implicit-`this`
    /// injection (issue #298) now let construction and dispatch actually
    /// *proceed* — the by-value clone no longer loses `this._functions`, and
    /// `this._buildLookupTables()`/`this._callFunction(...)` find their
    /// receiver. Execution runs until it reaches a base function the Rust
    /// runtime does not yet implement (`ball_unsupported_base_call` for
    /// `ball_proto.*`/`std.map_create`/`std.record`/… — the ~38-function
    /// runtime surface + `StdModuleHandler` dispatch that remain; see
    /// `rust/engine/AGENTS.md`), which panics and is surfaced here as a
    /// `Runtime` error. A clean completion returns the captured stdout lines.
    ///
    /// `moduleHandlers` is empty for now (registering the compiled
    /// `StdModuleHandler` requires those same unimplemented base functions in
    /// its `init`/`_buildStdDispatch`), so a program's own `std.print` dispatch
    /// is not yet wired — this is the driver seam the remaining runtime work
    /// plugs into, not a finished runner.
    #[cfg(feature = "self_host")]
    fn run_self_hosted(&self) -> Result<Vec<String>, EngineError> {
        use std::sync::{Arc, Mutex};

        use ball_shared::{BallFunction, BallMap};

        let output: Arc<Mutex<Vec<String>>> = Arc::new(Mutex::new(Vec::new()));
        let sink = Arc::clone(&output);
        let stdout_fn = BallValue::Function(BallFunction::new("stdout", move |message| {
            sink.lock()
                .unwrap_or_else(|e| e.into_inner())
                .push(message.to_string());
            BallValue::Null
        }));

        // The compiled `BallEngine` constructor reads `program` via
        // `ball_arg_get(input, "program", "arg0")` and every other field by
        // name (see the generated `main_BallEngine::new`).
        let mut ctor_input = BallMap::new();
        ctor_input.insert("program".to_string(), self.program_value.clone());
        ctor_input.insert("stdout".to_string(), stdout_fn);
        ctor_input.insert("stderr".to_string(), BallValue::Null);
        ctor_input.insert("stdinReader".to_string(), BallValue::Null);
        ctor_input.insert("envGet".to_string(), BallValue::Null);
        ctor_input.insert("args".to_string(), BallValue::List(Vec::new()));
        ctor_input.insert("enableProfiling".to_string(), BallValue::Bool(false));
        ctor_input.insert("maxRecursionDepth".to_string(), BallValue::Int(100_000));
        ctor_input.insert("timeoutMs".to_string(), BallValue::Null);
        ctor_input.insert("maxMemoryBytes".to_string(), BallValue::Null);
        ctor_input.insert("maxModules".to_string(), BallValue::Int(1_000_000));
        ctor_input.insert("maxExpressionDepth".to_string(), BallValue::Int(1_000_000));
        ctor_input.insert("maxProgramSizeBytes".to_string(), BallValue::Null);
        ctor_input.insert("sandbox".to_string(), BallValue::Bool(false));
        ctor_input.insert("moduleHandlers".to_string(), BallValue::List(Vec::new()));
        ctor_input.insert("resolver".to_string(), BallValue::Null);

        let outcome = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            let engine = compiled_engine::main_BallEngine::new(BallValue::Map(ctor_input));
            let mut run_input = BallMap::new();
            run_input.insert("self".to_string(), engine);
            compiled_engine::run(BallValue::Map(run_input))
        }));

        match outcome {
            Ok(_) => Ok(output.lock().unwrap_or_else(|e| e.into_inner()).clone()),
            Err(payload) => {
                let value = ball_shared::runtime::ball_catch_payload(payload);
                Err(EngineError::Runtime(format!(
                    "self-hosted engine did not complete: {value}"
                )))
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const HELLO: &str = r#"{
        "@type": "type.googleapis.com/ball.v1.Program",
        "name": "hello", "version": "1.0.0",
        "entryModule": "main", "entryFunction": "main",
        "modules": [ { "name": "main", "functions": [
            { "name": "main", "body": { "literal": { "stringValue": "hi" } } }
        ] } ]
    }"#;

    #[test]
    fn loads_a_program_and_exposes_typed_and_value_views() {
        let engine = BallEngine::from_json(HELLO).expect("load");
        assert_eq!(engine.program().name, "hello");
        assert!(matches!(engine.program_value(), BallValue::Map(_)));
    }

    #[test]
    fn invalid_json_is_a_parse_error() {
        let err = BallEngine::from_json("{ not valid").unwrap_err();
        assert!(matches!(err, EngineError::Parse(_)));
    }

    #[cfg(not(feature = "self_host"))]
    #[test]
    fn run_reports_self_host_pending_in_default_build() {
        let engine = BallEngine::from_json(HELLO).expect("load");
        let err = engine.run().unwrap_err();
        assert!(matches!(err, EngineError::SelfHostPending(_)));
    }

    #[cfg(feature = "self_host")]
    #[test]
    fn self_host_run_evidence() {
        // Not an assertion of success — a probe (issue #298): with reference
        // `this` + implicit-`this` injection, does execution now *proceed*
        // past construction/dispatch (which previously panicked on a `Null`
        // receiver / lost `_functions`) and reach the remaining unimplemented
        // runtime surface? Print the outcome so `--nocapture` shows exactly how
        // far it gets.
        std::panic::set_hook(Box::new(|_| {})); // silence the caught-panic noise
        let engine = BallEngine::from_json(HELLO).expect("load");
        match engine.run() {
            Ok(lines) => eprintln!("[self-host evidence] completed, stdout = {lines:?}"),
            Err(e) => eprintln!("[self-host evidence] {e}"),
        }
    }
}
