//! `ball-engine` — runs Ball programs via the self-hosted engine (issue #39).
//!
//! ## Design: self-host, mirroring the TS/C++ targets
//!
//! Rather than hand-writing a tree-walking interpreter, `ball-engine` follows
//! the recommended self-hosting route (see
//! `.claude/skills/new-ball-language/SKILL.md` Phase 4, Option B): the
//! reference engine is itself a Ball program
//! (`dart/self_host/engine.ball.json`), which `ball-engine-regen`
//! (`rust/engine/tool/`) compiles through `ball-compiler` into
//! `src/compiled_engine.rs`. A thin wrapper (this crate) then supplies what
//! compiled Ball can't express natively:
//! - loading a target [`Program`] from proto3-JSON `.ball.json` or binary
//!   `.ball.bin` and viewing it as the canonical proto3-JSON [`BallValue`] the
//!   compiled engine reads ([`loader`]);
//! - the `ball_proto` access-pattern functions the compiled engine calls to
//!   inspect that program — oneof discriminators, presence checks, safe field
//!   access ([`ball_proto`]);
//! - the lexical [`scope`] chain and [`scope::FlowSignal`] flow signals;
//! - virtual properties ([`ball_proto::virtual_property`]).
//!
//! `src/compiled_engine.rs` is a **generated, NEVER-edit** file — regenerate
//! it with `cargo run -p ball-engine-regen`, never hand-patch it.
//!
//! ## Self-host status (issue #39)
//!
//! The regeneration pipeline is complete and produces ~19k lines of Rust from
//! the 289-function self-hosted engine. Compiling that whole engine through
//! the current `ball-compiler` still exposes a **large, multi-faceted set of
//! compiler gaps** (the self-hosted engine is authored against the full Dart
//! SDK surface): protobuf oneof-discriminator enum constants, ~120 Dart-SDK
//! method calls (`RegExp`, `DateTime`, `File`, `Iterable`, `num.tryParse`, …),
//! named/optional-parameter + getter/setter dispatch, constructor
//! initializers + super-constructor inheritance, and dynamic-value-vs-borrow-
//! checker conflicts. Those are tracked as follow-up compiler issues; see the
//! PR/AGENTS.md gap report.
//!
//! Until they are closed, the compiled-engine driver is gated behind the
//! off-by-default `self_host` cargo feature so this crate's foundation
//! (loader + scope + ball_proto access patterns, all unit-tested) builds and
//! tests green. [`BallEngine::run`] returns [`EngineError::SelfHostPending`]
//! in the default build.

pub mod ball_proto;
pub mod loader;
pub mod scope;

// The generated self-hosted engine. Present only under the `self_host`
// feature (see Cargo.toml) — it is regenerated by `ball-engine-regen` and does
// not yet compile through `ball-compiler` (see "Self-host status" above), so
// the default build must not include it.
#[cfg(feature = "self_host")]
pub mod compiled_engine;

use std::fmt;

use ball_shared::BallValue;
use ball_shared::proto::ball::v1::Program;

/// A failure loading or running a Ball program.
#[derive(Debug, Clone, PartialEq)]
pub enum EngineError {
    /// The input was not a valid `ball.v1.Program` (bad JSON, wrong shape, or
    /// undecodable binary).
    Parse(String),
    /// A runtime failure while executing the program (a Ball `throw` that
    /// escaped the program, or an engine-level error).
    Runtime(String),
    /// The self-hosted engine driver is not yet wired in — the generated
    /// `compiled_engine.rs` does not compile through the current
    /// `ball-compiler` (issue #39; see the crate doc comment's "Self-host
    /// status"). Carries a short description of the blocking gap.
    SelfHostPending(String),
}

impl fmt::Display for EngineError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            EngineError::Parse(msg) => write!(f, "parse error: {msg}"),
            EngineError::Runtime(msg) => write!(f, "runtime error: {msg}"),
            EngineError::SelfHostPending(msg) => {
                write!(f, "self-hosted engine not yet available: {msg}")
            }
        }
    }
}

impl std::error::Error for EngineError {}

/// A loaded Ball program, ready to run.
///
/// Holds both the typed [`Program`] (for the wrapper's structural needs) and
/// its canonical proto3-JSON [`BallValue`] view (what the compiled engine
/// reads through `ball_proto`). Construct with [`BallEngine::from_json`] or
/// [`BallEngine::from_binary`].
#[derive(Debug)]
pub struct BallEngine {
    program: Program,
    program_value: BallValue,
}

impl BallEngine {
    /// Load a program from proto3-JSON `.ball.json` source (the `@type` Any
    /// envelope is stripped automatically).
    pub fn from_json(json: &str) -> Result<Self, EngineError> {
        let (program, program_value) = loader::parse_program_json(json)?;
        Ok(BallEngine {
            program,
            program_value,
        })
    }

    /// Load a program from binary-protobuf `.ball.bin` bytes.
    pub fn from_binary(bytes: &[u8]) -> Result<Self, EngineError> {
        let (program, program_value) = loader::parse_program_binary(bytes)?;
        Ok(BallEngine {
            program,
            program_value,
        })
    }

    /// The typed program (entry point, modules, functions).
    pub fn program(&self) -> &Program {
        &self.program
    }

    /// The canonical proto3-JSON [`BallValue`] view of the program — the shape
    /// the `ball_proto` access-pattern helpers read.
    pub fn program_value(&self) -> &BallValue {
        &self.program_value
    }

    /// Run the program, returning its captured stdout lines.
    ///
    /// In the default build this returns [`EngineError::SelfHostPending`] — the
    /// compiled self-hosted engine does not yet compile through
    /// `ball-compiler` (issue #39; see the crate doc comment). The loader,
    /// scope chain, and `ball_proto` access patterns this wrapper provides are
    /// the foundation the driver will use once those compiler gaps are closed.
    pub fn run(&self) -> Result<Vec<String>, EngineError> {
        #[cfg(feature = "self_host")]
        {
            self.run_self_hosted()
        }
        #[cfg(not(feature = "self_host"))]
        {
            Err(EngineError::SelfHostPending(
                "compiled_engine.rs does not yet build through ball-compiler; \
                 enable the `self_host` feature once the compiler gaps in issue \
                 #39 are closed (see rust/engine/AGENTS.md)"
                    .to_string(),
            ))
        }
    }

    #[cfg(feature = "self_host")]
    fn run_self_hosted(&self) -> Result<Vec<String>, EngineError> {
        // Driver seam for the compiled engine (issue #39 follow-up). Wired in
        // once `compiled_engine.rs` compiles: instantiate the compiled
        // `BallEngine`/`StdModuleHandler` classes with `self.program_value`,
        // call `run`, and collect the captured stdout — the same shape the TS
        // wrapper's `new CompiledEngine(...).run()` uses.
        Err(EngineError::SelfHostPending(
            "self_host feature is enabled but the compiled-engine driver seam \
             is not yet connected"
                .to_string(),
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const HELLO: &str = r#"{
        "@type": "type.googleapis.com/ball.v1.Program",
        "name": "hello", "version": "1.0.0",
        "entryModule": "main", "entryFunction": "main",
        "modules": [ { "name": "main", "functions": [
            { "name": "main", "body": { "literal": { "stringValue": "hi" } } }
        ] } ]
    }"#;

    #[test]
    fn loads_a_program_and_exposes_typed_and_value_views() {
        let engine = BallEngine::from_json(HELLO).expect("load");
        assert_eq!(engine.program().name, "hello");
        assert!(matches!(engine.program_value(), BallValue::Map(_)));
    }

    #[test]
    fn invalid_json_is_a_parse_error() {
        let err = BallEngine::from_json("{ not valid").unwrap_err();
        assert!(matches!(err, EngineError::Parse(_)));
    }

    #[test]
    fn run_reports_self_host_pending_in_default_build() {
        let engine = BallEngine::from_json(HELLO).expect("load");
        let err = engine.run().unwrap_err();
        assert!(matches!(err, EngineError::SelfHostPending(_)));
    }
}
