#!/usr/bin/env bash
# Wiring guard for ci.yml's `Ball Artifact Freshness` regeneration flow (#625).
#
# WHY THIS EXISTS: that job regenerates every committed Ball artifact and gates
# each family with a `git diff --exit-code` "Assert …" step. #619 added a second
# half — on failure it COLLECTS the regenerated bytes, UPLOADS them as the
# `regenerated-artifacts` workflow artifact, and (with `REGEN_PAT` set) COMMITS
# AND PUSHES them onto the PR branch.
#
# THE BUG #625 FIXES: those three steps were gated on a bare `failure()`, which
# cannot tell a failed *Assert* step (the regenerated bytes are correct and the
# commit is stale) from a failed *Regenerate* step (a generator died mid-write
# under `set -euo pipefail`, so the file on disk is PARTIAL). `failure()` fires
# identically for both, so the partial file would be uploaded as "the fix" and,
# once `REGEN_PAT` exists, committed to the PR automatically. The fix is to gate
# on the per-artifact `steps.<assert-id>.outcome == 'failure'` instead — a
# Regenerate failure then uploads nothing and simply fails loud.
#
# NOTHING WOULD CATCH THAT REGRESSING. The flow is only ever exercised on a RED
# freshness run, so a `failure()` that crept back, an Assert step that lost its
# `id`, a new artifact family whose Assert is not in the gate, or a push step
# that stopped calling the loop-breaker would all sit there unnoticed until the
# day they mattered. This parses the workflow and asserts the shape on every PR.
#
# POSITIVE FLOOR: a guard that asserted nothing must not report success. The
# checker refuses a job with fewer than 6 `Assert …` steps, refuses an empty
# required-id set, and the self-test refuses to pass on fewer than 10 cases.
#
# Usage:
#   bash tools/ci/check_ci_regen_wiring.sh                # gate the repo
#   bash tools/ci/check_ci_regen_wiring.sh --file FILE    # a synthetic workflow
#   bash tools/ci/check_ci_regen_wiring.sh --self-test    # drive the cases
#
# Exits 0 when the wiring holds; 1 otherwise, naming every broken expectation.
# Needs bash + python3 + PyYAML (the runner image ships all three), so it runs
# in ci.yml's always-on `Proto Checks` job with no toolchain.

set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
WORKFLOW="$ROOT/.github/workflows/ci.yml"
SELF_TEST=0

while [ $# -gt 0 ]; do
  case "$1" in
  --file)
    WORKFLOW="$2"
    shift 2
    ;;
  --file=*)
    WORKFLOW="${1#--file=}"
    shift
    ;;
  --self-test)
    SELF_TEST=1
    shift
    ;;
  -h | --help)
    sed -n '2,40p' "${BASH_SOURCE[0]}"
    exit 0
    ;;
  *)
    echo "::error::unknown argument: $1" >&2
    exit 2
    ;;
  esac
done

# ── the check itself ────────────────────────────────────────────────────────
# python3 rather than grep/awk: the conditions are folded (`>-`) multi-line YAML
# scalars, so only a parser sees the expression a step actually carries.
check_file() {
  local file="$1"
  python3 - "$file" <<'PY'
import re
import sys

try:
    import yaml
except ImportError:  # pragma: no cover - the runner image ships PyYAML
    print("::error::PyYAML is required by tools/ci/check_ci_regen_wiring.sh")
    sys.exit(1)

path = sys.argv[1]
JOB = "ball-freshness"

# Every artifact family the job regenerates, and the `id` its `git diff
# --exit-code` gate must carry. Adding a family here without wiring its id into
# the three conditions below is the failure this guard exists to make loud.
REQUIRED_ASSERT_IDS = (
    "assert-shared",
    "assert-corpus",
    "assert-std-coverage",
    "assert-ts-engine",
    "assert-ts-cli",
    "assert-go",
)
MIN_ASSERT_STEPS = 6

passed = 0
failures = []


def ok(msg):
    global passed
    passed += 1
    print(f"PASS {msg}")


def bad(msg):
    failures.append(msg)
    print(f"FAIL {msg}")


def die(msg):
    print(f"::error::{msg}")
    print("Results: 0 passed, 1 failed, 1 total")
    sys.exit(1)


try:
    with open(path, encoding="utf-8") as fh:
        doc = yaml.safe_load(fh)
except FileNotFoundError:
    die(f"workflow not found: {path}")
except yaml.YAMLError as exc:
    die(f"{path} is not parseable YAML: {exc}")

if not isinstance(doc, dict):
    die(f"{path} does not parse to a mapping")

jobs = doc.get("jobs")
if not isinstance(jobs, dict):
    die(f"{path} has no `jobs:` mapping")

job = jobs.get(JOB)
if not isinstance(job, dict):
    die(f"{path} has no `{JOB}` job — this guard gates that job's regeneration flow (#619/#625)")

steps = job.get("steps")
if not isinstance(steps, list) or not steps:
    die(f"{path}: `{JOB}` has no steps")


def cond(step):
    """The step's `if:` as one whitespace-normalised line ('' when absent)."""
    value = step.get("if")
    if value is None:
        return ""
    return " ".join(str(value).split())


def body(step):
    return str(step.get("run") or "")


def name(step):
    return str(step.get("name") or "")


asserts = [s for s in steps if isinstance(s, dict) and name(s).startswith("Assert ")]

# 1. A floor first: a job whose Assert steps vanished must not read as "wired".
if len(asserts) < MIN_ASSERT_STEPS:
    die(
        f"{path}: `{JOB}` has only {len(asserts)} `Assert …` step(s); at least "
        f"{MIN_ASSERT_STEPS} are expected. This guard refuses to certify a job it "
        "found nothing to check."
    )
ok(f"`{JOB}` has {len(asserts)} `Assert …` steps (floor {MIN_ASSERT_STEPS})")

# 2. EVERY Assert step carries an id. An un-id'd gate cannot be referenced by an
#    `if:`, so the next artifact family would silently fall back to `failure()`.
missing_id = [name(s) for s in asserts if not s.get("id")]
if missing_id:
    bad(
        "every `Assert …` step needs an `id` so the collect/upload/push gates can "
        "name it; these have none: " + ", ".join(missing_id)
    )
else:
    ok("every `Assert …` step carries an `id`")

ids = {str(s.get("id")) for s in asserts if s.get("id")}
absent = [i for i in REQUIRED_ASSERT_IDS if i not in ids]
if absent:
    bad("missing required Assert step id(s): " + ", ".join(absent))
else:
    ok("all " + str(len(REQUIRED_ASSERT_IDS)) + " artifact-family Assert ids are present")


def find_step(pred, label):
    for s in steps:
        if isinstance(s, dict) and pred(s):
            return s
    bad(f"no {label} step found in `{JOB}`")
    return None


collect = find_step(lambda s: s.get("id") == "collect", "`id: collect`")
upload = find_step(
    lambda s: str(s.get("uses") or "").startswith("actions/upload-artifact"),
    "`actions/upload-artifact`",
)
push = find_step(lambda s: "Commit and push" in name(s), "`Commit and push …`")


def assert_gated(step, label, extra=()):
    """The step's `if:` must name every artifact Assert outcome, plus `extra`."""
    if step is None:
        return
    expr = cond(step)
    if not expr:
        bad(f"{label} has no `if:` at all — it would run on every green job")
        return
    if "failure()" not in expr:
        bad(f"{label}'s `if:` does not mention `failure()`")
        return
    missing = [
        i
        for i in REQUIRED_ASSERT_IDS
        if not re.search(
            r"steps\." + re.escape(i) + r"\.outcome\s*==\s*'failure'", expr
        )
    ]
    if missing:
        bad(
            f"{label}'s `if:` must gate on the Assert steps' outcomes, not a bare "
            "`failure()` — a failed *Regenerate* step leaves PARTIAL bytes on disk "
            "(#625). Not referenced: " + ", ".join(missing)
        )
        return
    for needle in extra:
        if needle not in expr:
            bad(f"{label}'s `if:` is missing `{needle}`")
            return
    ok(f"{label} is gated on all {len(REQUIRED_ASSERT_IDS)} Assert outcomes")


assert_gated(collect, "the collect step")
assert_gated(upload, "the upload step", extra=("steps.collect.outputs.count",))
assert_gated(
    push,
    "the REGEN_PAT push step",
    extra=(
        "steps.collect.outputs.count",
        "github.event.pull_request.head.repo.full_name == github.repository",
        "env.HAS_REGEN_PAT == 'true'",
    ),
)

# 3. The loop-breaker (#625): the push step must ask whether the PR head commit
#    is itself an auto-push, and must take the marker trailer FROM the script
#    rather than spelling a second copy of the literal.
if push is not None:
    run = body(push)
    if "regen_loop_breaker.sh" not in run:
        bad(
            "the REGEN_PAT push step does not invoke tools/ci/regen_loop_breaker.sh — "
            "without it a nondeterministic generator loops forever (push -> run -> "
            "drift -> push, #625)"
        )
    elif "--rev" not in run:
        bad("the push step invokes the loop-breaker but never with `--rev` (the PR head commit)")
    elif "--print-marker" not in run:
        bad(
            "the push step must take the marker trailer from "
            "`regen_loop_breaker.sh --print-marker`; a hand-copied literal drifts and "
            "silently disables the loop-breaker"
        )
    else:
        ok("the push step consults the loop-breaker and sources the marker from it")

# 4. Every `${{ … }}` placeholder in the job must be WELL FORMED. GitHub parses
#    expressions only when it creates a run, and a workflow that fails to parse
#    produces NO CHECKS AT ALL — and an absent check reads as green. PyYAML is
#    perfectly happy with `${{{{ … }}}}` (a stray brace pair from a templating
#    slip), so the YAML parse above cannot see this class; scan the text.
placeholder_errors = []
for step in steps:
    if not isinstance(step, dict):
        continue
    chunks = [cond(step), body(step)]
    env = step.get("env")
    if isinstance(env, dict):
        chunks.extend(str(v) for v in env.values())
    with_ = step.get("with")
    if isinstance(with_, dict):
        chunks.extend(str(v) for v in with_.values())
    for chunk in chunks:
        if "${{{" in chunk or "}}}" in chunk:
            placeholder_errors.append(name(step) or str(step.get("id")))
            break
if placeholder_errors:
    bad(
        "malformed `${{ … }}` placeholder (a stray brace) in: "
        + ", ".join(sorted(set(placeholder_errors)))
        + " — GitHub would refuse to create the run, and a workflow that never "
        "runs shows NO checks, which reads as green"
    )
else:
    ok("every `${{ … }}` placeholder in the job is well formed")

# 5. No escape hatches anywhere in the job. A `continue-on-error` on any step
#    here would turn the whole regenerate-and-diff contract green-by-default.
hatches = []
if job.get("continue-on-error"):
    hatches.append(f"job `{JOB}`")
for s in steps:
    if isinstance(s, dict) and s.get("continue-on-error"):
        hatches.append(f"step `{name(s) or s.get('id')}`")
    if isinstance(s, dict) and re.search(r"\|\|\s*true\b", body(s)):
        hatches.append(f"step `{name(s) or s.get('id')}` uses `|| true`")
if hatches:
    bad("no step in this job may swallow a failure; found: " + ", ".join(hatches))
else:
    ok("no `continue-on-error` / `|| true` anywhere in the job")

total = passed + len(failures)
print(f"Results: {passed} passed, {len(failures)} failed, {total} total")
if failures:
    print(f"::error::{path}: the `{JOB}` regeneration wiring is broken (see the FAIL lines above; issue #625).")
    sys.exit(1)
if passed < 7:
    print(
        f"::error::{path}: only {passed} assertion(s) ran — a guard that checked "
        "almost nothing is not a passing guard."
    )
    sys.exit(1)
sys.exit(0)
PY
}

# ── self-test ───────────────────────────────────────────────────────────────
SCRATCH=""
cleanup() {
  [ -n "$SCRATCH" ] && rm -rf "$SCRATCH"
  return 0
}

# An artifact FAMILY, spelled the way the four places that must agree describe
# it:  <assert-id> <COLLECT_ENV_VAR> <repo/relative/path>
# The helpers below emit the `Assert …` step, the gate expression, the collect
# step's `env:` entry and its pathspec block from the SAME record, so a case can
# break exactly one of the four and leave the other three consistent — which is
# the only way to prove the guard sees THAT break and not some collateral one.
BASE_FAMILIES='assert-shared ASSERT_SHARED dart/shared/std.json
assert-corpus ASSERT_CORPUS tests/conformance/x.ball.json
assert-std-coverage ASSERT_STD_COVERAGE tests/conformance/std_coverage.json
assert-ts-engine ASSERT_TS_ENGINE ts/engine/src/compiled_engine.ts
assert-ts-cli ASSERT_TS_CLI ts/cli/src/compiled_cli.ts
assert-go ASSERT_GO go/engine/compiled/compiled_engine.go'

# The `Assert …` steps. Each carries the `git diff --exit-code` predicate the
# guard DERIVES the artifact-family set from (#655) — a checker step that owns
# no artifact is spelled without it.
asserts_yaml() {
  local id var path
  while read -r id var path; do
    [ -n "$id" ] || continue
    printf '      - name: Assert %s is up to date\n        id: %s\n        run: git diff --exit-code -- %s\n' \
      "$id" "$id" "$path"
  done <<<"$1"
}

# `failure() && ( steps.<id>.outcome == 'failure' || … )` over the ids given.
gate_expr() {
  local id out="failure() && (" first=1
  while read -r id; do
    [ -n "$id" ] || continue
    if [ "$first" -eq 1 ]; then first=0; else out="$out ||"; fi
    out="$out steps.$id.outcome == 'failure'"
  done <<<"$1"
  printf '%s )' "$out"
}

# The collect step's `env:` block — the id -> shell-variable mapping.
collect_env_yaml() {
  local id var path
  while read -r id var path; do
    [ -n "$id" ] || continue
    printf '          %s: ${{ steps.%s.outcome }}\n' "$var" "$id"
  done <<<"$1"
}

# The collect step's pathspec TABLE: one `if [ "$VAR" = "failure" ]` block per
# family, each appending that family's paths. A record with no path emits an
# empty `pathspec+=()`, which is the "gate lists it, table forgot it" shape.
collect_run_yaml() {
  local id var path
  printf '          set -euo pipefail\n          pathspec=()\n'
  while read -r id var path; do
    [ -n "$id" ] || continue
    printf '          if [ "${%s:-}" = "failure" ]; then\n            pathspec+=(%s)\n          fi\n' \
      "$var" "$path"
  done <<<"$1"
  printf '          echo "count=${#pathspec[@]}" >> "$GITHUB_OUTPUT"\n'
}

ids_of() { awk 'NF {print $1}' <<<"$1"; }

# Builds a synthetic ci.yml whose `ball-freshness` job has the right shape.
fixture() {
  local asserts="$1" collect_if="$2" collect_env="$3" collect_run="$4" \
    upload_if="$5" push_if="$6" push_run="$7" extra_step="$8"
  cat <<YAML
name: CI
on:
  pull_request:
    branches: [main]
jobs:
  ball-freshness:
    name: Ball Artifact Freshness
    runs-on: ubuntu-latest
    steps:
      - name: Regenerate shared Ball artifacts
        run: echo regen
${asserts}
${extra_step}      - name: Collect the regenerated artifacts
        id: collect
        if: >-
          ${collect_if}
        env:
${collect_env}
        run: |
${collect_run}
      - name: Upload the regenerated artifacts
        if: >-
          ${upload_if}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: regenerated-artifacts
          path: x
      - name: Commit and push the regenerated artifacts (needs REGEN_PAT)
        if: >-
          ${push_if}
        run: |
          ${push_run}
YAML
}

self_test() {
  local pass=0 fail=0
  SCRATCH="$(mktemp -d)"
  trap cleanup EXIT

  local base_ids all7 all7_ids seventh seventh_nopath good_run
  base_ids="$(ids_of "$BASE_FAMILIES")"
  seventh='assert-python ASSERT_PYTHON python/engine/ball_engine/compiled_engine.py'
  seventh_nopath='assert-python ASSERT_PYTHON'
  all7="$BASE_FAMILIES
$seventh"
  all7_ids="$(ids_of "$all7")"
  good_run='bash tools/ci/regen_loop_breaker.sh --rev HEAD; marker="$(bash tools/ci/regen_loop_breaker.sh --print-marker)"; git push'

  local gate upload_gate push_gate
  gate="$(gate_expr "$base_ids")"
  upload_gate="$gate && steps.collect.outputs.count > 0"
  push_gate="$gate && github.event.pull_request.head.repo.full_name == github.repository && env.HAS_REGEN_PAT == 'true' && steps.collect.outputs.count > 0"

  # wire <assert-families> <env-families> <table-families> <gate-ids> [extra-step] [assert-yaml-override]
  # Every gate (collect/upload/push) is built from the SAME id list, so a case
  # that varies only <gate-ids> varies all three together.
  wire() {
    local af="$1" ef="$2" tf="$3" gids="$4" extra="${5:-}" asserts="${6:-}"
    local g
    g="$(gate_expr "$gids")"
    [ -n "$asserts" ] || asserts="$(asserts_yaml "$af")"
    fixture "$asserts" "$g" "$(collect_env_yaml "$ef")" "$(collect_run_yaml "$tf")" \
      "$g && steps.collect.outputs.count > 0" \
      "$g && github.event.pull_request.head.repo.full_name == github.repository && env.HAS_REGEN_PAT == 'true' && steps.collect.outputs.count > 0" \
      "$good_run" "$extra"
  }

  # expect <name> <want-exit> <yaml> [needle...]
  expect() {
    local name="$1" want="$2" yaml="$3"
    shift 3
    local f out rc=0 ok=1 needle
    f="$SCRATCH/wf.$RANDOM.yml"
    printf '%s' "$yaml" >"$f"
    out="$(check_file "$f" 2>&1)" || rc=$?
    [ "$rc" -eq "$want" ] || ok=0
    for needle in "$@"; do
      case "$out" in
      *"$needle"*) ;;
      *) ok=0 ;;
      esac
    done
    if [ "$ok" -eq 1 ]; then
      pass=$((pass + 1))
      echo "PASS $name"
    else
      fail=$((fail + 1))
      echo "FAIL $name (exit $rc, wanted $want)"
      echo "$out" | sed 's/^/    | /'
    fi
  }

  # ── the happy shape, and the one that proves the set is DERIVED ────────────
  expect "a correctly wired job passes" 0 \
    "$(wire "$BASE_FAMILIES" "$BASE_FAMILIES" "$BASE_FAMILIES" "$base_ids")" \
    "Results: " " passed, 0 failed,"

  # A SEVENTH family, wired into all three gates, the env map and the table —
  # the guard must accept growth rather than pinning the set at today's six.
  expect "a seventh family wired everywhere passes" 0 \
    "$(wire "$all7" "$all7" "$all7" "$all7_ids")" \
    "Results: " " passed, 0 failed,"

  # ── #655 negative controls: a derived family that is not fully wired ───────
  expect "a seventh family absent from the gates and the table fails" 1 \
    "$(wire "$all7" "$BASE_FAMILIES" "$BASE_FAMILIES" "$base_ids")" \
    "assert-python"

  expect "a seventh family in the gates but missing from the collect table fails" 1 \
    "$(wire "$all7" "$all7" "$BASE_FAMILIES" "$all7_ids")" \
    "assert-python"

  expect "a seventh family whose table block adds no path fails" 1 \
    "$(wire "$all7" "$all7" "$BASE_FAMILIES
$seventh_nopath" "$all7_ids")" \
    "assert-python"

  expect "a seventh family with no collect env entry fails" 1 \
    "$(wire "$all7" "$BASE_FAMILIES" "$all7" "$all7_ids")" \
    "assert-python"

  # A table entry for a family that no longer exists is drift in the other
  # direction: the run tests a variable nothing ever sets.
  expect "a stale collect table entry fails" 1 \
    "$(wire "$BASE_FAMILIES" "$BASE_FAMILIES
assert-gone ASSERT_GONE dead/path.json" "$BASE_FAMILIES
assert-gone ASSERT_GONE dead/path.json" "$base_ids")" \
    "assert-gone"

  # An Assert step that stopped being a regenerate-and-diff gate drops out of
  # the derived set — which must fail against the literal floor, not silently
  # shrink the set the gates are checked against.
  local lost_diff
  lost_diff="$(asserts_yaml "$(grep -v '^assert-go ' <<<"$BASE_FAMILIES")")
      - name: Assert compiled Go engine and CLI core are up to date
        id: assert-go
        run: cd go/engine && go run ./cmd/check
"
  expect "an Assert step that lost \`git diff --exit-code\` fails the floor" 1 \
    "$(wire "$BASE_FAMILIES" "$BASE_FAMILIES" "$BASE_FAMILIES" "$base_ids" "" "$lost_diff")" \
    "assert-go"

  # ── the #625 cases, unchanged in intent ───────────────────────────────────
  expect "a bare failure() on collect fails" 1 \
    "$(fixture "$(asserts_yaml "$BASE_FAMILIES")" "failure()" "$(collect_env_yaml "$BASE_FAMILIES")" \
      "$(collect_run_yaml "$BASE_FAMILIES")" "$upload_gate" "$push_gate" "$good_run" "")" \
    "the collect step's \`if:\` must gate on the Assert steps' outcomes"

  expect "a bare failure() on upload fails" 1 \
    "$(fixture "$(asserts_yaml "$BASE_FAMILIES")" "$gate" "$(collect_env_yaml "$BASE_FAMILIES")" \
      "$(collect_run_yaml "$BASE_FAMILIES")" "failure() && steps.collect.outputs.count > 0" \
      "$push_gate" "$good_run" "")" \
    "the upload step's \`if:\`"

  expect "a bare failure() on the push fails" 1 \
    "$(fixture "$(asserts_yaml "$BASE_FAMILIES")" "$gate" "$(collect_env_yaml "$BASE_FAMILIES")" \
      "$(collect_run_yaml "$BASE_FAMILIES")" "$upload_gate" "failure() && env.HAS_REGEN_PAT == 'true'" \
      "$good_run" "")" \
    "the REGEN_PAT push step's \`if:\`"

  expect "an upload that dropped the count guard fails" 1 \
    "$(fixture "$(asserts_yaml "$BASE_FAMILIES")" "$gate" "$(collect_env_yaml "$BASE_FAMILIES")" \
      "$(collect_run_yaml "$BASE_FAMILIES")" "$gate" "$push_gate" "$good_run" "")" \
    "is missing \`steps.collect.outputs.count\`"

  expect "a push that dropped the fork guard fails" 1 \
    "$(fixture "$(asserts_yaml "$BASE_FAMILIES")" "$gate" "$(collect_env_yaml "$BASE_FAMILIES")" \
      "$(collect_run_yaml "$BASE_FAMILIES")" "$upload_gate" \
      "$gate && env.HAS_REGEN_PAT == 'true' && steps.collect.outputs.count > 0" "$good_run" "")" \
    "head.repo.full_name"

  local unided='      - name: Assert something new is up to date
        run: git diff --exit-code -- some/path
'
  expect "an Assert step with no id fails" 1 \
    "$(wire "$BASE_FAMILIES" "$BASE_FAMILIES" "$BASE_FAMILIES" "$base_ids" "$unided")" \
    "step needs an \`id\` so the collect/upload/push gates can name it"

  expect "a push with no loop-breaker fails" 1 \
    "$(fixture "$(asserts_yaml "$BASE_FAMILIES")" "$gate" "$(collect_env_yaml "$BASE_FAMILIES")" \
      "$(collect_run_yaml "$BASE_FAMILIES")" "$upload_gate" "$push_gate" "git push" "")" \
    "does not invoke tools/ci/regen_loop_breaker.sh"

  expect "a hand-copied marker literal fails" 1 \
    "$(fixture "$(asserts_yaml "$BASE_FAMILIES")" "$gate" "$(collect_env_yaml "$BASE_FAMILIES")" \
      "$(collect_run_yaml "$BASE_FAMILIES")" "$upload_gate" "$push_gate" \
      'bash tools/ci/regen_loop_breaker.sh --rev HEAD; git commit -m "Ball-Regen-Autopush: ball-artifact-freshness"' "")" \
    "--print-marker"

  local stray_brace='      - name: Something templated
        env:
          OUTCOME: ${{{ steps.assert-go.outcome }}}
        run: echo x
'
  expect "a stray-brace placeholder fails" 1 \
    "$(wire "$BASE_FAMILIES" "$BASE_FAMILIES" "$BASE_FAMILIES" "$base_ids" "$stray_brace")" \
    "malformed"

  local swallow='      - name: Something lenient
        continue-on-error: true
        run: echo x
'
  expect "a continue-on-error step fails" 1 \
    "$(wire "$BASE_FAMILIES" "$BASE_FAMILIES" "$BASE_FAMILIES" "$base_ids" "$swallow")" \
    "may swallow a failure"

  local too_few='name: CI
on: {pull_request: {}}
jobs:
  ball-freshness:
    runs-on: ubuntu-latest
    steps:
      - name: Assert no drift
        id: assert-shared
        run: git diff --exit-code
'
  expect "a job with too few Assert steps is refused" 1 "$too_few" \
    "refuses to certify a job it found nothing to check"

  local wrong_job='name: CI
on: {pull_request: {}}
jobs:
  other:
    runs-on: ubuntu-latest
    steps: [{run: "true"}]
'
  expect "a missing ball-freshness job is refused" 1 "$wrong_job" "has no \`ball-freshness\` job"

  expect "unparseable YAML is refused" 1 'jobs:
  x:
   steps:
  - bad: [
' "::error::"

  echo "Results: $pass passed, $fail failed, $((pass + fail)) total"
  if [ "$pass" -lt 18 ]; then
    echo "::error::self-test executed fewer cases than expected ($pass < 18) — a self-test that ran nothing is not a passing self-test."
    return 1
  fi
  [ "$fail" -eq 0 ]
}

if [ "$SELF_TEST" -eq 1 ]; then
  self_test
  exit $?
fi

check_file "$WORKFLOW"
exit $?
