using System.Text.Json;
using Ball.Compiler;
using Ball.V1;
using Google.Protobuf;
using Google.Protobuf.WellKnownTypes;

namespace Ball.Cli.Regen;

/// <summary>
/// Regenerates <c>csharp/cli/src/CompiledCli.cs</c> from the self-hosted CLI-core Ball program
/// (<c>dart/self_host/cli.ball.json</c>/<c>.pb</c>) — the C# cli-core adoption route (issue
/// #385, mirroring epic #361's pattern: <c>rust/cli/tool/src/main.rs</c> / <c>ts/cli</c>'s
/// compiled-CLI regeneration command). The only structural difference from
/// <c>csharp/engine/tool</c>: <c>cli_core</c> is a plain library of top-level
/// <c>Program -&gt; String</c> report functions (no classes, no interpreter loop), so the
/// compiled output is directly callable — no runtime-driving wrapper like
/// <see cref="Ball.Engine.BallEngine"/>'s <c>RunSelfHosted</c> is needed; <c>csharp/cli/src/Commands/*.cs</c>
/// calls the generated functions straight.
///
/// <para>Pipeline:</para>
/// <list type="number">
/// <item>Read <c>dart/self_host/cli.ball.pb</c> (falling back to <c>cli.ball.json</c>) — a
/// self-describing <c>google.protobuf.Any</c> envelope carrying the <c>ball.v1.Program</c>.</item>
/// <item>Unpack the <c>Any</c> to a typed <see cref="Program"/>.</item>
/// <item><b>Drop <c>auditReport</c></b> (see <see cref="SkippedFunctions"/>) before compiling.</item>
/// <item>Compile via <see cref="CSharpCompiler.Compile(Program)"/> (library shape — <c>cli_core</c>
/// has no runnable <c>main()</c>, so no <c>Main</c> is emitted, exactly like the self-hosted
/// engine).</item>
/// <item>Write <c>CompiledCli.cs</c> with a NEVER-edit header.</item>
/// </list>
///
/// <para><c>CompiledCli.cs</c> is a <b>generated, NEVER-edit</b> file — fix <c>cli_core</c>
/// (<c>dart/shared/lib/cli_core.dart</c>) or the compiler (<c>csharp/compiler/</c>) and rerun
/// this, never hand-patch the output. Usage: <c>dotnet run --project
/// csharp/cli/tool/Ball.Cli.Regen.csproj</c>.</para>
///
/// <para>Prerequisite: <c>dart/self_host/cli.ball.json</c>/<c>.pb</c> must already exist —
/// generate with <c>cd dart &amp;&amp; dart run compiler/tool/gen_cli_json.dart</c> first.</para>
/// </summary>
internal static class RegenTool
{
    private const string Header =
        "// <auto-generated> by `dotnet run --project csharp/cli/tool` from dart/self_host/cli.ball.json.\n" +
        "//\n" +
        "// DO NOT EDIT BY HAND. This is the self-hosted Ball CLI core (info/validate/tree/version\n" +
        "// report functions), compiled from `dart/shared/lib/cli_core.dart`'s own Ball encoding\n" +
        "// through the Ball -> C# compiler. To change it, fix `dart/shared/lib/cli_core.dart` (then\n" +
        "// rerun `dart run compiler/tool/gen_cli_json.dart`) or `csharp/compiler/`, and rerun the\n" +
        "// regenerator — never hand-patch this file. See csharp/AGENTS.md.\n" +
        "#nullable disable\n" +
        "#pragma warning disable\n\n";

    /// <summary>
    /// Function names dropped from <c>cli_core</c>'s <c>main</c> module before compiling (issue
    /// #385; #362 residual). <c>auditReport</c> calls <c>capability_analyzer</c>/
    /// <c>termination_analyzer</c> — separate Dart files pulled in via <c>import</c> (not
    /// <c>part</c>), which <c>gen_cli_json.dart</c>'s <c>resolveDartLibrary</c> does not merge,
    /// and which the Dart encoder therefore leaves as <b>empty import-stub modules</b> (0
    /// functions) in <c>cli.ball.json</c>. The Dart-engine self-host parity test tolerates this
    /// silently (<c>audit</c> is simply never invoked), but this compiler performs whole-file AOT
    /// compilation: an unresolved call to <c>analyzeCapabilities</c>/
    /// <c>formatCapabilityReport</c>/<c>analyzeTermination</c>/<c>formatTerminationReport</c>/
    /// <c>writeln</c> is a hard compile error, not a latent runtime gap. Dropping the function
    /// here (a C#-target-only, well-documented workaround — <c>cli_core.dart</c> and the compiler
    /// itself are untouched) keeps the generated file compiling while <c>ball audit</c> stays out
    /// of the C# CLI, mirroring <c>rust/cli/tool/src/main.rs</c>'s identical
    /// <c>SKIPPED_FUNCTIONS</c> filter exactly. Remove this filter once #362 makes
    /// <c>auditReport</c> fully self-hostable (its Dart source needs no change either way).
    /// </summary>
    private static readonly string[] SkippedFunctions = { "auditReport" };

    private static int Main()
    {
        var root = FindRepoRoot();
        var pbPath = Path.Combine(root, "dart", "self_host", "cli.ball.pb");
        var jsonPath = Path.Combine(root, "dart", "self_host", "cli.ball.json");
        var outPath = Path.Combine(root, "csharp", "cli", "src", "CompiledCli.cs");

        Program program;
        if (File.Exists(pbPath))
        {
            Console.Error.WriteLine($"[regen-cli] loading {pbPath}");
            program = LoadBinary(pbPath);
        }
        else if (File.Exists(jsonPath))
        {
            Console.Error.WriteLine($"[regen-cli] loading {jsonPath}");
            program = LoadJson(jsonPath);
        }
        else
        {
            Console.Error.WriteLine(
                $"[regen-cli] neither {pbPath} nor {jsonPath} exists.\n" +
                "            Regenerate the self-host source first:\n" +
                "              cd dart && dart run compiler/tool/gen_cli_json.dart");
            return 1;
        }

        foreach (var module in program.Modules)
        {
            var before = module.Functions.Count;
            for (var i = module.Functions.Count - 1; i >= 0; i--)
            {
                if (Array.IndexOf(SkippedFunctions, module.Functions[i].Name) >= 0)
                {
                    module.Functions.RemoveAt(i);
                }
            }

            var dropped = before - module.Functions.Count;
            if (dropped > 0)
            {
                Console.Error.WriteLine(
                    $"[regen-cli] dropped {dropped} unsupported function(s) from module " +
                    $"\"{module.Name}\": [{string.Join(", ", SkippedFunctions)}]");
            }
        }

        Console.Error.WriteLine(
            $"[regen-cli] compiling program \"{program.Name}\" v{program.Version} " +
            $"({program.Modules.Count} modules)");

        // cli_core is a *library* (it has no runnable top-level entry point — its public surface
        // is the info/validate/tree/version report functions), exactly like the self-hosted
        // engine — Compile() already skips Main emission when no function named EntryFunction
        // exists in the entry module (see CSharpCompiler.CompileProgram).
        var csharp = CSharpCompiler.Compile(program);

        Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);
        File.WriteAllText(outPath, Header + csharp);
        Console.Error.WriteLine($"[regen-cli] wrote {outPath} ({Header.Length + csharp.Length} bytes)");
        return 0;
    }

    /// <summary>
    /// Load a <c>cli.ball.pb</c> — a binary <c>google.protobuf.Any</c> envelope wrapping the
    /// <c>ball.v1.Program</c> — into a typed <see cref="Program"/>.
    /// </summary>
    private static Program LoadBinary(string path)
    {
        var bytes = File.ReadAllBytes(path);
        var any = Any.Parser.ParseFrom(bytes);
        return any.Unpack<Program>();
    }

    /// <summary>
    /// Load a <c>cli.ball.json</c> — a proto3-JSON <c>google.protobuf.Any</c> envelope with an
    /// explicit <c>@type</c> key — into a typed <see cref="Program"/>. The <c>@type</c> key is
    /// stripped before parsing (mirrors <c>csharp/engine/tool/Program.cs</c>).
    /// </summary>
    private static Program LoadJson(string path)
    {
        var json = File.ReadAllText(path);
        using var doc = JsonDocument.Parse(json, new JsonDocumentOptions { MaxDepth = 512 });
        using var stream = new MemoryStream();
        using (var writer = new Utf8JsonWriter(stream))
        {
            writer.WriteStartObject();
            foreach (var property in doc.RootElement.EnumerateObject())
            {
                if (property.NameEquals("@type"))
                {
                    continue;
                }

                property.WriteTo(writer);
            }

            writer.WriteEndObject();
        }

        var body = System.Text.Encoding.UTF8.GetString(stream.ToArray());
        var parser = new JsonParser(new JsonParser.Settings(512).WithIgnoreUnknownFields(true));
        return parser.Parse<Program>(body);
    }

    private static string FindRepoRoot()
    {
        var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
        while (dir is not null)
        {
            if (File.Exists(Path.Combine(dir.FullName, "proto", "ball", "v1", "ball.proto")))
            {
                return dir.FullName;
            }

            dir = dir.Parent;
        }

        throw new InvalidOperationException("not inside the ball repo (no proto/ball/v1/ball.proto found)");
    }
}
