"""Compile the self-hosted engine on first use and cache it (issue #496).

``compiled_engine.py`` is a ~690 KB generated artifact: gitignored in a checkout
(regenerated by ``python -m ball_engine.regen``) and deliberately NOT shipped in
the ``ball-lang`` wheel — the repo never distributes generated code, and a wheel
carries neither the Dart toolchain nor the ~21 MB self-host source in a form the
regenerator could reach.

So the wheel carries the engine's Ball **source** as package data
(``_selfhost/engine.ball.json.gz``, written at build time by
``python/engine/tool/bundle_selfhost.py``) and this module compiles it with the
bundled, pure-Python ``ball_compiler`` the first time ``ball run`` needs it,
caching the result under a per-user cache directory. The compile is cheap — well
under a second for the whole engine — so the first-run cost is a blink, and
every later run is an import.

Resolution order for the Ball source:

1. ``_selfhost/engine.ball.json.gz`` inside the installed package (the wheel);
2. ``dart/self_host/engine.ball.json`` in the surrounding checkout (so a
   developer who has run ``gen_engine_json.dart`` gets the same path without a
   bundling step).

The cache key covers the installed distribution version, the Python
major.minor, and a SHA-256 of the source bytes, so upgrading the wheel — or
regenerating the source — recompiles instead of silently reusing a stale engine.

Everything that can go wrong (no source, an unwritable cache directory, a
compiler failure) raises :class:`BootstrapError` with an actionable message; the
CLI reports it as a clean ``ball: …`` runtime error, never a traceback.
"""

from __future__ import annotations

import gzip
import hashlib
import importlib.util
import json
import os
import sys
import tempfile
from pathlib import Path
from types import ModuleType

__all__ = ["BootstrapError", "load_engine", "cache_root", "cache_key", "source_bytes"]

_BUNDLED_RELATIVE = ("_selfhost", "engine.ball.json.gz")
_MODULE_NAME = "ball_engine._cached_compiled_engine"
_DIST_NAME = "ball-lang"

# One process compiles at most once; the loaded module is reused.
_LOADED: ModuleType | None = None


class BootstrapError(RuntimeError):
    """The self-hosted engine could not be made available, with a reason a user
    can act on."""


def _dist_version() -> str:
    try:
        from importlib.metadata import PackageNotFoundError, version
    except ImportError:  # pragma: no cover - importlib.metadata is stdlib >= 3.8
        return "source"
    try:
        return version(_DIST_NAME)
    except PackageNotFoundError:
        return "source"


def bundled_source_path() -> Path | None:
    """The gzipped Ball source shipped inside the installed package, if present."""
    path = Path(__file__).resolve().parent.joinpath(*_BUNDLED_RELATIVE)
    return path if path.is_file() else None


def checkout_source_path() -> Path | None:
    """``dart/self_host/engine.ball.json`` in the surrounding checkout, if present."""
    d = Path(__file__).resolve().parent
    while d != d.parent:
        if (d / "proto" / "ball" / "v1" / "ball.proto").is_file():
            candidate = d / "dart" / "self_host" / "engine.ball.json"
            return candidate if candidate.is_file() else None
        d = d.parent
    return None


def source_bytes() -> bytes:
    """The self-host Ball program's JSON bytes, from the wheel or the checkout."""
    bundled = bundled_source_path()
    if bundled is not None:
        try:
            return gzip.decompress(bundled.read_bytes())
        except OSError as ex:
            raise BootstrapError(
                f"the bundled self-host engine source at {bundled} is unreadable: {ex}"
            ) from ex
    checkout = checkout_source_path()
    if checkout is not None:
        return checkout.read_bytes()
    raise BootstrapError(
        "the self-hosted Python engine is not available: this install carries no "
        "bundled engine source (ball_engine/_selfhost/engine.ball.json.gz) and no "
        "dart/self_host/engine.ball.json was found nearby.\n"
        "In a checkout, generate it and build compiled_engine.py directly:\n"
        "    cd dart && dart run compiler/tool/gen_engine_json.dart\n"
        "    cd ../python/engine && python -m ball_engine.regen"
    )


def cache_root() -> Path:
    """The per-user cache directory, overridable with ``BALL_CACHE_DIR``.

    Zero-dependency and explicit about every platform, so a container or a
    read-only ``HOME`` can be redirected without installing anything.
    """
    override = os.environ.get("BALL_CACHE_DIR")
    if override:
        return Path(override).expanduser()
    if sys.platform == "win32":
        base = os.environ.get("LOCALAPPDATA") or os.environ.get("APPDATA")
        if base:
            return Path(base) / "ball-lang" / "engine"
        return Path.home() / "AppData" / "Local" / "ball-lang" / "engine"
    xdg = os.environ.get("XDG_CACHE_HOME")
    base_dir = Path(xdg) if xdg else Path.home() / ".cache"
    return base_dir / "ball-lang" / "engine"


def cache_key(src: bytes) -> str:
    """A cache key over (distribution version, Python minor, source digest).

    All three matter: a new wheel may ship a different compiler, a different
    Python minor may byte-compile differently, and the source is the input.
    """
    digest = hashlib.sha256(src).hexdigest()[:32]
    py = f"{sys.version_info.major}.{sys.version_info.minor}"
    return f"{_dist_version()}-py{py}-{digest}"


def _compile_source(src: bytes) -> str:
    try:
        from ball_compiler.compiler import compile_library
    except ImportError as ex:
        raise BootstrapError(
            f"the Ball -> Python compiler is not importable ({ex}); the ball-lang "
            "install is incomplete"
        ) from ex
    try:
        program = json.loads(src.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as ex:
        raise BootstrapError(f"the self-host engine source is not valid JSON: {ex}") from ex
    program.pop("@type", None)  # google.protobuf.Any envelope
    try:
        return compile_library(program)
    except Exception as ex:  # a compiler bug or an unsupported shape — fail loud
        raise BootstrapError(
            f"compiling the self-hosted engine failed: {type(ex).__name__}: {ex}"
        ) from ex


def _write_atomic(target: Path, text: str) -> None:
    """Write ``text`` to ``target`` so a concurrent reader never sees a partial file."""
    try:
        target.parent.mkdir(parents=True, exist_ok=True)
        fd, tmp = tempfile.mkstemp(dir=str(target.parent), suffix=".tmp")
        try:
            with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as fh:
                fh.write(text)
            os.replace(tmp, target)
        finally:
            if os.path.exists(tmp):
                os.unlink(tmp)
    except OSError as ex:
        raise BootstrapError(
            f"could not write the compiled engine cache at {target.parent}: {ex}\n"
            "Set BALL_CACHE_DIR to a writable directory."
        ) from ex


def cached_module_path(src: bytes | None = None) -> Path:
    """Where the compiled engine for ``src`` lives (compiled or not)."""
    if src is None:
        src = source_bytes()
    return cache_root() / cache_key(src) / "compiled_engine.py"


def ensure_compiled(src: bytes | None = None) -> Path:
    """Return the cached compiled-engine path, compiling it on a cache miss."""
    if src is None:
        src = source_bytes()
    path = cached_module_path(src)
    if path.is_file() and path.stat().st_size > 0:
        return path
    _write_atomic(path, _compile_source(src))
    return path


def load_engine(src: bytes | None = None) -> ModuleType:
    """Import the compiled self-hosted engine, compiling+caching it on first use."""
    global _LOADED
    if _LOADED is not None and src is None:
        return _LOADED
    path = ensure_compiled(src)
    spec = importlib.util.spec_from_file_location(_MODULE_NAME, path)
    if spec is None or spec.loader is None:
        raise BootstrapError(f"could not load the compiled engine module at {path}")
    module = importlib.util.module_from_spec(spec)
    # Registered under its own name so the compiled module's own imports and any
    # pickling/introspection resolve, without shadowing ball_engine.compiled_engine.
    sys.modules[_MODULE_NAME] = module
    try:
        spec.loader.exec_module(module)
    except Exception as ex:
        sys.modules.pop(_MODULE_NAME, None)
        raise BootstrapError(
            f"the cached compiled engine at {path} failed to import: "
            f"{type(ex).__name__}: {ex}\nDelete that directory to force a rebuild."
        ) from ex
    if src is None:
        _LOADED = module
    return module
