/// Generates `cpp/shared/ball_program_descriptor.h` — the runtime message
/// descriptors that `ball_protobuf`'s C++ codecs (`ball_protobuf_rt.h`) need to
/// `unmarshal`/`marshal` a `ball.v1.Program` (and `ball.v1.Module`) from binary,
/// with NO Google protobuf. This is Stage 3 of #18 (binary-path cutover).
///
/// ## Minimal, opaque-passthrough descriptor
///
/// The descriptor covers ONLY Ball's own `ball.v1.*` messages. Every field that
/// points at a `google.protobuf.*` message (the `Struct metadata` bags, the
/// `DescriptorProto`/`EnumDescriptorProto` type descriptors) is emitted as an
/// opaque `TYPE_BYTES` field. On the wire a length-delimited message and a
/// `bytes` field are byte-identical (LEN tag + payload), so decoding such a
/// field as raw bytes and re-encoding it verbatim round-trips the exact
/// original bytes. Google then re-parses those bytes back into the real
/// `Struct`/`DescriptorProto`. This deliberately sidesteps proto2 explicit
/// presence, closed-enum, and well-known-type JSON fidelity — none of which the
/// wire round-trip needs — and keeps the generated header small.
///
/// Unknown fields (any number not in the descriptor) are also captured and
/// re-emitted verbatim by the codec, so the round-trip is loss-free even if a
/// field is missed.
///
/// ## Recursion via shared lists
///
/// `ball.v1.Expression` is deeply self-recursive (Expression → Block →
/// Statement → Expression, FunctionCall → Expression, …). In C++ a `BallList`
/// stored inside a `BallDyn` is `shared_ptr`-backed (`BallListRef`), so copying
/// a message's descriptor `BallDyn` into a field's `messageDescriptor` shares
/// the SAME underlying vector. The generated builder therefore uses two phases:
/// (1) create one empty shared list per message FQN, then (2) fill each — a
/// recursive field just references the (possibly not-yet-filled) shared list,
/// exactly mirroring how the Dart `buildRegistry` shares list references.
///
/// Regenerate with:
///   dart run dart/ball_protobuf/tool/gen_program_descriptor_cpp.dart
/// (uses `buf build` on PATH to produce the FileDescriptorSet; pass an explicit
/// `.binpb` path as arg0 to skip buf).
library;

import 'dart:io';

import 'descriptor_bridge.dart';

const String _ballPrefix = 'ball.v1.';

void main(List<String> args) {
  final repoRoot = _findRepoRoot();
  final fdsBytes = _loadFds(repoRoot, args.isNotEmpty ? args[0] : null);
  final registry = buildRegistry(fdsBytes);

  // Reachable ball.v1.* messages from both top-level loader entry points
  // (Program and Module — a ball file can carry either).
  final roots = [
    'ball.v1.Program',
    'ball.v1.Module',
  ].where(registry.containsKey).toList();
  if (roots.isEmpty) {
    stderr.writeln('No ball.v1.Program/Module in descriptor set — aborting.');
    exit(1);
  }
  final reachable = _reachable(registry, roots);

  final buf = StringBuffer();
  _emitHeader(buf, reachable, registry);

  final outPath = '$repoRoot/cpp/shared/ball_program_descriptor.h';
  File(outPath).writeAsStringSync(buf.toString());
  stdout.writeln(
    'Wrote $outPath (${reachable.length} ball.v1 messages, '
    '${File(outPath).lengthSync()} bytes)',
  );
}

/// BFS over message-typed fields, following only `ball.v1.*` references
/// (google.protobuf.* fields become opaque bytes and need no sub-descriptor).
Set<String> _reachable(DescriptorRegistry registry, List<String> roots) {
  final seen = <String>{};
  final queue = <String>[...roots];
  while (queue.isNotEmpty) {
    final fqn = queue.removeLast();
    if (!seen.add(fqn)) continue;
    for (final field in registry[fqn] ?? const []) {
      final typeName = field['typeName'] as String?;
      if (typeName != null &&
          typeName.startsWith(_ballPrefix) &&
          registry.containsKey(typeName)) {
        if (!seen.contains(typeName)) queue.add(typeName);
      }
    }
  }
  return seen;
}

void _emitHeader(
  StringBuffer b,
  Set<String> reachable,
  DescriptorRegistry registry,
) {
  final ordered = reachable.toList()..sort();

  b.writeln(
    '// GENERATED by dart/ball_protobuf/tool/gen_program_descriptor_cpp.dart',
  );
  b.writeln('// DO NOT EDIT. Regenerate via:');
  b.writeln(
    '//   dart run dart/ball_protobuf/tool/gen_program_descriptor_cpp.dart',
  );
  b.writeln('//');
  b.writeln(
    '// Minimal ball.v1 message descriptors for ball_protobuf_rt.h. Every',
  );
  b.writeln(
    '// google.protobuf.* field is an opaque TYPE_BYTES passthrough (a message',
  );
  b.writeln(
    '// and a bytes field are byte-identical on the wire), so the descriptor',
  );
  b.writeln(
    '// needs no descriptor.proto / struct.proto closure and round-trips the',
  );
  b.writeln('// original bytes verbatim. See #18 Stage 3.');
  b.writeln('#pragma once');
  b.writeln();
  b.writeln('#include <any>');
  b.writeln('#include <map>');
  b.writeln('#include <string>');
  b.writeln();
  b.writeln('#include "ball_protobuf_rt.h"');
  b.writeln();
  b.writeln('namespace ball_protobuf {');
  b.writeln('namespace descriptor {');
  b.writeln();
  b.writeln(
    '// Appends one field descriptor to message [msg]\'s shared field list.',
  );
  b.writeln(
    '// [refType], when non-null, is a ball.v1.* FQN whose shared descriptor list',
  );
  b.writeln(
    '// is referenced (copied BallDyn shares the underlying vector -> recursion).',
  );
  b.writeln(
    'inline void _push(std::map<std::string, BallDyn>& r, const char* msg,',
  );
  b.writeln(
    '                  const char* name, long long number, const char* type,',
  );
  b.writeln(
    '                  const char* label, bool repeated, const char* refType,',
  );
  b.writeln('                  const char* oneof, bool mapEntry,');
  b.writeln('                  const char* keyType, const char* valueType) {');
  b.writeln('  BallMap m;');
  b.writeln('  m["name"s] = std::any(std::string(name));');
  b.writeln('  m["number"s] = std::any(static_cast<int64_t>(number));');
  b.writeln('  m["type"s] = std::any(std::string(type));');
  b.writeln('  if (label) m["label"s] = std::any(std::string(label));');
  b.writeln('  if (repeated) m["repeated"s] = std::any(true);');
  b.writeln('  if (refType) {');
  b.writeln('    m["typeName"s] = std::any(std::string(refType));');
  b.writeln('    m["messageDescriptor"s] = std::any(r.at(refType));');
  b.writeln('  }');
  b.writeln('  if (oneof) m["oneof"s] = std::any(std::string(oneof));');
  b.writeln('  if (mapEntry) {');
  b.writeln('    m["mapEntry"s] = std::any(true);');
  b.writeln('    m["keyType"s] = std::any(std::string(keyType));');
  b.writeln('    m["valueType"s] = std::any(std::string(valueType));');
  b.writeln('  }');
  b.writeln(
    '  r.at(msg)._listPtr()->push_back(std::any(BallDyn(std::move(m))));',
  );
  b.writeln('}');
  b.writeln();
  b.writeln(
    '// Builds the ball.v1 descriptor registry once (thread-safe static init).',
  );
  b.writeln('inline const std::map<std::string, BallDyn>& _registry() {');
  b.writeln('  static const std::map<std::string, BallDyn> reg = [] {');
  b.writeln('    std::map<std::string, BallDyn> r;');
  b.writeln('    // Phase 1: one empty shared field-list per message.');
  for (final fqn in ordered) {
    b.writeln('    r["$fqn"] = BallDyn(BallList{});');
  }
  b.writeln(
    '    // Phase 2: populate fields (recursive refs share the lists above).',
  );
  for (final fqn in ordered) {
    for (final field in registry[fqn]!) {
      b.writeln(_emitPush(fqn, field, reachable));
    }
  }
  b.writeln('    return r;');
  b.writeln('  }();');
  b.writeln('  return reg;');
  b.writeln('}');
  b.writeln();
  b.writeln('// The ball.v1.Program descriptor (shared list — cheap to copy).');
  b.writeln(
    'inline BallDyn programDescriptor() { return _registry().at("ball.v1.Program"); }',
  );
  b.writeln();
  b.writeln('// The ball.v1.Module descriptor.');
  b.writeln(
    'inline BallDyn moduleDescriptor() { return _registry().at("ball.v1.Module"); }',
  );
  b.writeln();
  b.writeln('}  // namespace descriptor');
  b.writeln('}  // namespace ball_protobuf');
}

String _emitPush(
  String msgFqn,
  Map<String, Object?> field,
  Set<String> reachable,
) {
  final name = field['name'] as String;
  final number = field['number'] as int;
  var type = field['type'] as String;
  final label = field['label'] as String?;
  final repeated = field['repeated'] == true;
  final typeName = field['typeName'] as String?;
  final oneof = field['oneof'] as String?;
  final mapEntry = field['mapEntry'] == true;

  String? refType;
  String? keyType;
  String? valueType;
  if (mapEntry) {
    keyType = field['keyType'] as String;
    valueType = field['valueType'] as String;
    // Ball has only map<string,string> (HttpSource.headers); a message-valued
    // map would need refType — none exist in ball.v1, so none is emitted.
  } else if (typeName != null &&
      typeName.startsWith(_ballPrefix) &&
      reachable.contains(typeName)) {
    // Recursive ball MESSAGE reference. Guarded by `reachable` (the emitted
    // registry keys): a ball.v1 ENUM (Registry, ModuleEncoding) also carries a
    // ball.v1.* typeName but is NOT a message — emitting it as refType made
    // `r.at("ball.v1.Registry")` throw std::out_of_range at static init.
    refType = typeName;
  } else if (typeName != null && typeName.startsWith('google.protobuf.')) {
    // Opaque passthrough: message/group => bytes (wire-identical), so no
    // descriptor.proto / struct.proto closure is needed.
    type = 'TYPE_BYTES';
  }
  // Anything else (TYPE_ENUM with a non-registry typeName, plain scalars) is
  // emitted as-is: the binary codec treats an enum as a varint int32, which
  // round-trips the wire value without needing enumValues/enumNames.

  String cstr(String? s) => s == null ? 'nullptr' : '"${_esc(s)}"';
  return '    _push(r, "$msgFqn", "${_esc(name)}", $number, "$type", '
      '${cstr(label)}, $repeated, ${cstr(refType)}, ${cstr(oneof)}, '
      '$mapEntry, ${cstr(keyType)}, ${cstr(valueType)});';
}

String _esc(String s) => s.replaceAll('\\', '\\\\').replaceAll('"', '\\"');

List<int> _loadFds(String repoRoot, String? explicit) {
  if (explicit != null) {
    return File(explicit).readAsBytesSync();
  }
  // Build a FileDescriptorSet from the repo's protos via buf (host tool).
  // Scope buf to the proto/ module (proto/buf.yaml): an unscoped `buf build`
  // at the repo root also scans FetchContent'd third-party protos under
  // cpp/build*/_deps/protobuf-src/** and fails on their unstable editions.
  final tmp = File('${Directory.systemTemp.path}/ball_program_fds_$pid.binpb');
  final result = Process.runSync(
    'buf',
    ['build', 'proto', '-o', tmp.path],
    workingDirectory: repoRoot,
    runInShell: true,
  );
  if (result.exitCode != 0) {
    stderr.writeln('buf build failed (exit ${result.exitCode}):');
    stderr.writeln(result.stderr);
    stderr.writeln('Pass a prebuilt FileDescriptorSet .binpb path as arg0.');
    exit(1);
  }
  final bytes = tmp.readAsBytesSync();
  if (tmp.existsSync()) {
    tmp.deleteSync();
  }
  return bytes;
}

String _findRepoRoot() {
  var dir = Directory.current;
  while (true) {
    if (File('${dir.path}/proto/ball/v1/ball.proto').existsSync()) {
      return dir.path.replaceAll('\\', '/');
    }
    final parent = dir.parent;
    if (parent.path == dir.path) {
      throw StateError('Not in ball repo (no proto/ball/v1/ball.proto found)');
    }
    dir = parent;
  }
}
