// Package compiled holds the self-hosted Ball CLI core compiled from
// dart/self_host/cli.ball.pb through the Ball → Go compiler (issue #570) — the
// Go sibling of rust/cli's compiled_cli.rs and csharp/cli's CompiledCli.cs.
//
// The generated compiled_cli.go is a gitignored build artifact (regenerated by
// `go run ./cmd/regen`). Both it and the hand-written driver.go are behind the
// `clicore` build tag, so on a fresh checkout — where compiled_cli.go is absent
// — this package is just this doc file and a default `go build ./...` stays
// green.
//
// The tag is deliberately NOT `selfhost`: info/validate/tree/version are pure
// Program → String report functions that never touch the interpreter, so they
// are gated independently of the engine, exactly like Rust's `cli_core` Cargo
// feature (separate from `self_host`) and C#'s `-p:CliCore=true` (separate from
// `-p:SelfHost=true`). Both tags can be combined: `go build -tags "clicore
// selfhost"`.
package compiled
