// Package compiled holds the self-hosted Ball CLI core compiled from
// dart/self_host/cli.ball.pb through the Ball → Go compiler (issue #570) — the
// Go sibling of rust/cli's compiled_cli.rs and csharp/cli's CompiledCli.cs.
//
// The generated compiled_cli.go is a TRACKED build artifact (issue #586),
// regenerated by `go run ./cmd/regen` and gated by ci.yml's `Ball Artifact
// Freshness` regen-and-diff job — the same contract ts/cli's compiled_cli.ts has
// had since #580. It carries no build constraint: it used to be gitignored and
// `clicore`-tagged, but `go install` accepts no `-tags` and the module a proxy
// serves is the repository AT THE TAG, so `ball info|validate|tree|version` on a
// registry-acquired binary answered with an exit-1 regenerate hint (#586). Rust
// and C# keep their `cli_core` feature / `-p:CliCore=true` property because
// their registry channels regenerate at publish time; Go has no such step.
package compiled
