// Generated by ball compiler (C++ target)
// Source: encoded v1.0.0

#include <iostream>
#include <string>
#include <vector>
#include <map>
#include <unordered_map>
#include <any>
#include <functional>
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <sstream>
#include <stdexcept>
#include <cassert>
#include <regex>

using namespace std::string_literals;

// ball_emit_runtime.h — single source of truth for the small runtime
// helpers that are embedded into every compiler-emitted C++ program.
//
// This file is:
//   1. #included by the ball C++ engine (via ball_shared.h) so the
//      interpreter uses the same formatting as compiled programs.
//   2. Slurped verbatim at CMake configure time and embedded as a
//      C++ string constant in `ball_emit_runtime_embed.h`, which the
//      compiler splices into the preamble of every emitted program.
//
// Changes here automatically propagate to both sides. Keep the file
// self-contained: the compiler's emit_includes already brings in
// <string>, <sstream>, <stdexcept>, <cmath> — don't add #includes.

#ifndef BALL_EMIT_RUNTIME_H
#define BALL_EMIT_RUNTIME_H

// Minimal Ball exception type used by `throw` / `try` to preserve
// typed-catch semantics. Derives from std::exception so untyped
// `catch (const std::exception&)` clauses still match.
//
// `fields` holds the individual field values when the thrown Ball
// value was a messageCreation (e.g. `{__type: 'NotFound', detail: 'x'}`).
// Catch-side field access (`e.detail` in Ball IR) compiles to
// `e.fields.at("detail")` so the original structured payload round-trips.
struct BallException : public std::runtime_error {
    std::string type_name;
    std::map<std::string, std::string> fields;
    BallException(std::string t, std::string msg)
        : std::runtime_error(msg), type_name(std::move(t)) {}
    BallException(std::string t, std::string msg,
                  std::map<std::string, std::string> f)
        : std::runtime_error(msg), type_name(std::move(t)),
          fields(std::move(f)) {}
};

// Stream inserter so `print(e)` on a catch-bound BallException works
// (it falls through to printing `.what()`, matching the old
// string-binding behavior for plain-string throws).
inline std::ostream& operator<<(std::ostream& os, const BallException& e) {
    return os << e.what();
}

// Dart-compatible string conversion. Handles bool and doubles so
// compiled programs produce the same output as the Dart engine
// (e.g. `true` instead of `1`, `6.0` instead of `6.000000`).
inline std::string ball_to_string(bool b) { return b ? std::string("true") : std::string("false"); }
inline std::string ball_to_string(const std::string& s) { return s; }
inline std::string ball_to_string(const char* s) { return s; }
inline std::string ball_to_string(double d) {
    if (d != d) return "NaN";
    if (d > 1e308 || d < -1e308) return d < 0 ? "-Infinity" : "Infinity";
    if (d == static_cast<double>(static_cast<long long>(d)) && d < 1e16 && d > -1e16) {
        return std::to_string(static_cast<long long>(d)) + ".0";
    }
    std::ostringstream oss;
    oss.precision(15);
    oss << d;
    auto s = oss.str();
    if (s.find('.') != std::string::npos) {
        while (s.size() > 1 && s.back() == '0') s.pop_back();
        if (s.back() == '.') s.push_back('0');
    }
    return s;
}

// Forward declare for vector recursion before the template catch-all.
template<typename T> inline std::string ball_to_string(const std::vector<T>& v);

template<typename T> inline std::string ball_to_string(T v) { return std::to_string(v); }

// Lists render as Dart-style `[a, b, c]`. Each element uses
// ball_to_string so nested structures / bools / doubles all follow
// the Dart conventions.
template<typename T>
inline std::string ball_to_string(const std::vector<T>& v) {
    std::string out = "[";
    bool first = true;
    for (const auto& el : v) {
        if (!first) out += ", ";
        out += ball_to_string(el);
        first = false;
    }
    out += "]";
    return out;
}

#endif  // BALL_EMIT_RUNTIME_H


bool sideEffect(std::string tag, bool v) {
    std::cout << ("eval:"s + ball_to_string(tag)) << std::endl;
    return v;
}

int main() {
    std::cout << ball_to_string((sideEffect("a"s, false) && sideEffect("b"s, true))) << std::endl;
    std::cout << ball_to_string((sideEffect("c"s, true) || sideEffect("d"s, false))) << std::endl;
    std::cout << ball_to_string((sideEffect("e"s, true) && sideEffect("f"s, false))) << std::endl;
    return 0;
}
