/**
 * Runtime preamble prepended to every compiled TS output.
 *
 * Contains:
 *   - Helpers for Dart-flavored string conversion / parsing
 *   - Polyfills for Dart-flavored Array / Map / String methods that
 *     don't exist on JS prototypes (containsKey, addAll, removeLast,
 *     isEmpty/isNotEmpty/first/last, etc.)
 *   - A `__ball_active_error` module-level binding used by `rethrow`
 *
 * Node strips the TS type annotations at runtime via
 * `--experimental-strip-types`, so the `any` annotations and interface
 * declarations below are type-check only — they have no runtime cost.
 */
export const TS_RUNTIME_PREAMBLE = String.raw`// ── Ball runtime preamble (generated by @ball-lang/compiler) ────────

function __ball_to_string(v: any): string {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'number') {
    if (Number.isInteger(v)) return v.toString();
    const s = v.toString();
    return s.includes('.') || s.includes('e') ? s : s + '.0';
  }
  if (typeof v === 'string') return v;
  if (Array.isArray(v)) {
    return '[' + v.map(__ball_to_string).join(', ') + ']';
  }
  if (v instanceof Map) {
    const parts: string[] = [];
    for (const [k, val] of v.entries()) {
      parts.push(__ball_to_string(k) + ': ' + __ball_to_string(val));
    }
    return '{' + parts.join(', ') + '}';
  }
  return String(v);
}

function __ball_parse_int(s: string): number {
  const trimmed = s.trim();
  if (!/^-?\d+$/.test(trimmed)) {
    throw new Error('FormatException: ' + s);
  }
  return parseInt(trimmed, 10);
}

function __ball_parse_double(s: string): number {
  const n = parseFloat(s);
  if (Number.isNaN(n)) throw new Error('FormatException: ' + s);
  return n;
}

function __ball_double_to_string(n: number): string {
  if (Number.isInteger(n)) return n.toFixed(1);
  return n.toString();
}

// Active exception for rethrow. Catch bodies shadow with a local.
let __ball_active_error: any = undefined;

// ── Dart \u2192 JS method-name polyfills ────────────────────────────────
//
// Idempotent: guarded so multiple preamble inclusions don't double-install.
(function installBallPolyfills() {
  const mp: any = Map.prototype;
  if (!mp.containsKey) mp.containsKey = function (k: any) { return this.has(k); };
  if (!mp.putIfAbsent) {
    mp.putIfAbsent = function (k: any, supplier: any) {
      if (!this.has(k)) this.set(k, supplier());
      return this.get(k);
    };
  }
  if (!mp.addAll) {
    mp.addAll = function (other: any) {
      if (other instanceof Map) {
        for (const [k, v] of other.entries()) this.set(k, v);
      } else if (other && typeof other === 'object') {
        for (const k of Object.keys(other)) this.set(k, other[k]);
      }
    };
  }
  Object.defineProperty(mp, 'isEmpty', {
    configurable: true, get() { return this.size === 0; },
  });
  Object.defineProperty(mp, 'isNotEmpty', {
    configurable: true, get() { return this.size !== 0; },
  });

  const ap: any = Array.prototype;
  if (!ap.add) ap.add = function (v: any) { this.push(v); };
  if (!ap.addAll) ap.addAll = function (iter: any) {
    for (const v of iter) this.push(v);
  };
  if (!ap.removeLast) ap.removeLast = function () { return this.pop(); };
  if (!ap.where) ap.where = Array.prototype.filter;
  if (!ap.toList) ap.toList = function () { return this.slice(); };
  if (!ap.toSet) ap.toSet = function () { return new Set(this); };
  if (!ap.contains) ap.contains = function (v: any) { return this.indexOf(v) >= 0; };
  Object.defineProperty(ap, 'isEmpty', {
    configurable: true, get() { return this.length === 0; },
  });
  Object.defineProperty(ap, 'isNotEmpty', {
    configurable: true, get() { return this.length !== 0; },
  });
  Object.defineProperty(ap, 'first', {
    configurable: true, get() { return this[0]; },
  });
  Object.defineProperty(ap, 'last', {
    configurable: true, get() { return this[this.length - 1]; },
  });

  const sp: any = String.prototype;
  Object.defineProperty(sp, 'isEmpty', {
    configurable: true, get() { return this.length === 0; },
  });
  Object.defineProperty(sp, 'isNotEmpty', {
    configurable: true, get() { return this.length !== 0; },
  });
})();
`;
